/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * BizReq.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-27 Created
 */
package java.request;

import java.io.Serializable;

public class BizReq implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 业务名称
     */
    private String bizName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jhi_biz
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz.ID
     *
     * @return the value of jhi_biz.ID
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz.ID
     *
     * @param id the value for jhi_biz.ID
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz.BIZ_NAME
     *
     * @return the value of jhi_biz.BIZ_NAME
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz.BIZ_NAME
     *
     * @param bizName the value for jhi_biz.BIZ_NAME
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jhi_biz
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BizReq other = (BizReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBizName() == null ? other.getBizName() == null : this.getBizName().equals(other.getBizName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jhi_biz
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBizName() == null) ? 0 : getBizName().hashCode());
        return result;
    }
}