/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * CompanyReq.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-27 Created
 */
package java.request;

import java.io.Serializable;
import java.util.Date;

public class CompanyReq implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 权限名称
     */
    private String name;

    /**
     * 编码
     */
    private String code;

    /**
     * 级别
     */
    private Short level;

    /**
     * 父节点
     */
    private Long parentId;

    /**
     * 创建人
     */
    private String createdBy;

    /**
     * 创建时间
     */
    private Date createdDate;

    /**
     * 修改人
     */
    private String lastModifiedBy;

    /**
     * 修改时间
     */
    private Date lastModifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jhi_role
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.ID
     *
     * @return the value of jhi_role.ID
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.ID
     *
     * @param id the value for jhi_role.ID
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.NAME
     *
     * @return the value of jhi_role.NAME
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.NAME
     *
     * @param name the value for jhi_role.NAME
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.CODE
     *
     * @return the value of jhi_role.CODE
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.CODE
     *
     * @param code the value for jhi_role.CODE
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.LEVEL
     *
     * @return the value of jhi_role.LEVEL
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.LEVEL
     *
     * @param level the value for jhi_role.LEVEL
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setLevel(Short level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.PARENT_ID
     *
     * @return the value of jhi_role.PARENT_ID
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.PARENT_ID
     *
     * @param parentId the value for jhi_role.PARENT_ID
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.CREATED_BY
     *
     * @return the value of jhi_role.CREATED_BY
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.CREATED_BY
     *
     * @param createdBy the value for jhi_role.CREATED_BY
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.CREATED_DATE
     *
     * @return the value of jhi_role.CREATED_DATE
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.CREATED_DATE
     *
     * @param createdDate the value for jhi_role.CREATED_DATE
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.LAST_MODIFIED_BY
     *
     * @return the value of jhi_role.LAST_MODIFIED_BY
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for jhi_role.LAST_MODIFIED_BY
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy == null ? null : lastModifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_role.LAST_MODIFIED_DATE
     *
     * @return the value of jhi_role.LAST_MODIFIED_DATE
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_role.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for jhi_role.LAST_MODIFIED_DATE
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jhi_role
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CompanyReq other = (CompanyReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getLastModifiedBy() == null ? other.getLastModifiedBy() == null : this.getLastModifiedBy().equals(other.getLastModifiedBy()))
            && (this.getLastModifiedDate() == null ? other.getLastModifiedDate() == null : this.getLastModifiedDate().equals(other.getLastModifiedDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jhi_role
     *
     * @mbggenerated Thu Jul 27 10:24:17 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getLastModifiedBy() == null) ? 0 : getLastModifiedBy().hashCode());
        result = prime * result + ((getLastModifiedDate() == null) ? 0 : getLastModifiedDate().hashCode());
        return result;
    }
}