/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * NichePushDetailReq.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-28 Created
 */
package java.request;

import java.io.Serializable;
import java.util.Date;

public class NichePushDetailReq implements Serializable {
    private Long id;

    /**
     * 推送ID，关联trade_niche_push.id
     */
    private Long pushId;

    /**
     * 报价联系人
     */
    private String linkMan;

    /**
     * 联系电话
     */
    private String linkPhone;

    /**
     * 推送至公司ID
     */
    private Long pushCompanyId;

    /**
     * 推送至公司名称
     */
    private String pushCompanyName;

    /**
     * 报价/回复时间
     */
    private Date offerTime;

    /**
     * 报价内容，留言
     */
    private String offerNote;

    /**
     * 报价状态，0未提交，1已提交
     */
    private Short offerStatus;

    /**
     * 处理人ID，关联trade_operation_user.user_id
     */
    private Long handlePersonId;

    /**
     * 处理人姓名
     */
    private String handlePersonName;

    /**
     * 处理意见
     */
    private String handleOpinions;

    /**
     * 处理时间
     */
    private Date handleTime;

    /**
     * 是否已处理，0否，1是
     */
    private Short isHandle;

    /**
     * 创建人ID
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改人ID
     */
    private Long updateId;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 商机类型，0代理采购，1采购，2商讯，3商品
     */
    private Short nicheType;

    /**
     * 商机标题
     */
    private String nicheTitle;

    /**
     * 商机ID，type=0关联代理采购表trade_agent_purchase.id，type=1关联采购表type=2关联商讯trade_bus_info.id，type=3关联采购表trade_demand_main.demand_id
     */
    private Long nicheId;

    /**
     * 推送类型，0按条件，1按账号
     */
    private Short pushType;

    /**
     * 推送时间
     */
    private Date pushTime;

    /**
     * 推送状态，0未撤回，1已撤回
     */
    private Short pushStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.id
     *
     * @return the value of trade_niche_push_detail.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.id
     *
     * @param id the value for trade_niche_push_detail.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.push_id
     *
     * @return the value of trade_niche_push_detail.push_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getPushId() {
        return pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.push_id
     *
     * @param pushId the value for trade_niche_push_detail.push_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushId(Long pushId) {
        this.pushId = pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.link_man
     *
     * @return the value of trade_niche_push_detail.link_man
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.link_man
     *
     * @param linkMan the value for trade_niche_push_detail.link_man
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.link_phone
     *
     * @return the value of trade_niche_push_detail.link_phone
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.link_phone
     *
     * @param linkPhone the value for trade_niche_push_detail.link_phone
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone == null ? null : linkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.push_company_id
     *
     * @return the value of trade_niche_push_detail.push_company_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getPushCompanyId() {
        return pushCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.push_company_id
     *
     * @param pushCompanyId the value for trade_niche_push_detail.push_company_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushCompanyId(Long pushCompanyId) {
        this.pushCompanyId = pushCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.push_company_name
     *
     * @return the value of trade_niche_push_detail.push_company_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getPushCompanyName() {
        return pushCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.push_company_name
     *
     * @param pushCompanyName the value for trade_niche_push_detail.push_company_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushCompanyName(String pushCompanyName) {
        this.pushCompanyName = pushCompanyName == null ? null : pushCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.offer_time
     *
     * @return the value of trade_niche_push_detail.offer_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getOfferTime() {
        return offerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.offer_time
     *
     * @param offerTime the value for trade_niche_push_detail.offer_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setOfferTime(Date offerTime) {
        this.offerTime = offerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.offer_note
     *
     * @return the value of trade_niche_push_detail.offer_note
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getOfferNote() {
        return offerNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.offer_note
     *
     * @param offerNote the value for trade_niche_push_detail.offer_note
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setOfferNote(String offerNote) {
        this.offerNote = offerNote == null ? null : offerNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.offer_status
     *
     * @return the value of trade_niche_push_detail.offer_status
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getOfferStatus() {
        return offerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.offer_status
     *
     * @param offerStatus the value for trade_niche_push_detail.offer_status
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setOfferStatus(Short offerStatus) {
        this.offerStatus = offerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.handle_person_id
     *
     * @return the value of trade_niche_push_detail.handle_person_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getHandlePersonId() {
        return handlePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.handle_person_id
     *
     * @param handlePersonId the value for trade_niche_push_detail.handle_person_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setHandlePersonId(Long handlePersonId) {
        this.handlePersonId = handlePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.handle_person_name
     *
     * @return the value of trade_niche_push_detail.handle_person_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getHandlePersonName() {
        return handlePersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.handle_person_name
     *
     * @param handlePersonName the value for trade_niche_push_detail.handle_person_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setHandlePersonName(String handlePersonName) {
        this.handlePersonName = handlePersonName == null ? null : handlePersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.handle_opinions
     *
     * @return the value of trade_niche_push_detail.handle_opinions
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getHandleOpinions() {
        return handleOpinions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.handle_opinions
     *
     * @param handleOpinions the value for trade_niche_push_detail.handle_opinions
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setHandleOpinions(String handleOpinions) {
        this.handleOpinions = handleOpinions == null ? null : handleOpinions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.handle_time
     *
     * @return the value of trade_niche_push_detail.handle_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.handle_time
     *
     * @param handleTime the value for trade_niche_push_detail.handle_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.is_handle
     *
     * @return the value of trade_niche_push_detail.is_handle
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getIsHandle() {
        return isHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.is_handle
     *
     * @param isHandle the value for trade_niche_push_detail.is_handle
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setIsHandle(Short isHandle) {
        this.isHandle = isHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.create_id
     *
     * @return the value of trade_niche_push_detail.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.create_id
     *
     * @param createId the value for trade_niche_push_detail.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.create_time
     *
     * @return the value of trade_niche_push_detail.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.create_time
     *
     * @param createTime the value for trade_niche_push_detail.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.update_id
     *
     * @return the value of trade_niche_push_detail.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.update_id
     *
     * @param updateId the value for trade_niche_push_detail.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.update_time
     *
     * @return the value of trade_niche_push_detail.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.update_time
     *
     * @param updateTime the value for trade_niche_push_detail.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.niche_type
     *
     * @return the value of trade_niche_push_detail.niche_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getNicheType() {
        return nicheType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.niche_type
     *
     * @param nicheType the value for trade_niche_push_detail.niche_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setNicheType(Short nicheType) {
        this.nicheType = nicheType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.niche_title
     *
     * @return the value of trade_niche_push_detail.niche_title
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getNicheTitle() {
        return nicheTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.niche_title
     *
     * @param nicheTitle the value for trade_niche_push_detail.niche_title
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setNicheTitle(String nicheTitle) {
        this.nicheTitle = nicheTitle == null ? null : nicheTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.niche_id
     *
     * @return the value of trade_niche_push_detail.niche_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getNicheId() {
        return nicheId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.niche_id
     *
     * @param nicheId the value for trade_niche_push_detail.niche_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setNicheId(Long nicheId) {
        this.nicheId = nicheId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.push_type
     *
     * @return the value of trade_niche_push_detail.push_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.push_type
     *
     * @param pushType the value for trade_niche_push_detail.push_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushType(Short pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.push_time
     *
     * @return the value of trade_niche_push_detail.push_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getPushTime() {
        return pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.push_time
     *
     * @param pushTime the value for trade_niche_push_detail.push_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushTime(Date pushTime) {
        this.pushTime = pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push_detail.push_status
     *
     * @return the value of trade_niche_push_detail.push_status
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push_detail.push_status
     *
     * @param pushStatus the value for trade_niche_push_detail.push_status
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushStatus(Short pushStatus) {
        this.pushStatus = pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NichePushDetailReq other = (NichePushDetailReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPushId() == null ? other.getPushId() == null : this.getPushId().equals(other.getPushId()))
            && (this.getLinkMan() == null ? other.getLinkMan() == null : this.getLinkMan().equals(other.getLinkMan()))
            && (this.getLinkPhone() == null ? other.getLinkPhone() == null : this.getLinkPhone().equals(other.getLinkPhone()))
            && (this.getPushCompanyId() == null ? other.getPushCompanyId() == null : this.getPushCompanyId().equals(other.getPushCompanyId()))
            && (this.getPushCompanyName() == null ? other.getPushCompanyName() == null : this.getPushCompanyName().equals(other.getPushCompanyName()))
            && (this.getOfferTime() == null ? other.getOfferTime() == null : this.getOfferTime().equals(other.getOfferTime()))
            && (this.getOfferNote() == null ? other.getOfferNote() == null : this.getOfferNote().equals(other.getOfferNote()))
            && (this.getOfferStatus() == null ? other.getOfferStatus() == null : this.getOfferStatus().equals(other.getOfferStatus()))
            && (this.getHandlePersonId() == null ? other.getHandlePersonId() == null : this.getHandlePersonId().equals(other.getHandlePersonId()))
            && (this.getHandlePersonName() == null ? other.getHandlePersonName() == null : this.getHandlePersonName().equals(other.getHandlePersonName()))
            && (this.getHandleOpinions() == null ? other.getHandleOpinions() == null : this.getHandleOpinions().equals(other.getHandleOpinions()))
            && (this.getHandleTime() == null ? other.getHandleTime() == null : this.getHandleTime().equals(other.getHandleTime()))
            && (this.getIsHandle() == null ? other.getIsHandle() == null : this.getIsHandle().equals(other.getIsHandle()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getNicheType() == null ? other.getNicheType() == null : this.getNicheType().equals(other.getNicheType()))
            && (this.getNicheTitle() == null ? other.getNicheTitle() == null : this.getNicheTitle().equals(other.getNicheTitle()))
            && (this.getNicheId() == null ? other.getNicheId() == null : this.getNicheId().equals(other.getNicheId()))
            && (this.getPushType() == null ? other.getPushType() == null : this.getPushType().equals(other.getPushType()))
            && (this.getPushTime() == null ? other.getPushTime() == null : this.getPushTime().equals(other.getPushTime()))
            && (this.getPushStatus() == null ? other.getPushStatus() == null : this.getPushStatus().equals(other.getPushStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPushId() == null) ? 0 : getPushId().hashCode());
        result = prime * result + ((getLinkMan() == null) ? 0 : getLinkMan().hashCode());
        result = prime * result + ((getLinkPhone() == null) ? 0 : getLinkPhone().hashCode());
        result = prime * result + ((getPushCompanyId() == null) ? 0 : getPushCompanyId().hashCode());
        result = prime * result + ((getPushCompanyName() == null) ? 0 : getPushCompanyName().hashCode());
        result = prime * result + ((getOfferTime() == null) ? 0 : getOfferTime().hashCode());
        result = prime * result + ((getOfferNote() == null) ? 0 : getOfferNote().hashCode());
        result = prime * result + ((getOfferStatus() == null) ? 0 : getOfferStatus().hashCode());
        result = prime * result + ((getHandlePersonId() == null) ? 0 : getHandlePersonId().hashCode());
        result = prime * result + ((getHandlePersonName() == null) ? 0 : getHandlePersonName().hashCode());
        result = prime * result + ((getHandleOpinions() == null) ? 0 : getHandleOpinions().hashCode());
        result = prime * result + ((getHandleTime() == null) ? 0 : getHandleTime().hashCode());
        result = prime * result + ((getIsHandle() == null) ? 0 : getIsHandle().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getNicheType() == null) ? 0 : getNicheType().hashCode());
        result = prime * result + ((getNicheTitle() == null) ? 0 : getNicheTitle().hashCode());
        result = prime * result + ((getNicheId() == null) ? 0 : getNicheId().hashCode());
        result = prime * result + ((getPushType() == null) ? 0 : getPushType().hashCode());
        result = prime * result + ((getPushTime() == null) ? 0 : getPushTime().hashCode());
        result = prime * result + ((getPushStatus() == null) ? 0 : getPushStatus().hashCode());
        return result;
    }
}