/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * NichePushReq.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-28 Created
 */
package java.request;

import java.io.Serializable;
import java.util.Date;

public class NichePushReq implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 推送时间
     */
    private Date pushTime;

    /**
     * 推送状态，0未撤回，1已撤回
     */
    private Short pushStatus;

    /**
     * 撤回时间
     */
    private Date withdrawTime;

    /**
     * 撤回人员ID，关联trade_operation_user.id
     */
    private Long withdrawUserId;

    /**
     * 商机类型，0代理采购，1采购，2商讯，3商品
     */
    private Short nicheType;

    /**
     * 商机标题
     */
    private String nicheTitle;

    /**
     * 商机ID，type=0关联代理采购表trade_agent_purchase.id，type=1关联采购表type=2关联商讯trade_bus_info.id，type=3关联采购表trade_demand_main.demand_id
     */
    private Long nicheId;

    /**
     * 推送类型，0按条件，1按账号
     */
    private Short pushType;

    /**
     * 推送至行政区划代码，多个之间英文逗号分隔
     */
    private String areaCode;

    /**
     * 推送至地区名称，多个之间英文逗号分隔
     */
    private String areaName;

    /**
     * 推送至手机号码
     */
    private String userMobileNo;

    /**
     * 推送至用户名称
     */
    private String userFullname;

    /**
     * 推送企业数量
     */
    private Integer pushConmapyCount;

    /**
     * 创建人ID
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改人ID
     */
    private Long updateId;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 批量插入顺序码
     */
    private Long seq;

    /**
     * 推送至行业id 对应trade_industry.industry_id
     */
    private String industryId;

    /**
     * 地域类型，0地区，1省
     */
    private Short areaType;

    /**
     * 是否删除，0正常，1已删除
     */
    private Short deleteFlag;

    /**
     * 推送至行业名称，多个之间中文逗号分隔
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.id
     *
     * @return the value of trade_niche_push.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.id
     *
     * @param id the value for trade_niche_push.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.push_time
     *
     * @return the value of trade_niche_push.push_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getPushTime() {
        return pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.push_time
     *
     * @param pushTime the value for trade_niche_push.push_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushTime(Date pushTime) {
        this.pushTime = pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.push_status
     *
     * @return the value of trade_niche_push.push_status
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.push_status
     *
     * @param pushStatus the value for trade_niche_push.push_status
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushStatus(Short pushStatus) {
        this.pushStatus = pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.withdraw_time
     *
     * @return the value of trade_niche_push.withdraw_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getWithdrawTime() {
        return withdrawTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.withdraw_time
     *
     * @param withdrawTime the value for trade_niche_push.withdraw_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setWithdrawTime(Date withdrawTime) {
        this.withdrawTime = withdrawTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.withdraw_user_id
     *
     * @return the value of trade_niche_push.withdraw_user_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getWithdrawUserId() {
        return withdrawUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.withdraw_user_id
     *
     * @param withdrawUserId the value for trade_niche_push.withdraw_user_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setWithdrawUserId(Long withdrawUserId) {
        this.withdrawUserId = withdrawUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.niche_type
     *
     * @return the value of trade_niche_push.niche_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getNicheType() {
        return nicheType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.niche_type
     *
     * @param nicheType the value for trade_niche_push.niche_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setNicheType(Short nicheType) {
        this.nicheType = nicheType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.niche_title
     *
     * @return the value of trade_niche_push.niche_title
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getNicheTitle() {
        return nicheTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.niche_title
     *
     * @param nicheTitle the value for trade_niche_push.niche_title
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setNicheTitle(String nicheTitle) {
        this.nicheTitle = nicheTitle == null ? null : nicheTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.niche_id
     *
     * @return the value of trade_niche_push.niche_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getNicheId() {
        return nicheId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.niche_id
     *
     * @param nicheId the value for trade_niche_push.niche_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setNicheId(Long nicheId) {
        this.nicheId = nicheId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.push_type
     *
     * @return the value of trade_niche_push.push_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.push_type
     *
     * @param pushType the value for trade_niche_push.push_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushType(Short pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.area_code
     *
     * @return the value of trade_niche_push.area_code
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.area_code
     *
     * @param areaCode the value for trade_niche_push.area_code
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.area_name
     *
     * @return the value of trade_niche_push.area_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.area_name
     *
     * @param areaName the value for trade_niche_push.area_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.user_mobile_no
     *
     * @return the value of trade_niche_push.user_mobile_no
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getUserMobileNo() {
        return userMobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.user_mobile_no
     *
     * @param userMobileNo the value for trade_niche_push.user_mobile_no
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUserMobileNo(String userMobileNo) {
        this.userMobileNo = userMobileNo == null ? null : userMobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.user_fullname
     *
     * @return the value of trade_niche_push.user_fullname
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getUserFullname() {
        return userFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.user_fullname
     *
     * @param userFullname the value for trade_niche_push.user_fullname
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUserFullname(String userFullname) {
        this.userFullname = userFullname == null ? null : userFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.push_conmapy_count
     *
     * @return the value of trade_niche_push.push_conmapy_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Integer getPushConmapyCount() {
        return pushConmapyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.push_conmapy_count
     *
     * @param pushConmapyCount the value for trade_niche_push.push_conmapy_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushConmapyCount(Integer pushConmapyCount) {
        this.pushConmapyCount = pushConmapyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.create_id
     *
     * @return the value of trade_niche_push.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.create_id
     *
     * @param createId the value for trade_niche_push.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.create_time
     *
     * @return the value of trade_niche_push.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.create_time
     *
     * @param createTime the value for trade_niche_push.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.update_id
     *
     * @return the value of trade_niche_push.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.update_id
     *
     * @param updateId the value for trade_niche_push.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.update_time
     *
     * @return the value of trade_niche_push.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.update_time
     *
     * @param updateTime the value for trade_niche_push.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.seq
     *
     * @return the value of trade_niche_push.seq
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.seq
     *
     * @param seq the value for trade_niche_push.seq
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.industry_id
     *
     * @return the value of trade_niche_push.industry_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.industry_id
     *
     * @param industryId the value for trade_niche_push.industry_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setIndustryId(String industryId) {
        this.industryId = industryId == null ? null : industryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.area_type
     *
     * @return the value of trade_niche_push.area_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.area_type
     *
     * @param areaType the value for trade_niche_push.area_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setAreaType(Short areaType) {
        this.areaType = areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.delete_flag
     *
     * @return the value of trade_niche_push.delete_flag
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.delete_flag
     *
     * @param deleteFlag the value for trade_niche_push.delete_flag
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_niche_push.industry_name
     *
     * @return the value of trade_niche_push.industry_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_niche_push.industry_name
     *
     * @param industryName the value for trade_niche_push.industry_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NichePushReq other = (NichePushReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPushTime() == null ? other.getPushTime() == null : this.getPushTime().equals(other.getPushTime()))
            && (this.getPushStatus() == null ? other.getPushStatus() == null : this.getPushStatus().equals(other.getPushStatus()))
            && (this.getWithdrawTime() == null ? other.getWithdrawTime() == null : this.getWithdrawTime().equals(other.getWithdrawTime()))
            && (this.getWithdrawUserId() == null ? other.getWithdrawUserId() == null : this.getWithdrawUserId().equals(other.getWithdrawUserId()))
            && (this.getNicheType() == null ? other.getNicheType() == null : this.getNicheType().equals(other.getNicheType()))
            && (this.getNicheTitle() == null ? other.getNicheTitle() == null : this.getNicheTitle().equals(other.getNicheTitle()))
            && (this.getNicheId() == null ? other.getNicheId() == null : this.getNicheId().equals(other.getNicheId()))
            && (this.getPushType() == null ? other.getPushType() == null : this.getPushType().equals(other.getPushType()))
            && (this.getAreaCode() == null ? other.getAreaCode() == null : this.getAreaCode().equals(other.getAreaCode()))
            && (this.getAreaName() == null ? other.getAreaName() == null : this.getAreaName().equals(other.getAreaName()))
            && (this.getUserMobileNo() == null ? other.getUserMobileNo() == null : this.getUserMobileNo().equals(other.getUserMobileNo()))
            && (this.getUserFullname() == null ? other.getUserFullname() == null : this.getUserFullname().equals(other.getUserFullname()))
            && (this.getPushConmapyCount() == null ? other.getPushConmapyCount() == null : this.getPushConmapyCount().equals(other.getPushConmapyCount()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getSeq() == null ? other.getSeq() == null : this.getSeq().equals(other.getSeq()))
            && (this.getIndustryId() == null ? other.getIndustryId() == null : this.getIndustryId().equals(other.getIndustryId()))
            && (this.getAreaType() == null ? other.getAreaType() == null : this.getAreaType().equals(other.getAreaType()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getIndustryName() == null ? other.getIndustryName() == null : this.getIndustryName().equals(other.getIndustryName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPushTime() == null) ? 0 : getPushTime().hashCode());
        result = prime * result + ((getPushStatus() == null) ? 0 : getPushStatus().hashCode());
        result = prime * result + ((getWithdrawTime() == null) ? 0 : getWithdrawTime().hashCode());
        result = prime * result + ((getWithdrawUserId() == null) ? 0 : getWithdrawUserId().hashCode());
        result = prime * result + ((getNicheType() == null) ? 0 : getNicheType().hashCode());
        result = prime * result + ((getNicheTitle() == null) ? 0 : getNicheTitle().hashCode());
        result = prime * result + ((getNicheId() == null) ? 0 : getNicheId().hashCode());
        result = prime * result + ((getPushType() == null) ? 0 : getPushType().hashCode());
        result = prime * result + ((getAreaCode() == null) ? 0 : getAreaCode().hashCode());
        result = prime * result + ((getAreaName() == null) ? 0 : getAreaName().hashCode());
        result = prime * result + ((getUserMobileNo() == null) ? 0 : getUserMobileNo().hashCode());
        result = prime * result + ((getUserFullname() == null) ? 0 : getUserFullname().hashCode());
        result = prime * result + ((getPushConmapyCount() == null) ? 0 : getPushConmapyCount().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
        result = prime * result + ((getIndustryId() == null) ? 0 : getIndustryId().hashCode());
        result = prime * result + ((getAreaType() == null) ? 0 : getAreaType().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getIndustryName() == null) ? 0 : getIndustryName().hashCode());
        return result;
    }
}