/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * PpGradeMaterailReq.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-18 Created
 */
package java.request;

import java.io.Serializable;
import java.util.Date;

public class PpGradeMaterailReq implements Serializable {
    private Long id;

    private Long compId;

    private Long projId;

    private String material;

    private String ppClass;

    private String jsizeMin;

    /**
     * @ 来源抽检比例表 中的代号
     */
    private String jsizeMax;

    private String wallThickCode;

    /**
     * @ CS SS PE
     */
    private String materialType;

    /**
     * @ 常量
     */
    private String materialCategory;

    private Date createTime;

    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.ID
     *
     * @return the value of pp_grade_materail.ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.ID
     *
     * @param id the value for pp_grade_materail.ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.COMP_ID
     *
     * @return the value of pp_grade_materail.COMP_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.COMP_ID
     *
     * @param compId the value for pp_grade_materail.COMP_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.PROJ_ID
     *
     * @return the value of pp_grade_materail.PROJ_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.PROJ_ID
     *
     * @param projId the value for pp_grade_materail.PROJ_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setProjId(Long projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.MATERIAL
     *
     * @return the value of pp_grade_materail.MATERIAL
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.MATERIAL
     *
     * @param material the value for pp_grade_materail.MATERIAL
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.PP_CLASS
     *
     * @return the value of pp_grade_materail.PP_CLASS
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getPpClass() {
        return ppClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.PP_CLASS
     *
     * @param ppClass the value for pp_grade_materail.PP_CLASS
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setPpClass(String ppClass) {
        this.ppClass = ppClass == null ? null : ppClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.JSIZE_MIN
     *
     * @return the value of pp_grade_materail.JSIZE_MIN
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getJsizeMin() {
        return jsizeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.JSIZE_MIN
     *
     * @param jsizeMin the value for pp_grade_materail.JSIZE_MIN
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setJsizeMin(String jsizeMin) {
        this.jsizeMin = jsizeMin == null ? null : jsizeMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.JSIZE_MAX
     *
     * @return the value of pp_grade_materail.JSIZE_MAX
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getJsizeMax() {
        return jsizeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.JSIZE_MAX
     *
     * @param jsizeMax the value for pp_grade_materail.JSIZE_MAX
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setJsizeMax(String jsizeMax) {
        this.jsizeMax = jsizeMax == null ? null : jsizeMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.WALL_THICK_CODE
     *
     * @return the value of pp_grade_materail.WALL_THICK_CODE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getWallThickCode() {
        return wallThickCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.WALL_THICK_CODE
     *
     * @param wallThickCode the value for pp_grade_materail.WALL_THICK_CODE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setWallThickCode(String wallThickCode) {
        this.wallThickCode = wallThickCode == null ? null : wallThickCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.MATERIAL_TYPE
     *
     * @return the value of pp_grade_materail.MATERIAL_TYPE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getMaterialType() {
        return materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.MATERIAL_TYPE
     *
     * @param materialType the value for pp_grade_materail.MATERIAL_TYPE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setMaterialType(String materialType) {
        this.materialType = materialType == null ? null : materialType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.MATERIAL_CATEGORY
     *
     * @return the value of pp_grade_materail.MATERIAL_CATEGORY
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getMaterialCategory() {
        return materialCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.MATERIAL_CATEGORY
     *
     * @param materialCategory the value for pp_grade_materail.MATERIAL_CATEGORY
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setMaterialCategory(String materialCategory) {
        this.materialCategory = materialCategory == null ? null : materialCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.CREATE_TIME
     *
     * @return the value of pp_grade_materail.CREATE_TIME
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.CREATE_TIME
     *
     * @param createTime the value for pp_grade_materail.CREATE_TIME
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_grade_materail.DEL_FLAG
     *
     * @return the value of pp_grade_materail.DEL_FLAG
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_grade_materail.DEL_FLAG
     *
     * @param delFlag the value for pp_grade_materail.DEL_FLAG
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PpGradeMaterailReq other = (PpGradeMaterailReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompId() == null ? other.getCompId() == null : this.getCompId().equals(other.getCompId()))
            && (this.getProjId() == null ? other.getProjId() == null : this.getProjId().equals(other.getProjId()))
            && (this.getMaterial() == null ? other.getMaterial() == null : this.getMaterial().equals(other.getMaterial()))
            && (this.getPpClass() == null ? other.getPpClass() == null : this.getPpClass().equals(other.getPpClass()))
            && (this.getJsizeMin() == null ? other.getJsizeMin() == null : this.getJsizeMin().equals(other.getJsizeMin()))
            && (this.getJsizeMax() == null ? other.getJsizeMax() == null : this.getJsizeMax().equals(other.getJsizeMax()))
            && (this.getWallThickCode() == null ? other.getWallThickCode() == null : this.getWallThickCode().equals(other.getWallThickCode()))
            && (this.getMaterialType() == null ? other.getMaterialType() == null : this.getMaterialType().equals(other.getMaterialType()))
            && (this.getMaterialCategory() == null ? other.getMaterialCategory() == null : this.getMaterialCategory().equals(other.getMaterialCategory()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompId() == null) ? 0 : getCompId().hashCode());
        result = prime * result + ((getProjId() == null) ? 0 : getProjId().hashCode());
        result = prime * result + ((getMaterial() == null) ? 0 : getMaterial().hashCode());
        result = prime * result + ((getPpClass() == null) ? 0 : getPpClass().hashCode());
        result = prime * result + ((getJsizeMin() == null) ? 0 : getJsizeMin().hashCode());
        result = prime * result + ((getJsizeMax() == null) ? 0 : getJsizeMax().hashCode());
        result = prime * result + ((getWallThickCode() == null) ? 0 : getWallThickCode().hashCode());
        result = prime * result + ((getMaterialType() == null) ? 0 : getMaterialType().hashCode());
        result = prime * result + ((getMaterialCategory() == null) ? 0 : getMaterialCategory().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }
}