/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * PpLineWeldEntrustReq.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-18 Created
 */
package java.request;

import java.io.Serializable;
import java.util.Date;

public class PpLineWeldEntrustReq implements Serializable {
    private Long id;

    private Long projId;

    private Long pipelineId;

    private Long weldId;

    private String flowNum;

    /**
     * @分项号-委托类型-流水号
     */
    private String code;

    private Integer expandCount;

    private Integer repareCount;

    /**
     * @RT PT UT MT PMI
     */
    private String entrustType;

    private Date entrustDate;

    private String remark;

    private Date createTime;

    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld_entrust
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.ID
     *
     * @return the value of pp_line_weld_entrust.ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.ID
     *
     * @param id the value for pp_line_weld_entrust.ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.PROJ_ID
     *
     * @return the value of pp_line_weld_entrust.PROJ_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.PROJ_ID
     *
     * @param projId the value for pp_line_weld_entrust.PROJ_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setProjId(Long projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.PIPELINE_ID
     *
     * @return the value of pp_line_weld_entrust.PIPELINE_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getPipelineId() {
        return pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.PIPELINE_ID
     *
     * @param pipelineId the value for pp_line_weld_entrust.PIPELINE_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setPipelineId(Long pipelineId) {
        this.pipelineId = pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.WELD_ID
     *
     * @return the value of pp_line_weld_entrust.WELD_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getWeldId() {
        return weldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.WELD_ID
     *
     * @param weldId the value for pp_line_weld_entrust.WELD_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setWeldId(Long weldId) {
        this.weldId = weldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.FLOW_NUM
     *
     * @return the value of pp_line_weld_entrust.FLOW_NUM
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getFlowNum() {
        return flowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.FLOW_NUM
     *
     * @param flowNum the value for pp_line_weld_entrust.FLOW_NUM
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setFlowNum(String flowNum) {
        this.flowNum = flowNum == null ? null : flowNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.CODE
     *
     * @return the value of pp_line_weld_entrust.CODE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.CODE
     *
     * @param code the value for pp_line_weld_entrust.CODE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.EXPAND_COUNT
     *
     * @return the value of pp_line_weld_entrust.EXPAND_COUNT
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Integer getExpandCount() {
        return expandCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.EXPAND_COUNT
     *
     * @param expandCount the value for pp_line_weld_entrust.EXPAND_COUNT
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setExpandCount(Integer expandCount) {
        this.expandCount = expandCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.REPARE_COUNT
     *
     * @return the value of pp_line_weld_entrust.REPARE_COUNT
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Integer getRepareCount() {
        return repareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.REPARE_COUNT
     *
     * @param repareCount the value for pp_line_weld_entrust.REPARE_COUNT
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setRepareCount(Integer repareCount) {
        this.repareCount = repareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.ENTRUST_TYPE
     *
     * @return the value of pp_line_weld_entrust.ENTRUST_TYPE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getEntrustType() {
        return entrustType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.ENTRUST_TYPE
     *
     * @param entrustType the value for pp_line_weld_entrust.ENTRUST_TYPE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setEntrustType(String entrustType) {
        this.entrustType = entrustType == null ? null : entrustType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.ENTRUST_DATE
     *
     * @return the value of pp_line_weld_entrust.ENTRUST_DATE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Date getEntrustDate() {
        return entrustDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.ENTRUST_DATE
     *
     * @param entrustDate the value for pp_line_weld_entrust.ENTRUST_DATE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setEntrustDate(Date entrustDate) {
        this.entrustDate = entrustDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.REMARK
     *
     * @return the value of pp_line_weld_entrust.REMARK
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.REMARK
     *
     * @param remark the value for pp_line_weld_entrust.REMARK
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.CREATE_TIME
     *
     * @return the value of pp_line_weld_entrust.CREATE_TIME
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.CREATE_TIME
     *
     * @param createTime the value for pp_line_weld_entrust.CREATE_TIME
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_entrust.DEL_FLAG
     *
     * @return the value of pp_line_weld_entrust.DEL_FLAG
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_entrust.DEL_FLAG
     *
     * @param delFlag the value for pp_line_weld_entrust.DEL_FLAG
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_entrust
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PpLineWeldEntrustReq other = (PpLineWeldEntrustReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProjId() == null ? other.getProjId() == null : this.getProjId().equals(other.getProjId()))
            && (this.getPipelineId() == null ? other.getPipelineId() == null : this.getPipelineId().equals(other.getPipelineId()))
            && (this.getWeldId() == null ? other.getWeldId() == null : this.getWeldId().equals(other.getWeldId()))
            && (this.getFlowNum() == null ? other.getFlowNum() == null : this.getFlowNum().equals(other.getFlowNum()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getExpandCount() == null ? other.getExpandCount() == null : this.getExpandCount().equals(other.getExpandCount()))
            && (this.getRepareCount() == null ? other.getRepareCount() == null : this.getRepareCount().equals(other.getRepareCount()))
            && (this.getEntrustType() == null ? other.getEntrustType() == null : this.getEntrustType().equals(other.getEntrustType()))
            && (this.getEntrustDate() == null ? other.getEntrustDate() == null : this.getEntrustDate().equals(other.getEntrustDate()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_entrust
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjId() == null) ? 0 : getProjId().hashCode());
        result = prime * result + ((getPipelineId() == null) ? 0 : getPipelineId().hashCode());
        result = prime * result + ((getWeldId() == null) ? 0 : getWeldId().hashCode());
        result = prime * result + ((getFlowNum() == null) ? 0 : getFlowNum().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getExpandCount() == null) ? 0 : getExpandCount().hashCode());
        result = prime * result + ((getRepareCount() == null) ? 0 : getRepareCount().hashCode());
        result = prime * result + ((getEntrustType() == null) ? 0 : getEntrustType().hashCode());
        result = prime * result + ((getEntrustDate() == null) ? 0 : getEntrustDate().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }
}