/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * VipCouponDetailReq.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-28 Created
 */
package java.request;

import java.io.Serializable;
import java.util.Date;

public class VipCouponDetailReq implements Serializable {
    private Long id;

    /**
     * 优惠码批次名称，读取trade_vip_coupon.coupon_name
     */
    private String couponName;

    /**
     * 优惠码
     */
    private String couponCode;

    /**
     * 优惠码批次ID，关联trade_vip_coupon.id
     */
    private Long couponId;

    /**
     * 公司ID，关联trade_company.comp_id
     */
    private Long companyId;

    /**
     * 是否已使用，0否，1是
     */
    private Short isUsed;

    /**
     * 使用时间
     */
    private Date useTime;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改人
     */
    private Long updateId;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_vip_coupon_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.id
     *
     * @return the value of trade_vip_coupon_detail.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.id
     *
     * @param id the value for trade_vip_coupon_detail.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.coupon_name
     *
     * @return the value of trade_vip_coupon_detail.coupon_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.coupon_name
     *
     * @param couponName the value for trade_vip_coupon_detail.coupon_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.coupon_code
     *
     * @return the value of trade_vip_coupon_detail.coupon_code
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.coupon_code
     *
     * @param couponCode the value for trade_vip_coupon_detail.coupon_code
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode == null ? null : couponCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.coupon_id
     *
     * @return the value of trade_vip_coupon_detail.coupon_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.coupon_id
     *
     * @param couponId the value for trade_vip_coupon_detail.coupon_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.company_id
     *
     * @return the value of trade_vip_coupon_detail.company_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.company_id
     *
     * @param companyId the value for trade_vip_coupon_detail.company_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.is_used
     *
     * @return the value of trade_vip_coupon_detail.is_used
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.is_used
     *
     * @param isUsed the value for trade_vip_coupon_detail.is_used
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setIsUsed(Short isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.use_time
     *
     * @return the value of trade_vip_coupon_detail.use_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.use_time
     *
     * @param useTime the value for trade_vip_coupon_detail.use_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.create_id
     *
     * @return the value of trade_vip_coupon_detail.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.create_id
     *
     * @param createId the value for trade_vip_coupon_detail.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.create_time
     *
     * @return the value of trade_vip_coupon_detail.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.create_time
     *
     * @param createTime the value for trade_vip_coupon_detail.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.update_id
     *
     * @return the value of trade_vip_coupon_detail.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.update_id
     *
     * @param updateId the value for trade_vip_coupon_detail.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon_detail.update_time
     *
     * @return the value of trade_vip_coupon_detail.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon_detail.update_time
     *
     * @param updateTime the value for trade_vip_coupon_detail.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_vip_coupon_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VipCouponDetailReq other = (VipCouponDetailReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCouponName() == null ? other.getCouponName() == null : this.getCouponName().equals(other.getCouponName()))
            && (this.getCouponCode() == null ? other.getCouponCode() == null : this.getCouponCode().equals(other.getCouponCode()))
            && (this.getCouponId() == null ? other.getCouponId() == null : this.getCouponId().equals(other.getCouponId()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getIsUsed() == null ? other.getIsUsed() == null : this.getIsUsed().equals(other.getIsUsed()))
            && (this.getUseTime() == null ? other.getUseTime() == null : this.getUseTime().equals(other.getUseTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_vip_coupon_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCouponName() == null) ? 0 : getCouponName().hashCode());
        result = prime * result + ((getCouponCode() == null) ? 0 : getCouponCode().hashCode());
        result = prime * result + ((getCouponId() == null) ? 0 : getCouponId().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getIsUsed() == null) ? 0 : getIsUsed().hashCode());
        result = prime * result + ((getUseTime() == null) ? 0 : getUseTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}