/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * BusInfoReq.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-28 Created
 */
package java.request.trade_dev_dev;

import java.io.Serializable;
import java.util.Date;

public class BusInfoReq implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 聚贸资讯的ID
     */
    private Long foreignId;

    /**
     * 封面图片，最多三张，用,分割
     */
    private String indexImg;

    /**
     * 文章标题
     */
    private String articleTitle;

    /**
     * 简介
     */
    private String introduce;

    /**
     * 关键字，多个关键词，用,好分割开
     */
    private String articleLabel;

    /**
     * 到期时间
     */
    private Date effectiveTime;

    /**
     * 商讯类型
     */
    private String industryName;

    /**
     * 语言编码
     */
    private String languageCode;

    /**
     * 是否删除，0正常，1已删除
     */
    private Short deleteFlag;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改人
     */
    private Long updateId;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 推送状态，0未推送，1已推送
     */
    private Short isPush;

    /**
     * 推送时间，每次推送更新
     */
    private Date pushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_dev_dev..trade_bus_info
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.id
     *
     * @return the value of trade_dev_dev..trade_bus_info.id
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.id
     *
     * @param id the value for trade_dev_dev..trade_bus_info.id
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.foreign_id
     *
     * @return the value of trade_dev_dev..trade_bus_info.foreign_id
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Long getForeignId() {
        return foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.foreign_id
     *
     * @param foreignId the value for trade_dev_dev..trade_bus_info.foreign_id
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setForeignId(Long foreignId) {
        this.foreignId = foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.index_img
     *
     * @return the value of trade_dev_dev..trade_bus_info.index_img
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public String getIndexImg() {
        return indexImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.index_img
     *
     * @param indexImg the value for trade_dev_dev..trade_bus_info.index_img
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setIndexImg(String indexImg) {
        this.indexImg = indexImg == null ? null : indexImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.article_title
     *
     * @return the value of trade_dev_dev..trade_bus_info.article_title
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.article_title
     *
     * @param articleTitle the value for trade_dev_dev..trade_bus_info.article_title
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.introduce
     *
     * @return the value of trade_dev_dev..trade_bus_info.introduce
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.introduce
     *
     * @param introduce the value for trade_dev_dev..trade_bus_info.introduce
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.article_label
     *
     * @return the value of trade_dev_dev..trade_bus_info.article_label
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public String getArticleLabel() {
        return articleLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.article_label
     *
     * @param articleLabel the value for trade_dev_dev..trade_bus_info.article_label
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setArticleLabel(String articleLabel) {
        this.articleLabel = articleLabel == null ? null : articleLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.effective_time
     *
     * @return the value of trade_dev_dev..trade_bus_info.effective_time
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.effective_time
     *
     * @param effectiveTime the value for trade_dev_dev..trade_bus_info.effective_time
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.industry_name
     *
     * @return the value of trade_dev_dev..trade_bus_info.industry_name
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.industry_name
     *
     * @param industryName the value for trade_dev_dev..trade_bus_info.industry_name
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.language_code
     *
     * @return the value of trade_dev_dev..trade_bus_info.language_code
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.language_code
     *
     * @param languageCode the value for trade_dev_dev..trade_bus_info.language_code
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode == null ? null : languageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.delete_flag
     *
     * @return the value of trade_dev_dev..trade_bus_info.delete_flag
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.delete_flag
     *
     * @param deleteFlag the value for trade_dev_dev..trade_bus_info.delete_flag
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.create_id
     *
     * @return the value of trade_dev_dev..trade_bus_info.create_id
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.create_id
     *
     * @param createId the value for trade_dev_dev..trade_bus_info.create_id
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.create_time
     *
     * @return the value of trade_dev_dev..trade_bus_info.create_time
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.create_time
     *
     * @param createTime the value for trade_dev_dev..trade_bus_info.create_time
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.update_id
     *
     * @return the value of trade_dev_dev..trade_bus_info.update_id
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.update_id
     *
     * @param updateId the value for trade_dev_dev..trade_bus_info.update_id
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.update_time
     *
     * @return the value of trade_dev_dev..trade_bus_info.update_time
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.update_time
     *
     * @param updateTime the value for trade_dev_dev..trade_bus_info.update_time
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.is_push
     *
     * @return the value of trade_dev_dev..trade_bus_info.is_push
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Short getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.is_push
     *
     * @param isPush the value for trade_dev_dev..trade_bus_info.is_push
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setIsPush(Short isPush) {
        this.isPush = isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_bus_info.push_time
     *
     * @return the value of trade_dev_dev..trade_bus_info.push_time
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public Date getPushTime() {
        return pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_bus_info.push_time
     *
     * @param pushTime the value for trade_dev_dev..trade_bus_info.push_time
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    public void setPushTime(Date pushTime) {
        this.pushTime = pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_dev_dev..trade_bus_info
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BusInfoReq other = (BusInfoReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getForeignId() == null ? other.getForeignId() == null : this.getForeignId().equals(other.getForeignId()))
            && (this.getIndexImg() == null ? other.getIndexImg() == null : this.getIndexImg().equals(other.getIndexImg()))
            && (this.getArticleTitle() == null ? other.getArticleTitle() == null : this.getArticleTitle().equals(other.getArticleTitle()))
            && (this.getIntroduce() == null ? other.getIntroduce() == null : this.getIntroduce().equals(other.getIntroduce()))
            && (this.getArticleLabel() == null ? other.getArticleLabel() == null : this.getArticleLabel().equals(other.getArticleLabel()))
            && (this.getEffectiveTime() == null ? other.getEffectiveTime() == null : this.getEffectiveTime().equals(other.getEffectiveTime()))
            && (this.getIndustryName() == null ? other.getIndustryName() == null : this.getIndustryName().equals(other.getIndustryName()))
            && (this.getLanguageCode() == null ? other.getLanguageCode() == null : this.getLanguageCode().equals(other.getLanguageCode()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsPush() == null ? other.getIsPush() == null : this.getIsPush().equals(other.getIsPush()))
            && (this.getPushTime() == null ? other.getPushTime() == null : this.getPushTime().equals(other.getPushTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_dev_dev..trade_bus_info
     *
     * @mbggenerated Mon Aug 28 11:49:01 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getForeignId() == null) ? 0 : getForeignId().hashCode());
        result = prime * result + ((getIndexImg() == null) ? 0 : getIndexImg().hashCode());
        result = prime * result + ((getArticleTitle() == null) ? 0 : getArticleTitle().hashCode());
        result = prime * result + ((getIntroduce() == null) ? 0 : getIntroduce().hashCode());
        result = prime * result + ((getArticleLabel() == null) ? 0 : getArticleLabel().hashCode());
        result = prime * result + ((getEffectiveTime() == null) ? 0 : getEffectiveTime().hashCode());
        result = prime * result + ((getIndustryName() == null) ? 0 : getIndustryName().hashCode());
        result = prime * result + ((getLanguageCode() == null) ? 0 : getLanguageCode().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsPush() == null) ? 0 : getIsPush().hashCode());
        result = prime * result + ((getPushTime() == null) ? 0 : getPushTime().hashCode());
        return result;
    }
}