package java.trade_dev_dev;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 会员支付表
 * 
 * @author 菠萝大象
 * @version 1.0 2017-08-28
 */
public class VipPay implements Serializable {
    private Long id;

    /**
     * 会员支付订单号
     */
    private String payOrderNo;

    /**
     * 公司ID，关联trade_company.comp_id
     */
    private Long companyId;

    /**
     * 公司名称
     */
    private String companyName;

    /**
     * 支付金额
     */
    private BigDecimal amount;

    /**
     * 原金额
     */
    private BigDecimal originalAmount;

    /**
     * 优化金额
     */
    private BigDecimal preferentialAmount;

    /**
     * 优惠码
     */
    private String couponCode;

    /**
     * 支付类型 0:线上支付 1:线下支付 2:后台新增
     */
    private Short payType;

    /**
     * 支付时间
     */
    private Date payTime;

    /**
     * 支付人员ID，关联trade_user_center.user_id
     */
    private Long payUserId;

    /**
     * 支付人员姓名
     */
    private String payUserFullname;

    /**
     * 支付备注
     */
    private String remark;

    /**
     * 支付状态，0支付中，1支付成功，2支付已关闭
     */
    private Short payStatus;

    /**
     * 是否最新支付记录，0否，1是
     */
    private Short isCurrent;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改人
     */
    private Long updateId;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_dev_dev..trade_vip_pay
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.id
     *
     * @return the value of trade_dev_dev..trade_vip_pay.id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.id
     *
     * @param id the value for trade_dev_dev..trade_vip_pay.id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.pay_order_no
     *
     * @return the value of trade_dev_dev..trade_vip_pay.pay_order_no
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public String getPayOrderNo() {
        return payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.pay_order_no
     *
     * @param payOrderNo the value for trade_dev_dev..trade_vip_pay.pay_order_no
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setPayOrderNo(String payOrderNo) {
        this.payOrderNo = payOrderNo == null ? null : payOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.company_id
     *
     * @return the value of trade_dev_dev..trade_vip_pay.company_id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.company_id
     *
     * @param companyId the value for trade_dev_dev..trade_vip_pay.company_id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.company_name
     *
     * @return the value of trade_dev_dev..trade_vip_pay.company_name
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.company_name
     *
     * @param companyName the value for trade_dev_dev..trade_vip_pay.company_name
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.amount
     *
     * @return the value of trade_dev_dev..trade_vip_pay.amount
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.amount
     *
     * @param amount the value for trade_dev_dev..trade_vip_pay.amount
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.original_amount
     *
     * @return the value of trade_dev_dev..trade_vip_pay.original_amount
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public BigDecimal getOriginalAmount() {
        return originalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.original_amount
     *
     * @param originalAmount the value for trade_dev_dev..trade_vip_pay.original_amount
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setOriginalAmount(BigDecimal originalAmount) {
        this.originalAmount = originalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.preferential_amount
     *
     * @return the value of trade_dev_dev..trade_vip_pay.preferential_amount
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public BigDecimal getPreferentialAmount() {
        return preferentialAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.preferential_amount
     *
     * @param preferentialAmount the value for trade_dev_dev..trade_vip_pay.preferential_amount
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setPreferentialAmount(BigDecimal preferentialAmount) {
        this.preferentialAmount = preferentialAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.coupon_code
     *
     * @return the value of trade_dev_dev..trade_vip_pay.coupon_code
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.coupon_code
     *
     * @param couponCode the value for trade_dev_dev..trade_vip_pay.coupon_code
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode == null ? null : couponCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.pay_type
     *
     * @return the value of trade_dev_dev..trade_vip_pay.pay_type
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.pay_type
     *
     * @param payType the value for trade_dev_dev..trade_vip_pay.pay_type
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.pay_time
     *
     * @return the value of trade_dev_dev..trade_vip_pay.pay_time
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.pay_time
     *
     * @param payTime the value for trade_dev_dev..trade_vip_pay.pay_time
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.pay_user_id
     *
     * @return the value of trade_dev_dev..trade_vip_pay.pay_user_id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Long getPayUserId() {
        return payUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.pay_user_id
     *
     * @param payUserId the value for trade_dev_dev..trade_vip_pay.pay_user_id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setPayUserId(Long payUserId) {
        this.payUserId = payUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.pay_user_fullname
     *
     * @return the value of trade_dev_dev..trade_vip_pay.pay_user_fullname
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public String getPayUserFullname() {
        return payUserFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.pay_user_fullname
     *
     * @param payUserFullname the value for trade_dev_dev..trade_vip_pay.pay_user_fullname
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setPayUserFullname(String payUserFullname) {
        this.payUserFullname = payUserFullname == null ? null : payUserFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.remark
     *
     * @return the value of trade_dev_dev..trade_vip_pay.remark
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.remark
     *
     * @param remark the value for trade_dev_dev..trade_vip_pay.remark
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.pay_status
     *
     * @return the value of trade_dev_dev..trade_vip_pay.pay_status
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Short getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.pay_status
     *
     * @param payStatus the value for trade_dev_dev..trade_vip_pay.pay_status
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setPayStatus(Short payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.is_current
     *
     * @return the value of trade_dev_dev..trade_vip_pay.is_current
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Short getIsCurrent() {
        return isCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.is_current
     *
     * @param isCurrent the value for trade_dev_dev..trade_vip_pay.is_current
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setIsCurrent(Short isCurrent) {
        this.isCurrent = isCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.create_id
     *
     * @return the value of trade_dev_dev..trade_vip_pay.create_id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.create_id
     *
     * @param createId the value for trade_dev_dev..trade_vip_pay.create_id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.create_time
     *
     * @return the value of trade_dev_dev..trade_vip_pay.create_time
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.create_time
     *
     * @param createTime the value for trade_dev_dev..trade_vip_pay.create_time
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.update_id
     *
     * @return the value of trade_dev_dev..trade_vip_pay.update_id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.update_id
     *
     * @param updateId the value for trade_dev_dev..trade_vip_pay.update_id
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_dev_dev..trade_vip_pay.update_time
     *
     * @return the value of trade_dev_dev..trade_vip_pay.update_time
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_dev_dev..trade_vip_pay.update_time
     *
     * @param updateTime the value for trade_dev_dev..trade_vip_pay.update_time
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_dev_dev..trade_vip_pay
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VipPay other = (VipPay) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayOrderNo() == null ? other.getPayOrderNo() == null : this.getPayOrderNo().equals(other.getPayOrderNo()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getOriginalAmount() == null ? other.getOriginalAmount() == null : this.getOriginalAmount().equals(other.getOriginalAmount()))
            && (this.getPreferentialAmount() == null ? other.getPreferentialAmount() == null : this.getPreferentialAmount().equals(other.getPreferentialAmount()))
            && (this.getCouponCode() == null ? other.getCouponCode() == null : this.getCouponCode().equals(other.getCouponCode()))
            && (this.getPayType() == null ? other.getPayType() == null : this.getPayType().equals(other.getPayType()))
            && (this.getPayTime() == null ? other.getPayTime() == null : this.getPayTime().equals(other.getPayTime()))
            && (this.getPayUserId() == null ? other.getPayUserId() == null : this.getPayUserId().equals(other.getPayUserId()))
            && (this.getPayUserFullname() == null ? other.getPayUserFullname() == null : this.getPayUserFullname().equals(other.getPayUserFullname()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getPayStatus() == null ? other.getPayStatus() == null : this.getPayStatus().equals(other.getPayStatus()))
            && (this.getIsCurrent() == null ? other.getIsCurrent() == null : this.getIsCurrent().equals(other.getIsCurrent()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_dev_dev..trade_vip_pay
     *
     * @mbggenerated Mon Aug 28 11:47:45 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayOrderNo() == null) ? 0 : getPayOrderNo().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getOriginalAmount() == null) ? 0 : getOriginalAmount().hashCode());
        result = prime * result + ((getPreferentialAmount() == null) ? 0 : getPreferentialAmount().hashCode());
        result = prime * result + ((getCouponCode() == null) ? 0 : getCouponCode().hashCode());
        result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
        result = prime * result + ((getPayTime() == null) ? 0 : getPayTime().hashCode());
        result = prime * result + ((getPayUserId() == null) ? 0 : getPayUserId().hashCode());
        result = prime * result + ((getPayUserFullname() == null) ? 0 : getPayUserFullname().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getPayStatus() == null) ? 0 : getPayStatus().hashCode());
        result = prime * result + ((getIsCurrent() == null) ? 0 : getIsCurrent().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}