package java;

import java.io.Serializable;
import java.util.Date;

/**
 * 代理采购
 * 
 * @author 菠萝大象
 * @version 1.0 2017-08-28
 */
public class AgentPurchase implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 采购标题
     */
    private String title;

    /**
     * 采购数量
     */
    private String purchaseCount;

    /**
     * 采购描述
     */
    private String remark;

    /**
     * 企业名称
     */
    private String companyName;

    /**
     * 联系人
     */
    private String contacts;

    /**
     * 联系电话
     */
    private String contactNumber;

    /**
     * 报价截止日期
     */
    private Date offerPeriod;

    /**
     * 行业id 对应trade_industry.industry_id
     */
    private Long industryId;

    /**
     * 推送状态，0未推送，1已推送
     */
    private Short isPush;

    /**
     * 语言编码
     */
    private String languageCode;

    /**
     * 是否删除
     */
    private Short deleteFlag;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改人
     */
    private Long updateId;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_agent_purchase
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.id
     *
     * @return the value of trade_agent_purchase.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.id
     *
     * @param id the value for trade_agent_purchase.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.title
     *
     * @return the value of trade_agent_purchase.title
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.title
     *
     * @param title the value for trade_agent_purchase.title
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.purchase_count
     *
     * @return the value of trade_agent_purchase.purchase_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getPurchaseCount() {
        return purchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.purchase_count
     *
     * @param purchaseCount the value for trade_agent_purchase.purchase_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPurchaseCount(String purchaseCount) {
        this.purchaseCount = purchaseCount == null ? null : purchaseCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.remark
     *
     * @return the value of trade_agent_purchase.remark
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.remark
     *
     * @param remark the value for trade_agent_purchase.remark
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.company_name
     *
     * @return the value of trade_agent_purchase.company_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.company_name
     *
     * @param companyName the value for trade_agent_purchase.company_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.contacts
     *
     * @return the value of trade_agent_purchase.contacts
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.contacts
     *
     * @param contacts the value for trade_agent_purchase.contacts
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.contact_number
     *
     * @return the value of trade_agent_purchase.contact_number
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.contact_number
     *
     * @param contactNumber the value for trade_agent_purchase.contact_number
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber == null ? null : contactNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.offer_period
     *
     * @return the value of trade_agent_purchase.offer_period
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getOfferPeriod() {
        return offerPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.offer_period
     *
     * @param offerPeriod the value for trade_agent_purchase.offer_period
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setOfferPeriod(Date offerPeriod) {
        this.offerPeriod = offerPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.industry_id
     *
     * @return the value of trade_agent_purchase.industry_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.industry_id
     *
     * @param industryId the value for trade_agent_purchase.industry_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setIndustryId(Long industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.is_push
     *
     * @return the value of trade_agent_purchase.is_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.is_push
     *
     * @param isPush the value for trade_agent_purchase.is_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setIsPush(Short isPush) {
        this.isPush = isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.language_code
     *
     * @return the value of trade_agent_purchase.language_code
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.language_code
     *
     * @param languageCode the value for trade_agent_purchase.language_code
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode == null ? null : languageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.delete_flag
     *
     * @return the value of trade_agent_purchase.delete_flag
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.delete_flag
     *
     * @param deleteFlag the value for trade_agent_purchase.delete_flag
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.create_id
     *
     * @return the value of trade_agent_purchase.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.create_id
     *
     * @param createId the value for trade_agent_purchase.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.create_time
     *
     * @return the value of trade_agent_purchase.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.create_time
     *
     * @param createTime the value for trade_agent_purchase.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.update_id
     *
     * @return the value of trade_agent_purchase.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.update_id
     *
     * @param updateId the value for trade_agent_purchase.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_agent_purchase.update_time
     *
     * @return the value of trade_agent_purchase.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_agent_purchase.update_time
     *
     * @param updateTime the value for trade_agent_purchase.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_agent_purchase
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AgentPurchase other = (AgentPurchase) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getPurchaseCount() == null ? other.getPurchaseCount() == null : this.getPurchaseCount().equals(other.getPurchaseCount()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getContacts() == null ? other.getContacts() == null : this.getContacts().equals(other.getContacts()))
            && (this.getContactNumber() == null ? other.getContactNumber() == null : this.getContactNumber().equals(other.getContactNumber()))
            && (this.getOfferPeriod() == null ? other.getOfferPeriod() == null : this.getOfferPeriod().equals(other.getOfferPeriod()))
            && (this.getIndustryId() == null ? other.getIndustryId() == null : this.getIndustryId().equals(other.getIndustryId()))
            && (this.getIsPush() == null ? other.getIsPush() == null : this.getIsPush().equals(other.getIsPush()))
            && (this.getLanguageCode() == null ? other.getLanguageCode() == null : this.getLanguageCode().equals(other.getLanguageCode()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_agent_purchase
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getPurchaseCount() == null) ? 0 : getPurchaseCount().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getContacts() == null) ? 0 : getContacts().hashCode());
        result = prime * result + ((getContactNumber() == null) ? 0 : getContactNumber().hashCode());
        result = prime * result + ((getOfferPeriod() == null) ? 0 : getOfferPeriod().hashCode());
        result = prime * result + ((getIndustryId() == null) ? 0 : getIndustryId().hashCode());
        result = prime * result + ((getIsPush() == null) ? 0 : getIsPush().hashCode());
        result = prime * result + ((getLanguageCode() == null) ? 0 : getLanguageCode().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}