package java;

import java.io.Serializable;
import java.util.Date;

/**
 * 数据权限设置
 * 
 * @author 菠萝大象
 * @version 1.0 2017-07-27
 */
public class BizAuth implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 业务类别
     */
    private String bizName;

    /**
     * 角色编码
     */
    private String roleCode;

    /**
     * 最小限码
     */
    private Long minAuthCode;

    /**
     * 最大权限权
     */
    private Long maxAuthCode;

    /**
     * 特殊权限码
     */
    private String authCode;

    /**
     * 权限类别@0:范围,1:特殊权限包含,1:特殊权限排除
     */
    private Short authCategory;

    /**
     * 创建人
     */
    private String createdBy;

    /**
     * 创建时间
     */
    private Date createdDate;

    /**
     * 修改人
     */
    private String lastModifiedBy;

    /**
     * 修改时间
     */
    private Date lastModifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jhi_biz_auth
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.ID
     *
     * @return the value of jhi_biz_auth.ID
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.ID
     *
     * @param id the value for jhi_biz_auth.ID
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.BIZ_NAME
     *
     * @return the value of jhi_biz_auth.BIZ_NAME
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.BIZ_NAME
     *
     * @param bizName the value for jhi_biz_auth.BIZ_NAME
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.ROLE_CODE
     *
     * @return the value of jhi_biz_auth.ROLE_CODE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.ROLE_CODE
     *
     * @param roleCode the value for jhi_biz_auth.ROLE_CODE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.MIN_AUTH_CODE
     *
     * @return the value of jhi_biz_auth.MIN_AUTH_CODE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public Long getMinAuthCode() {
        return minAuthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.MIN_AUTH_CODE
     *
     * @param minAuthCode the value for jhi_biz_auth.MIN_AUTH_CODE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setMinAuthCode(Long minAuthCode) {
        this.minAuthCode = minAuthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.MAX_AUTH_CODE
     *
     * @return the value of jhi_biz_auth.MAX_AUTH_CODE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public Long getMaxAuthCode() {
        return maxAuthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.MAX_AUTH_CODE
     *
     * @param maxAuthCode the value for jhi_biz_auth.MAX_AUTH_CODE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setMaxAuthCode(Long maxAuthCode) {
        this.maxAuthCode = maxAuthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.AUTH_CODE
     *
     * @return the value of jhi_biz_auth.AUTH_CODE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.AUTH_CODE
     *
     * @param authCode the value for jhi_biz_auth.AUTH_CODE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.AUTH_CATEGORY
     *
     * @return the value of jhi_biz_auth.AUTH_CATEGORY
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public Short getAuthCategory() {
        return authCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.AUTH_CATEGORY
     *
     * @param authCategory the value for jhi_biz_auth.AUTH_CATEGORY
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setAuthCategory(Short authCategory) {
        this.authCategory = authCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.CREATED_BY
     *
     * @return the value of jhi_biz_auth.CREATED_BY
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.CREATED_BY
     *
     * @param createdBy the value for jhi_biz_auth.CREATED_BY
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.CREATED_DATE
     *
     * @return the value of jhi_biz_auth.CREATED_DATE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.CREATED_DATE
     *
     * @param createdDate the value for jhi_biz_auth.CREATED_DATE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.LAST_MODIFIED_BY
     *
     * @return the value of jhi_biz_auth.LAST_MODIFIED_BY
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for jhi_biz_auth.LAST_MODIFIED_BY
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy == null ? null : lastModifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jhi_biz_auth.LAST_MODIFIED_DATE
     *
     * @return the value of jhi_biz_auth.LAST_MODIFIED_DATE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jhi_biz_auth.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for jhi_biz_auth.LAST_MODIFIED_DATE
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jhi_biz_auth
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BizAuth other = (BizAuth) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBizName() == null ? other.getBizName() == null : this.getBizName().equals(other.getBizName()))
            && (this.getRoleCode() == null ? other.getRoleCode() == null : this.getRoleCode().equals(other.getRoleCode()))
            && (this.getMinAuthCode() == null ? other.getMinAuthCode() == null : this.getMinAuthCode().equals(other.getMinAuthCode()))
            && (this.getMaxAuthCode() == null ? other.getMaxAuthCode() == null : this.getMaxAuthCode().equals(other.getMaxAuthCode()))
            && (this.getAuthCode() == null ? other.getAuthCode() == null : this.getAuthCode().equals(other.getAuthCode()))
            && (this.getAuthCategory() == null ? other.getAuthCategory() == null : this.getAuthCategory().equals(other.getAuthCategory()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getLastModifiedBy() == null ? other.getLastModifiedBy() == null : this.getLastModifiedBy().equals(other.getLastModifiedBy()))
            && (this.getLastModifiedDate() == null ? other.getLastModifiedDate() == null : this.getLastModifiedDate().equals(other.getLastModifiedDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jhi_biz_auth
     *
     * @mbggenerated Thu Jul 27 10:58:26 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBizName() == null) ? 0 : getBizName().hashCode());
        result = prime * result + ((getRoleCode() == null) ? 0 : getRoleCode().hashCode());
        result = prime * result + ((getMinAuthCode() == null) ? 0 : getMinAuthCode().hashCode());
        result = prime * result + ((getMaxAuthCode() == null) ? 0 : getMaxAuthCode().hashCode());
        result = prime * result + ((getAuthCode() == null) ? 0 : getAuthCode().hashCode());
        result = prime * result + ((getAuthCategory() == null) ? 0 : getAuthCategory().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getLastModifiedBy() == null) ? 0 : getLastModifiedBy().hashCode());
        result = prime * result + ((getLastModifiedDate() == null) ? 0 : getLastModifiedDate().hashCode());
        return result;
    }
}