/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * NichePushQueryHelper.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-28 Created
 */
package java;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NichePushQueryHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public NichePushQueryHelper() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 商机推送表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-08-28
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPushTimeIsNull() {
            addCriterion("push_time is null");
            return (Criteria) this;
        }

        public Criteria andPushTimeIsNotNull() {
            addCriterion("push_time is not null");
            return (Criteria) this;
        }

        public Criteria andPushTimeEqualTo(Date value) {
            addCriterion("push_time =", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeNotEqualTo(Date value) {
            addCriterion("push_time <>", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeGreaterThan(Date value) {
            addCriterion("push_time >", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("push_time >=", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeLessThan(Date value) {
            addCriterion("push_time <", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeLessThanOrEqualTo(Date value) {
            addCriterion("push_time <=", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeIn(List<Date> values) {
            addCriterion("push_time in", values, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeNotIn(List<Date> values) {
            addCriterion("push_time not in", values, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeBetween(Date value1, Date value2) {
            addCriterion("push_time between", value1, value2, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeNotBetween(Date value1, Date value2) {
            addCriterion("push_time not between", value1, value2, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushStatusIsNull() {
            addCriterion("push_status is null");
            return (Criteria) this;
        }

        public Criteria andPushStatusIsNotNull() {
            addCriterion("push_status is not null");
            return (Criteria) this;
        }

        public Criteria andPushStatusEqualTo(Short value) {
            addCriterion("push_status =", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusNotEqualTo(Short value) {
            addCriterion("push_status <>", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusGreaterThan(Short value) {
            addCriterion("push_status >", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("push_status >=", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusLessThan(Short value) {
            addCriterion("push_status <", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusLessThanOrEqualTo(Short value) {
            addCriterion("push_status <=", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusIn(List<Short> values) {
            addCriterion("push_status in", values, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusNotIn(List<Short> values) {
            addCriterion("push_status not in", values, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusBetween(Short value1, Short value2) {
            addCriterion("push_status between", value1, value2, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusNotBetween(Short value1, Short value2) {
            addCriterion("push_status not between", value1, value2, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeIsNull() {
            addCriterion("withdraw_time is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeIsNotNull() {
            addCriterion("withdraw_time is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeEqualTo(Date value) {
            addCriterion("withdraw_time =", value, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeNotEqualTo(Date value) {
            addCriterion("withdraw_time <>", value, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeGreaterThan(Date value) {
            addCriterion("withdraw_time >", value, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("withdraw_time >=", value, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeLessThan(Date value) {
            addCriterion("withdraw_time <", value, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeLessThanOrEqualTo(Date value) {
            addCriterion("withdraw_time <=", value, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeIn(List<Date> values) {
            addCriterion("withdraw_time in", values, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeNotIn(List<Date> values) {
            addCriterion("withdraw_time not in", values, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeBetween(Date value1, Date value2) {
            addCriterion("withdraw_time between", value1, value2, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeNotBetween(Date value1, Date value2) {
            addCriterion("withdraw_time not between", value1, value2, "withdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdIsNull() {
            addCriterion("withdraw_user_id is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdIsNotNull() {
            addCriterion("withdraw_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdEqualTo(Long value) {
            addCriterion("withdraw_user_id =", value, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdNotEqualTo(Long value) {
            addCriterion("withdraw_user_id <>", value, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdGreaterThan(Long value) {
            addCriterion("withdraw_user_id >", value, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("withdraw_user_id >=", value, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdLessThan(Long value) {
            addCriterion("withdraw_user_id <", value, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdLessThanOrEqualTo(Long value) {
            addCriterion("withdraw_user_id <=", value, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdIn(List<Long> values) {
            addCriterion("withdraw_user_id in", values, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdNotIn(List<Long> values) {
            addCriterion("withdraw_user_id not in", values, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdBetween(Long value1, Long value2) {
            addCriterion("withdraw_user_id between", value1, value2, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andWithdrawUserIdNotBetween(Long value1, Long value2) {
            addCriterion("withdraw_user_id not between", value1, value2, "withdrawUserId");
            return (Criteria) this;
        }

        public Criteria andNicheTypeIsNull() {
            addCriterion("niche_type is null");
            return (Criteria) this;
        }

        public Criteria andNicheTypeIsNotNull() {
            addCriterion("niche_type is not null");
            return (Criteria) this;
        }

        public Criteria andNicheTypeEqualTo(Short value) {
            addCriterion("niche_type =", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeNotEqualTo(Short value) {
            addCriterion("niche_type <>", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeGreaterThan(Short value) {
            addCriterion("niche_type >", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("niche_type >=", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeLessThan(Short value) {
            addCriterion("niche_type <", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeLessThanOrEqualTo(Short value) {
            addCriterion("niche_type <=", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeIn(List<Short> values) {
            addCriterion("niche_type in", values, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeNotIn(List<Short> values) {
            addCriterion("niche_type not in", values, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeBetween(Short value1, Short value2) {
            addCriterion("niche_type between", value1, value2, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeNotBetween(Short value1, Short value2) {
            addCriterion("niche_type not between", value1, value2, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTitleIsNull() {
            addCriterion("niche_title is null");
            return (Criteria) this;
        }

        public Criteria andNicheTitleIsNotNull() {
            addCriterion("niche_title is not null");
            return (Criteria) this;
        }

        public Criteria andNicheTitleEqualTo(String value) {
            addCriterion("niche_title =", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleNotEqualTo(String value) {
            addCriterion("niche_title <>", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleGreaterThan(String value) {
            addCriterion("niche_title >", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleGreaterThanOrEqualTo(String value) {
            addCriterion("niche_title >=", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleLessThan(String value) {
            addCriterion("niche_title <", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleLessThanOrEqualTo(String value) {
            addCriterion("niche_title <=", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleLike(String value) {
            addCriterion("niche_title like", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleNotLike(String value) {
            addCriterion("niche_title not like", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleIn(List<String> values) {
            addCriterion("niche_title in", values, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleNotIn(List<String> values) {
            addCriterion("niche_title not in", values, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleBetween(String value1, String value2) {
            addCriterion("niche_title between", value1, value2, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleNotBetween(String value1, String value2) {
            addCriterion("niche_title not between", value1, value2, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheIdIsNull() {
            addCriterion("niche_id is null");
            return (Criteria) this;
        }

        public Criteria andNicheIdIsNotNull() {
            addCriterion("niche_id is not null");
            return (Criteria) this;
        }

        public Criteria andNicheIdEqualTo(Long value) {
            addCriterion("niche_id =", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdNotEqualTo(Long value) {
            addCriterion("niche_id <>", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdGreaterThan(Long value) {
            addCriterion("niche_id >", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdGreaterThanOrEqualTo(Long value) {
            addCriterion("niche_id >=", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdLessThan(Long value) {
            addCriterion("niche_id <", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdLessThanOrEqualTo(Long value) {
            addCriterion("niche_id <=", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdIn(List<Long> values) {
            addCriterion("niche_id in", values, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdNotIn(List<Long> values) {
            addCriterion("niche_id not in", values, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdBetween(Long value1, Long value2) {
            addCriterion("niche_id between", value1, value2, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdNotBetween(Long value1, Long value2) {
            addCriterion("niche_id not between", value1, value2, "nicheId");
            return (Criteria) this;
        }

        public Criteria andPushTypeIsNull() {
            addCriterion("push_type is null");
            return (Criteria) this;
        }

        public Criteria andPushTypeIsNotNull() {
            addCriterion("push_type is not null");
            return (Criteria) this;
        }

        public Criteria andPushTypeEqualTo(Short value) {
            addCriterion("push_type =", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotEqualTo(Short value) {
            addCriterion("push_type <>", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeGreaterThan(Short value) {
            addCriterion("push_type >", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("push_type >=", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeLessThan(Short value) {
            addCriterion("push_type <", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeLessThanOrEqualTo(Short value) {
            addCriterion("push_type <=", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeIn(List<Short> values) {
            addCriterion("push_type in", values, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotIn(List<Short> values) {
            addCriterion("push_type not in", values, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeBetween(Short value1, Short value2) {
            addCriterion("push_type between", value1, value2, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotBetween(Short value1, Short value2) {
            addCriterion("push_type not between", value1, value2, "pushType");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIsNull() {
            addCriterion("area_code is null");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIsNotNull() {
            addCriterion("area_code is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCodeEqualTo(String value) {
            addCriterion("area_code =", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotEqualTo(String value) {
            addCriterion("area_code <>", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeGreaterThan(String value) {
            addCriterion("area_code >", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("area_code >=", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLessThan(String value) {
            addCriterion("area_code <", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLessThanOrEqualTo(String value) {
            addCriterion("area_code <=", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLike(String value) {
            addCriterion("area_code like", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotLike(String value) {
            addCriterion("area_code not like", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIn(List<String> values) {
            addCriterion("area_code in", values, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotIn(List<String> values) {
            addCriterion("area_code not in", values, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeBetween(String value1, String value2) {
            addCriterion("area_code between", value1, value2, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotBetween(String value1, String value2) {
            addCriterion("area_code not between", value1, value2, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaNameIsNull() {
            addCriterion("area_name is null");
            return (Criteria) this;
        }

        public Criteria andAreaNameIsNotNull() {
            addCriterion("area_name is not null");
            return (Criteria) this;
        }

        public Criteria andAreaNameEqualTo(String value) {
            addCriterion("area_name =", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotEqualTo(String value) {
            addCriterion("area_name <>", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameGreaterThan(String value) {
            addCriterion("area_name >", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameGreaterThanOrEqualTo(String value) {
            addCriterion("area_name >=", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLessThan(String value) {
            addCriterion("area_name <", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLessThanOrEqualTo(String value) {
            addCriterion("area_name <=", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLike(String value) {
            addCriterion("area_name like", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotLike(String value) {
            addCriterion("area_name not like", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameIn(List<String> values) {
            addCriterion("area_name in", values, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotIn(List<String> values) {
            addCriterion("area_name not in", values, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameBetween(String value1, String value2) {
            addCriterion("area_name between", value1, value2, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotBetween(String value1, String value2) {
            addCriterion("area_name not between", value1, value2, "areaName");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoIsNull() {
            addCriterion("user_mobile_no is null");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoIsNotNull() {
            addCriterion("user_mobile_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoEqualTo(String value) {
            addCriterion("user_mobile_no =", value, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoNotEqualTo(String value) {
            addCriterion("user_mobile_no <>", value, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoGreaterThan(String value) {
            addCriterion("user_mobile_no >", value, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("user_mobile_no >=", value, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoLessThan(String value) {
            addCriterion("user_mobile_no <", value, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoLessThanOrEqualTo(String value) {
            addCriterion("user_mobile_no <=", value, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoLike(String value) {
            addCriterion("user_mobile_no like", value, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoNotLike(String value) {
            addCriterion("user_mobile_no not like", value, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoIn(List<String> values) {
            addCriterion("user_mobile_no in", values, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoNotIn(List<String> values) {
            addCriterion("user_mobile_no not in", values, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoBetween(String value1, String value2) {
            addCriterion("user_mobile_no between", value1, value2, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoNotBetween(String value1, String value2) {
            addCriterion("user_mobile_no not between", value1, value2, "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserFullnameIsNull() {
            addCriterion("user_fullname is null");
            return (Criteria) this;
        }

        public Criteria andUserFullnameIsNotNull() {
            addCriterion("user_fullname is not null");
            return (Criteria) this;
        }

        public Criteria andUserFullnameEqualTo(String value) {
            addCriterion("user_fullname =", value, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameNotEqualTo(String value) {
            addCriterion("user_fullname <>", value, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameGreaterThan(String value) {
            addCriterion("user_fullname >", value, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameGreaterThanOrEqualTo(String value) {
            addCriterion("user_fullname >=", value, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameLessThan(String value) {
            addCriterion("user_fullname <", value, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameLessThanOrEqualTo(String value) {
            addCriterion("user_fullname <=", value, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameLike(String value) {
            addCriterion("user_fullname like", value, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameNotLike(String value) {
            addCriterion("user_fullname not like", value, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameIn(List<String> values) {
            addCriterion("user_fullname in", values, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameNotIn(List<String> values) {
            addCriterion("user_fullname not in", values, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameBetween(String value1, String value2) {
            addCriterion("user_fullname between", value1, value2, "userFullname");
            return (Criteria) this;
        }

        public Criteria andUserFullnameNotBetween(String value1, String value2) {
            addCriterion("user_fullname not between", value1, value2, "userFullname");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountIsNull() {
            addCriterion("push_conmapy_count is null");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountIsNotNull() {
            addCriterion("push_conmapy_count is not null");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountEqualTo(Integer value) {
            addCriterion("push_conmapy_count =", value, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountNotEqualTo(Integer value) {
            addCriterion("push_conmapy_count <>", value, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountGreaterThan(Integer value) {
            addCriterion("push_conmapy_count >", value, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_conmapy_count >=", value, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountLessThan(Integer value) {
            addCriterion("push_conmapy_count <", value, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountLessThanOrEqualTo(Integer value) {
            addCriterion("push_conmapy_count <=", value, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountIn(List<Integer> values) {
            addCriterion("push_conmapy_count in", values, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountNotIn(List<Integer> values) {
            addCriterion("push_conmapy_count not in", values, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountBetween(Integer value1, Integer value2) {
            addCriterion("push_conmapy_count between", value1, value2, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andPushConmapyCountNotBetween(Integer value1, Integer value2) {
            addCriterion("push_conmapy_count not between", value1, value2, "pushConmapyCount");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("create_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("create_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(Long value) {
            addCriterion("create_id =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(Long value) {
            addCriterion("create_id <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(Long value) {
            addCriterion("create_id >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_id >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(Long value) {
            addCriterion("create_id <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(Long value) {
            addCriterion("create_id <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<Long> values) {
            addCriterion("create_id in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<Long> values) {
            addCriterion("create_id not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(Long value1, Long value2) {
            addCriterion("create_id between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(Long value1, Long value2) {
            addCriterion("create_id not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("update_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("update_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(Long value) {
            addCriterion("update_id =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(Long value) {
            addCriterion("update_id <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(Long value) {
            addCriterion("update_id >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("update_id >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(Long value) {
            addCriterion("update_id <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(Long value) {
            addCriterion("update_id <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<Long> values) {
            addCriterion("update_id in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<Long> values) {
            addCriterion("update_id not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(Long value1, Long value2) {
            addCriterion("update_id between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(Long value1, Long value2) {
            addCriterion("update_id not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSeqIsNull() {
            addCriterion("seq is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("seq is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(Long value) {
            addCriterion("seq =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(Long value) {
            addCriterion("seq <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(Long value) {
            addCriterion("seq >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("seq >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(Long value) {
            addCriterion("seq <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(Long value) {
            addCriterion("seq <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<Long> values) {
            addCriterion("seq in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<Long> values) {
            addCriterion("seq not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(Long value1, Long value2) {
            addCriterion("seq between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(Long value1, Long value2) {
            addCriterion("seq not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andIndustryIdIsNull() {
            addCriterion("industry_id is null");
            return (Criteria) this;
        }

        public Criteria andIndustryIdIsNotNull() {
            addCriterion("industry_id is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryIdEqualTo(String value) {
            addCriterion("industry_id =", value, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdNotEqualTo(String value) {
            addCriterion("industry_id <>", value, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdGreaterThan(String value) {
            addCriterion("industry_id >", value, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdGreaterThanOrEqualTo(String value) {
            addCriterion("industry_id >=", value, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdLessThan(String value) {
            addCriterion("industry_id <", value, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdLessThanOrEqualTo(String value) {
            addCriterion("industry_id <=", value, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdLike(String value) {
            addCriterion("industry_id like", value, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdNotLike(String value) {
            addCriterion("industry_id not like", value, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdIn(List<String> values) {
            addCriterion("industry_id in", values, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdNotIn(List<String> values) {
            addCriterion("industry_id not in", values, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdBetween(String value1, String value2) {
            addCriterion("industry_id between", value1, value2, "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryIdNotBetween(String value1, String value2) {
            addCriterion("industry_id not between", value1, value2, "industryId");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIsNull() {
            addCriterion("area_type is null");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIsNotNull() {
            addCriterion("area_type is not null");
            return (Criteria) this;
        }

        public Criteria andAreaTypeEqualTo(Short value) {
            addCriterion("area_type =", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotEqualTo(Short value) {
            addCriterion("area_type <>", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeGreaterThan(Short value) {
            addCriterion("area_type >", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("area_type >=", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeLessThan(Short value) {
            addCriterion("area_type <", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeLessThanOrEqualTo(Short value) {
            addCriterion("area_type <=", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIn(List<Short> values) {
            addCriterion("area_type in", values, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotIn(List<Short> values) {
            addCriterion("area_type not in", values, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeBetween(Short value1, Short value2) {
            addCriterion("area_type between", value1, value2, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotBetween(Short value1, Short value2) {
            addCriterion("area_type not between", value1, value2, "areaType");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Short value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Short value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Short value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Short value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Short value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Short> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Short> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Short value1, Short value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Short value1, Short value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andIndustryNameIsNull() {
            addCriterion("industry_name is null");
            return (Criteria) this;
        }

        public Criteria andIndustryNameIsNotNull() {
            addCriterion("industry_name is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryNameEqualTo(String value) {
            addCriterion("industry_name =", value, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameNotEqualTo(String value) {
            addCriterion("industry_name <>", value, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameGreaterThan(String value) {
            addCriterion("industry_name >", value, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameGreaterThanOrEqualTo(String value) {
            addCriterion("industry_name >=", value, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameLessThan(String value) {
            addCriterion("industry_name <", value, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameLessThanOrEqualTo(String value) {
            addCriterion("industry_name <=", value, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameLike(String value) {
            addCriterion("industry_name like", value, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameNotLike(String value) {
            addCriterion("industry_name not like", value, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameIn(List<String> values) {
            addCriterion("industry_name in", values, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameNotIn(List<String> values) {
            addCriterion("industry_name not in", values, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameBetween(String value1, String value2) {
            addCriterion("industry_name between", value1, value2, "industryName");
            return (Criteria) this;
        }

        public Criteria andIndustryNameNotBetween(String value1, String value2) {
            addCriterion("industry_name not between", value1, value2, "industryName");
            return (Criteria) this;
        }

        public Criteria andNicheTitleLikeInsensitive(String value) {
            addCriterion("upper(niche_title) like", value.toUpperCase(), "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLikeInsensitive(String value) {
            addCriterion("upper(area_code) like", value.toUpperCase(), "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaNameLikeInsensitive(String value) {
            addCriterion("upper(area_name) like", value.toUpperCase(), "areaName");
            return (Criteria) this;
        }

        public Criteria andUserMobileNoLikeInsensitive(String value) {
            addCriterion("upper(user_mobile_no) like", value.toUpperCase(), "userMobileNo");
            return (Criteria) this;
        }

        public Criteria andUserFullnameLikeInsensitive(String value) {
            addCriterion("upper(user_fullname) like", value.toUpperCase(), "userFullname");
            return (Criteria) this;
        }

        public Criteria andIndustryIdLikeInsensitive(String value) {
            addCriterion("upper(industry_id) like", value.toUpperCase(), "industryId");
            return (Criteria) this;
        }

        public Criteria andIndustryNameLikeInsensitive(String value) {
            addCriterion("upper(industry_name) like", value.toUpperCase(), "industryName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_niche_push
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 28 11:46:45 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 商机推送表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-08-28
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}