/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * NichePushDetailQueryHelper.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-28 Created
 */
package java;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NichePushDetailQueryHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public NichePushDetailQueryHelper() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 商机推送表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-08-28
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPushIdIsNull() {
            addCriterion("push_id is null");
            return (Criteria) this;
        }

        public Criteria andPushIdIsNotNull() {
            addCriterion("push_id is not null");
            return (Criteria) this;
        }

        public Criteria andPushIdEqualTo(Long value) {
            addCriterion("push_id =", value, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdNotEqualTo(Long value) {
            addCriterion("push_id <>", value, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdGreaterThan(Long value) {
            addCriterion("push_id >", value, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdGreaterThanOrEqualTo(Long value) {
            addCriterion("push_id >=", value, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdLessThan(Long value) {
            addCriterion("push_id <", value, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdLessThanOrEqualTo(Long value) {
            addCriterion("push_id <=", value, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdIn(List<Long> values) {
            addCriterion("push_id in", values, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdNotIn(List<Long> values) {
            addCriterion("push_id not in", values, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdBetween(Long value1, Long value2) {
            addCriterion("push_id between", value1, value2, "pushId");
            return (Criteria) this;
        }

        public Criteria andPushIdNotBetween(Long value1, Long value2) {
            addCriterion("push_id not between", value1, value2, "pushId");
            return (Criteria) this;
        }

        public Criteria andLinkManIsNull() {
            addCriterion("link_man is null");
            return (Criteria) this;
        }

        public Criteria andLinkManIsNotNull() {
            addCriterion("link_man is not null");
            return (Criteria) this;
        }

        public Criteria andLinkManEqualTo(String value) {
            addCriterion("link_man =", value, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManNotEqualTo(String value) {
            addCriterion("link_man <>", value, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManGreaterThan(String value) {
            addCriterion("link_man >", value, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManGreaterThanOrEqualTo(String value) {
            addCriterion("link_man >=", value, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManLessThan(String value) {
            addCriterion("link_man <", value, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManLessThanOrEqualTo(String value) {
            addCriterion("link_man <=", value, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManLike(String value) {
            addCriterion("link_man like", value, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManNotLike(String value) {
            addCriterion("link_man not like", value, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManIn(List<String> values) {
            addCriterion("link_man in", values, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManNotIn(List<String> values) {
            addCriterion("link_man not in", values, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManBetween(String value1, String value2) {
            addCriterion("link_man between", value1, value2, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkManNotBetween(String value1, String value2) {
            addCriterion("link_man not between", value1, value2, "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIsNull() {
            addCriterion("link_phone is null");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIsNotNull() {
            addCriterion("link_phone is not null");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneEqualTo(String value) {
            addCriterion("link_phone =", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotEqualTo(String value) {
            addCriterion("link_phone <>", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneGreaterThan(String value) {
            addCriterion("link_phone >", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("link_phone >=", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLessThan(String value) {
            addCriterion("link_phone <", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLessThanOrEqualTo(String value) {
            addCriterion("link_phone <=", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLike(String value) {
            addCriterion("link_phone like", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotLike(String value) {
            addCriterion("link_phone not like", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIn(List<String> values) {
            addCriterion("link_phone in", values, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotIn(List<String> values) {
            addCriterion("link_phone not in", values, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneBetween(String value1, String value2) {
            addCriterion("link_phone between", value1, value2, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotBetween(String value1, String value2) {
            addCriterion("link_phone not between", value1, value2, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdIsNull() {
            addCriterion("push_company_id is null");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdIsNotNull() {
            addCriterion("push_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdEqualTo(Long value) {
            addCriterion("push_company_id =", value, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdNotEqualTo(Long value) {
            addCriterion("push_company_id <>", value, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdGreaterThan(Long value) {
            addCriterion("push_company_id >", value, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("push_company_id >=", value, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdLessThan(Long value) {
            addCriterion("push_company_id <", value, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("push_company_id <=", value, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdIn(List<Long> values) {
            addCriterion("push_company_id in", values, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdNotIn(List<Long> values) {
            addCriterion("push_company_id not in", values, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdBetween(Long value1, Long value2) {
            addCriterion("push_company_id between", value1, value2, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("push_company_id not between", value1, value2, "pushCompanyId");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameIsNull() {
            addCriterion("push_company_name is null");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameIsNotNull() {
            addCriterion("push_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameEqualTo(String value) {
            addCriterion("push_company_name =", value, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameNotEqualTo(String value) {
            addCriterion("push_company_name <>", value, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameGreaterThan(String value) {
            addCriterion("push_company_name >", value, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("push_company_name >=", value, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameLessThan(String value) {
            addCriterion("push_company_name <", value, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("push_company_name <=", value, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameLike(String value) {
            addCriterion("push_company_name like", value, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameNotLike(String value) {
            addCriterion("push_company_name not like", value, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameIn(List<String> values) {
            addCriterion("push_company_name in", values, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameNotIn(List<String> values) {
            addCriterion("push_company_name not in", values, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameBetween(String value1, String value2) {
            addCriterion("push_company_name between", value1, value2, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameNotBetween(String value1, String value2) {
            addCriterion("push_company_name not between", value1, value2, "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andOfferTimeIsNull() {
            addCriterion("offer_time is null");
            return (Criteria) this;
        }

        public Criteria andOfferTimeIsNotNull() {
            addCriterion("offer_time is not null");
            return (Criteria) this;
        }

        public Criteria andOfferTimeEqualTo(Date value) {
            addCriterion("offer_time =", value, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeNotEqualTo(Date value) {
            addCriterion("offer_time <>", value, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeGreaterThan(Date value) {
            addCriterion("offer_time >", value, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("offer_time >=", value, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeLessThan(Date value) {
            addCriterion("offer_time <", value, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeLessThanOrEqualTo(Date value) {
            addCriterion("offer_time <=", value, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeIn(List<Date> values) {
            addCriterion("offer_time in", values, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeNotIn(List<Date> values) {
            addCriterion("offer_time not in", values, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeBetween(Date value1, Date value2) {
            addCriterion("offer_time between", value1, value2, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferTimeNotBetween(Date value1, Date value2) {
            addCriterion("offer_time not between", value1, value2, "offerTime");
            return (Criteria) this;
        }

        public Criteria andOfferNoteIsNull() {
            addCriterion("offer_note is null");
            return (Criteria) this;
        }

        public Criteria andOfferNoteIsNotNull() {
            addCriterion("offer_note is not null");
            return (Criteria) this;
        }

        public Criteria andOfferNoteEqualTo(String value) {
            addCriterion("offer_note =", value, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteNotEqualTo(String value) {
            addCriterion("offer_note <>", value, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteGreaterThan(String value) {
            addCriterion("offer_note >", value, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteGreaterThanOrEqualTo(String value) {
            addCriterion("offer_note >=", value, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteLessThan(String value) {
            addCriterion("offer_note <", value, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteLessThanOrEqualTo(String value) {
            addCriterion("offer_note <=", value, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteLike(String value) {
            addCriterion("offer_note like", value, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteNotLike(String value) {
            addCriterion("offer_note not like", value, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteIn(List<String> values) {
            addCriterion("offer_note in", values, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteNotIn(List<String> values) {
            addCriterion("offer_note not in", values, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteBetween(String value1, String value2) {
            addCriterion("offer_note between", value1, value2, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferNoteNotBetween(String value1, String value2) {
            addCriterion("offer_note not between", value1, value2, "offerNote");
            return (Criteria) this;
        }

        public Criteria andOfferStatusIsNull() {
            addCriterion("offer_status is null");
            return (Criteria) this;
        }

        public Criteria andOfferStatusIsNotNull() {
            addCriterion("offer_status is not null");
            return (Criteria) this;
        }

        public Criteria andOfferStatusEqualTo(Short value) {
            addCriterion("offer_status =", value, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusNotEqualTo(Short value) {
            addCriterion("offer_status <>", value, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusGreaterThan(Short value) {
            addCriterion("offer_status >", value, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("offer_status >=", value, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusLessThan(Short value) {
            addCriterion("offer_status <", value, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusLessThanOrEqualTo(Short value) {
            addCriterion("offer_status <=", value, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusIn(List<Short> values) {
            addCriterion("offer_status in", values, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusNotIn(List<Short> values) {
            addCriterion("offer_status not in", values, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusBetween(Short value1, Short value2) {
            addCriterion("offer_status between", value1, value2, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andOfferStatusNotBetween(Short value1, Short value2) {
            addCriterion("offer_status not between", value1, value2, "offerStatus");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdIsNull() {
            addCriterion("handle_person_id is null");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdIsNotNull() {
            addCriterion("handle_person_id is not null");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdEqualTo(Long value) {
            addCriterion("handle_person_id =", value, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdNotEqualTo(Long value) {
            addCriterion("handle_person_id <>", value, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdGreaterThan(Long value) {
            addCriterion("handle_person_id >", value, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdGreaterThanOrEqualTo(Long value) {
            addCriterion("handle_person_id >=", value, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdLessThan(Long value) {
            addCriterion("handle_person_id <", value, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdLessThanOrEqualTo(Long value) {
            addCriterion("handle_person_id <=", value, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdIn(List<Long> values) {
            addCriterion("handle_person_id in", values, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdNotIn(List<Long> values) {
            addCriterion("handle_person_id not in", values, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdBetween(Long value1, Long value2) {
            addCriterion("handle_person_id between", value1, value2, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonIdNotBetween(Long value1, Long value2) {
            addCriterion("handle_person_id not between", value1, value2, "handlePersonId");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameIsNull() {
            addCriterion("handle_person_name is null");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameIsNotNull() {
            addCriterion("handle_person_name is not null");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameEqualTo(String value) {
            addCriterion("handle_person_name =", value, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameNotEqualTo(String value) {
            addCriterion("handle_person_name <>", value, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameGreaterThan(String value) {
            addCriterion("handle_person_name >", value, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameGreaterThanOrEqualTo(String value) {
            addCriterion("handle_person_name >=", value, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameLessThan(String value) {
            addCriterion("handle_person_name <", value, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameLessThanOrEqualTo(String value) {
            addCriterion("handle_person_name <=", value, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameLike(String value) {
            addCriterion("handle_person_name like", value, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameNotLike(String value) {
            addCriterion("handle_person_name not like", value, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameIn(List<String> values) {
            addCriterion("handle_person_name in", values, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameNotIn(List<String> values) {
            addCriterion("handle_person_name not in", values, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameBetween(String value1, String value2) {
            addCriterion("handle_person_name between", value1, value2, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameNotBetween(String value1, String value2) {
            addCriterion("handle_person_name not between", value1, value2, "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsIsNull() {
            addCriterion("handle_opinions is null");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsIsNotNull() {
            addCriterion("handle_opinions is not null");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsEqualTo(String value) {
            addCriterion("handle_opinions =", value, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsNotEqualTo(String value) {
            addCriterion("handle_opinions <>", value, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsGreaterThan(String value) {
            addCriterion("handle_opinions >", value, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsGreaterThanOrEqualTo(String value) {
            addCriterion("handle_opinions >=", value, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsLessThan(String value) {
            addCriterion("handle_opinions <", value, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsLessThanOrEqualTo(String value) {
            addCriterion("handle_opinions <=", value, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsLike(String value) {
            addCriterion("handle_opinions like", value, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsNotLike(String value) {
            addCriterion("handle_opinions not like", value, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsIn(List<String> values) {
            addCriterion("handle_opinions in", values, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsNotIn(List<String> values) {
            addCriterion("handle_opinions not in", values, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsBetween(String value1, String value2) {
            addCriterion("handle_opinions between", value1, value2, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsNotBetween(String value1, String value2) {
            addCriterion("handle_opinions not between", value1, value2, "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andHandleTimeIsNull() {
            addCriterion("handle_time is null");
            return (Criteria) this;
        }

        public Criteria andHandleTimeIsNotNull() {
            addCriterion("handle_time is not null");
            return (Criteria) this;
        }

        public Criteria andHandleTimeEqualTo(Date value) {
            addCriterion("handle_time =", value, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeNotEqualTo(Date value) {
            addCriterion("handle_time <>", value, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeGreaterThan(Date value) {
            addCriterion("handle_time >", value, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("handle_time >=", value, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeLessThan(Date value) {
            addCriterion("handle_time <", value, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeLessThanOrEqualTo(Date value) {
            addCriterion("handle_time <=", value, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeIn(List<Date> values) {
            addCriterion("handle_time in", values, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeNotIn(List<Date> values) {
            addCriterion("handle_time not in", values, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeBetween(Date value1, Date value2) {
            addCriterion("handle_time between", value1, value2, "handleTime");
            return (Criteria) this;
        }

        public Criteria andHandleTimeNotBetween(Date value1, Date value2) {
            addCriterion("handle_time not between", value1, value2, "handleTime");
            return (Criteria) this;
        }

        public Criteria andIsHandleIsNull() {
            addCriterion("is_handle is null");
            return (Criteria) this;
        }

        public Criteria andIsHandleIsNotNull() {
            addCriterion("is_handle is not null");
            return (Criteria) this;
        }

        public Criteria andIsHandleEqualTo(Short value) {
            addCriterion("is_handle =", value, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleNotEqualTo(Short value) {
            addCriterion("is_handle <>", value, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleGreaterThan(Short value) {
            addCriterion("is_handle >", value, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleGreaterThanOrEqualTo(Short value) {
            addCriterion("is_handle >=", value, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleLessThan(Short value) {
            addCriterion("is_handle <", value, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleLessThanOrEqualTo(Short value) {
            addCriterion("is_handle <=", value, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleIn(List<Short> values) {
            addCriterion("is_handle in", values, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleNotIn(List<Short> values) {
            addCriterion("is_handle not in", values, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleBetween(Short value1, Short value2) {
            addCriterion("is_handle between", value1, value2, "isHandle");
            return (Criteria) this;
        }

        public Criteria andIsHandleNotBetween(Short value1, Short value2) {
            addCriterion("is_handle not between", value1, value2, "isHandle");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("create_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("create_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(Long value) {
            addCriterion("create_id =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(Long value) {
            addCriterion("create_id <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(Long value) {
            addCriterion("create_id >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_id >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(Long value) {
            addCriterion("create_id <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(Long value) {
            addCriterion("create_id <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<Long> values) {
            addCriterion("create_id in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<Long> values) {
            addCriterion("create_id not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(Long value1, Long value2) {
            addCriterion("create_id between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(Long value1, Long value2) {
            addCriterion("create_id not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("update_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("update_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(Long value) {
            addCriterion("update_id =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(Long value) {
            addCriterion("update_id <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(Long value) {
            addCriterion("update_id >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("update_id >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(Long value) {
            addCriterion("update_id <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(Long value) {
            addCriterion("update_id <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<Long> values) {
            addCriterion("update_id in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<Long> values) {
            addCriterion("update_id not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(Long value1, Long value2) {
            addCriterion("update_id between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(Long value1, Long value2) {
            addCriterion("update_id not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andNicheTypeIsNull() {
            addCriterion("niche_type is null");
            return (Criteria) this;
        }

        public Criteria andNicheTypeIsNotNull() {
            addCriterion("niche_type is not null");
            return (Criteria) this;
        }

        public Criteria andNicheTypeEqualTo(Short value) {
            addCriterion("niche_type =", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeNotEqualTo(Short value) {
            addCriterion("niche_type <>", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeGreaterThan(Short value) {
            addCriterion("niche_type >", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("niche_type >=", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeLessThan(Short value) {
            addCriterion("niche_type <", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeLessThanOrEqualTo(Short value) {
            addCriterion("niche_type <=", value, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeIn(List<Short> values) {
            addCriterion("niche_type in", values, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeNotIn(List<Short> values) {
            addCriterion("niche_type not in", values, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeBetween(Short value1, Short value2) {
            addCriterion("niche_type between", value1, value2, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTypeNotBetween(Short value1, Short value2) {
            addCriterion("niche_type not between", value1, value2, "nicheType");
            return (Criteria) this;
        }

        public Criteria andNicheTitleIsNull() {
            addCriterion("niche_title is null");
            return (Criteria) this;
        }

        public Criteria andNicheTitleIsNotNull() {
            addCriterion("niche_title is not null");
            return (Criteria) this;
        }

        public Criteria andNicheTitleEqualTo(String value) {
            addCriterion("niche_title =", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleNotEqualTo(String value) {
            addCriterion("niche_title <>", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleGreaterThan(String value) {
            addCriterion("niche_title >", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleGreaterThanOrEqualTo(String value) {
            addCriterion("niche_title >=", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleLessThan(String value) {
            addCriterion("niche_title <", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleLessThanOrEqualTo(String value) {
            addCriterion("niche_title <=", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleLike(String value) {
            addCriterion("niche_title like", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleNotLike(String value) {
            addCriterion("niche_title not like", value, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleIn(List<String> values) {
            addCriterion("niche_title in", values, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleNotIn(List<String> values) {
            addCriterion("niche_title not in", values, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleBetween(String value1, String value2) {
            addCriterion("niche_title between", value1, value2, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheTitleNotBetween(String value1, String value2) {
            addCriterion("niche_title not between", value1, value2, "nicheTitle");
            return (Criteria) this;
        }

        public Criteria andNicheIdIsNull() {
            addCriterion("niche_id is null");
            return (Criteria) this;
        }

        public Criteria andNicheIdIsNotNull() {
            addCriterion("niche_id is not null");
            return (Criteria) this;
        }

        public Criteria andNicheIdEqualTo(Long value) {
            addCriterion("niche_id =", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdNotEqualTo(Long value) {
            addCriterion("niche_id <>", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdGreaterThan(Long value) {
            addCriterion("niche_id >", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdGreaterThanOrEqualTo(Long value) {
            addCriterion("niche_id >=", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdLessThan(Long value) {
            addCriterion("niche_id <", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdLessThanOrEqualTo(Long value) {
            addCriterion("niche_id <=", value, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdIn(List<Long> values) {
            addCriterion("niche_id in", values, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdNotIn(List<Long> values) {
            addCriterion("niche_id not in", values, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdBetween(Long value1, Long value2) {
            addCriterion("niche_id between", value1, value2, "nicheId");
            return (Criteria) this;
        }

        public Criteria andNicheIdNotBetween(Long value1, Long value2) {
            addCriterion("niche_id not between", value1, value2, "nicheId");
            return (Criteria) this;
        }

        public Criteria andPushTypeIsNull() {
            addCriterion("push_type is null");
            return (Criteria) this;
        }

        public Criteria andPushTypeIsNotNull() {
            addCriterion("push_type is not null");
            return (Criteria) this;
        }

        public Criteria andPushTypeEqualTo(Short value) {
            addCriterion("push_type =", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotEqualTo(Short value) {
            addCriterion("push_type <>", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeGreaterThan(Short value) {
            addCriterion("push_type >", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("push_type >=", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeLessThan(Short value) {
            addCriterion("push_type <", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeLessThanOrEqualTo(Short value) {
            addCriterion("push_type <=", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeIn(List<Short> values) {
            addCriterion("push_type in", values, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotIn(List<Short> values) {
            addCriterion("push_type not in", values, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeBetween(Short value1, Short value2) {
            addCriterion("push_type between", value1, value2, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotBetween(Short value1, Short value2) {
            addCriterion("push_type not between", value1, value2, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTimeIsNull() {
            addCriterion("push_time is null");
            return (Criteria) this;
        }

        public Criteria andPushTimeIsNotNull() {
            addCriterion("push_time is not null");
            return (Criteria) this;
        }

        public Criteria andPushTimeEqualTo(Date value) {
            addCriterion("push_time =", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeNotEqualTo(Date value) {
            addCriterion("push_time <>", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeGreaterThan(Date value) {
            addCriterion("push_time >", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("push_time >=", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeLessThan(Date value) {
            addCriterion("push_time <", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeLessThanOrEqualTo(Date value) {
            addCriterion("push_time <=", value, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeIn(List<Date> values) {
            addCriterion("push_time in", values, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeNotIn(List<Date> values) {
            addCriterion("push_time not in", values, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeBetween(Date value1, Date value2) {
            addCriterion("push_time between", value1, value2, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushTimeNotBetween(Date value1, Date value2) {
            addCriterion("push_time not between", value1, value2, "pushTime");
            return (Criteria) this;
        }

        public Criteria andPushStatusIsNull() {
            addCriterion("push_status is null");
            return (Criteria) this;
        }

        public Criteria andPushStatusIsNotNull() {
            addCriterion("push_status is not null");
            return (Criteria) this;
        }

        public Criteria andPushStatusEqualTo(Short value) {
            addCriterion("push_status =", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusNotEqualTo(Short value) {
            addCriterion("push_status <>", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusGreaterThan(Short value) {
            addCriterion("push_status >", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("push_status >=", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusLessThan(Short value) {
            addCriterion("push_status <", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusLessThanOrEqualTo(Short value) {
            addCriterion("push_status <=", value, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusIn(List<Short> values) {
            addCriterion("push_status in", values, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusNotIn(List<Short> values) {
            addCriterion("push_status not in", values, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusBetween(Short value1, Short value2) {
            addCriterion("push_status between", value1, value2, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andPushStatusNotBetween(Short value1, Short value2) {
            addCriterion("push_status not between", value1, value2, "pushStatus");
            return (Criteria) this;
        }

        public Criteria andLinkManLikeInsensitive(String value) {
            addCriterion("upper(link_man) like", value.toUpperCase(), "linkMan");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLikeInsensitive(String value) {
            addCriterion("upper(link_phone) like", value.toUpperCase(), "linkPhone");
            return (Criteria) this;
        }

        public Criteria andPushCompanyNameLikeInsensitive(String value) {
            addCriterion("upper(push_company_name) like", value.toUpperCase(), "pushCompanyName");
            return (Criteria) this;
        }

        public Criteria andOfferNoteLikeInsensitive(String value) {
            addCriterion("upper(offer_note) like", value.toUpperCase(), "offerNote");
            return (Criteria) this;
        }

        public Criteria andHandlePersonNameLikeInsensitive(String value) {
            addCriterion("upper(handle_person_name) like", value.toUpperCase(), "handlePersonName");
            return (Criteria) this;
        }

        public Criteria andHandleOpinionsLikeInsensitive(String value) {
            addCriterion("upper(handle_opinions) like", value.toUpperCase(), "handleOpinions");
            return (Criteria) this;
        }

        public Criteria andNicheTitleLikeInsensitive(String value) {
            addCriterion("upper(niche_title) like", value.toUpperCase(), "nicheTitle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_niche_push_detail
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 28 11:46:45 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 商机推送表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-08-28
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}