/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * PpGradeMaterailQueryHelper.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-23 Created
 */
package java;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PpGradeMaterailQueryHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public PpGradeMaterailQueryHelper() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_grade_materail
     *
     * @mbggenerated Sun Jul 23 12:39:35 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 等级材质对照表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-23
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNull() {
            addCriterion("COMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNotNull() {
            addCriterion("COMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompIdEqualTo(Long value) {
            addCriterion("COMP_ID =", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotEqualTo(Long value) {
            addCriterion("COMP_ID <>", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThan(Long value) {
            addCriterion("COMP_ID >", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COMP_ID >=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThan(Long value) {
            addCriterion("COMP_ID <", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThanOrEqualTo(Long value) {
            addCriterion("COMP_ID <=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdIn(List<Long> values) {
            addCriterion("COMP_ID in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotIn(List<Long> values) {
            addCriterion("COMP_ID not in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdBetween(Long value1, Long value2) {
            addCriterion("COMP_ID between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotBetween(Long value1, Long value2) {
            addCriterion("COMP_ID not between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("PROJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("PROJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Long value) {
            addCriterion("PROJ_ID =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Long value) {
            addCriterion("PROJ_ID <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Long value) {
            addCriterion("PROJ_ID >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Long value) {
            addCriterion("PROJ_ID <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Long> values) {
            addCriterion("PROJ_ID in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Long> values) {
            addCriterion("PROJ_ID not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andMaterialIsNull() {
            addCriterion("MATERIAL is null");
            return (Criteria) this;
        }

        public Criteria andMaterialIsNotNull() {
            addCriterion("MATERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialEqualTo(String value) {
            addCriterion("MATERIAL =", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialNotEqualTo(String value) {
            addCriterion("MATERIAL <>", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialGreaterThan(String value) {
            addCriterion("MATERIAL >", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL >=", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialLessThan(String value) {
            addCriterion("MATERIAL <", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL <=", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialLike(String value) {
            addCriterion("MATERIAL like", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialNotLike(String value) {
            addCriterion("MATERIAL not like", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialIn(List<String> values) {
            addCriterion("MATERIAL in", values, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialNotIn(List<String> values) {
            addCriterion("MATERIAL not in", values, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialBetween(String value1, String value2) {
            addCriterion("MATERIAL between", value1, value2, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialNotBetween(String value1, String value2) {
            addCriterion("MATERIAL not between", value1, value2, "material");
            return (Criteria) this;
        }

        public Criteria andPpClassIsNull() {
            addCriterion("PP_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andPpClassIsNotNull() {
            addCriterion("PP_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andPpClassEqualTo(String value) {
            addCriterion("PP_CLASS =", value, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassNotEqualTo(String value) {
            addCriterion("PP_CLASS <>", value, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassGreaterThan(String value) {
            addCriterion("PP_CLASS >", value, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassGreaterThanOrEqualTo(String value) {
            addCriterion("PP_CLASS >=", value, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassLessThan(String value) {
            addCriterion("PP_CLASS <", value, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassLessThanOrEqualTo(String value) {
            addCriterion("PP_CLASS <=", value, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassLike(String value) {
            addCriterion("PP_CLASS like", value, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassNotLike(String value) {
            addCriterion("PP_CLASS not like", value, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassIn(List<String> values) {
            addCriterion("PP_CLASS in", values, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassNotIn(List<String> values) {
            addCriterion("PP_CLASS not in", values, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassBetween(String value1, String value2) {
            addCriterion("PP_CLASS between", value1, value2, "ppClass");
            return (Criteria) this;
        }

        public Criteria andPpClassNotBetween(String value1, String value2) {
            addCriterion("PP_CLASS not between", value1, value2, "ppClass");
            return (Criteria) this;
        }

        public Criteria andJsizeMinIsNull() {
            addCriterion("JSIZE_MIN is null");
            return (Criteria) this;
        }

        public Criteria andJsizeMinIsNotNull() {
            addCriterion("JSIZE_MIN is not null");
            return (Criteria) this;
        }

        public Criteria andJsizeMinEqualTo(String value) {
            addCriterion("JSIZE_MIN =", value, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinNotEqualTo(String value) {
            addCriterion("JSIZE_MIN <>", value, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinGreaterThan(String value) {
            addCriterion("JSIZE_MIN >", value, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinGreaterThanOrEqualTo(String value) {
            addCriterion("JSIZE_MIN >=", value, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinLessThan(String value) {
            addCriterion("JSIZE_MIN <", value, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinLessThanOrEqualTo(String value) {
            addCriterion("JSIZE_MIN <=", value, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinLike(String value) {
            addCriterion("JSIZE_MIN like", value, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinNotLike(String value) {
            addCriterion("JSIZE_MIN not like", value, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinIn(List<String> values) {
            addCriterion("JSIZE_MIN in", values, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinNotIn(List<String> values) {
            addCriterion("JSIZE_MIN not in", values, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinBetween(String value1, String value2) {
            addCriterion("JSIZE_MIN between", value1, value2, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMinNotBetween(String value1, String value2) {
            addCriterion("JSIZE_MIN not between", value1, value2, "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxIsNull() {
            addCriterion("JSIZE_MAX is null");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxIsNotNull() {
            addCriterion("JSIZE_MAX is not null");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxEqualTo(String value) {
            addCriterion("JSIZE_MAX =", value, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxNotEqualTo(String value) {
            addCriterion("JSIZE_MAX <>", value, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxGreaterThan(String value) {
            addCriterion("JSIZE_MAX >", value, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxGreaterThanOrEqualTo(String value) {
            addCriterion("JSIZE_MAX >=", value, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxLessThan(String value) {
            addCriterion("JSIZE_MAX <", value, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxLessThanOrEqualTo(String value) {
            addCriterion("JSIZE_MAX <=", value, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxLike(String value) {
            addCriterion("JSIZE_MAX like", value, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxNotLike(String value) {
            addCriterion("JSIZE_MAX not like", value, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxIn(List<String> values) {
            addCriterion("JSIZE_MAX in", values, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxNotIn(List<String> values) {
            addCriterion("JSIZE_MAX not in", values, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxBetween(String value1, String value2) {
            addCriterion("JSIZE_MAX between", value1, value2, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxNotBetween(String value1, String value2) {
            addCriterion("JSIZE_MAX not between", value1, value2, "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeIsNull() {
            addCriterion("WALL_THICK_CODE is null");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeIsNotNull() {
            addCriterion("WALL_THICK_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeEqualTo(String value) {
            addCriterion("WALL_THICK_CODE =", value, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeNotEqualTo(String value) {
            addCriterion("WALL_THICK_CODE <>", value, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeGreaterThan(String value) {
            addCriterion("WALL_THICK_CODE >", value, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeGreaterThanOrEqualTo(String value) {
            addCriterion("WALL_THICK_CODE >=", value, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeLessThan(String value) {
            addCriterion("WALL_THICK_CODE <", value, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeLessThanOrEqualTo(String value) {
            addCriterion("WALL_THICK_CODE <=", value, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeLike(String value) {
            addCriterion("WALL_THICK_CODE like", value, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeNotLike(String value) {
            addCriterion("WALL_THICK_CODE not like", value, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeIn(List<String> values) {
            addCriterion("WALL_THICK_CODE in", values, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeNotIn(List<String> values) {
            addCriterion("WALL_THICK_CODE not in", values, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeBetween(String value1, String value2) {
            addCriterion("WALL_THICK_CODE between", value1, value2, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeNotBetween(String value1, String value2) {
            addCriterion("WALL_THICK_CODE not between", value1, value2, "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIsNull() {
            addCriterion("MATERIAL_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIsNotNull() {
            addCriterion("MATERIAL_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeEqualTo(String value) {
            addCriterion("MATERIAL_TYPE =", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotEqualTo(String value) {
            addCriterion("MATERIAL_TYPE <>", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeGreaterThan(String value) {
            addCriterion("MATERIAL_TYPE >", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL_TYPE >=", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeLessThan(String value) {
            addCriterion("MATERIAL_TYPE <", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL_TYPE <=", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeLike(String value) {
            addCriterion("MATERIAL_TYPE like", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotLike(String value) {
            addCriterion("MATERIAL_TYPE not like", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIn(List<String> values) {
            addCriterion("MATERIAL_TYPE in", values, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotIn(List<String> values) {
            addCriterion("MATERIAL_TYPE not in", values, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeBetween(String value1, String value2) {
            addCriterion("MATERIAL_TYPE between", value1, value2, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotBetween(String value1, String value2) {
            addCriterion("MATERIAL_TYPE not between", value1, value2, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryIsNull() {
            addCriterion("MATERIAL_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryIsNotNull() {
            addCriterion("MATERIAL_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryEqualTo(String value) {
            addCriterion("MATERIAL_CATEGORY =", value, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryNotEqualTo(String value) {
            addCriterion("MATERIAL_CATEGORY <>", value, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryGreaterThan(String value) {
            addCriterion("MATERIAL_CATEGORY >", value, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL_CATEGORY >=", value, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryLessThan(String value) {
            addCriterion("MATERIAL_CATEGORY <", value, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL_CATEGORY <=", value, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryLike(String value) {
            addCriterion("MATERIAL_CATEGORY like", value, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryNotLike(String value) {
            addCriterion("MATERIAL_CATEGORY not like", value, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryIn(List<String> values) {
            addCriterion("MATERIAL_CATEGORY in", values, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryNotIn(List<String> values) {
            addCriterion("MATERIAL_CATEGORY not in", values, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryBetween(String value1, String value2) {
            addCriterion("MATERIAL_CATEGORY between", value1, value2, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryNotBetween(String value1, String value2) {
            addCriterion("MATERIAL_CATEGORY not between", value1, value2, "materialCategory");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andMaterialLikeInsensitive(String value) {
            addCriterion("upper(MATERIAL) like", value.toUpperCase(), "material");
            return (Criteria) this;
        }

        public Criteria andPpClassLikeInsensitive(String value) {
            addCriterion("upper(PP_CLASS) like", value.toUpperCase(), "ppClass");
            return (Criteria) this;
        }

        public Criteria andJsizeMinLikeInsensitive(String value) {
            addCriterion("upper(JSIZE_MIN) like", value.toUpperCase(), "jsizeMin");
            return (Criteria) this;
        }

        public Criteria andJsizeMaxLikeInsensitive(String value) {
            addCriterion("upper(JSIZE_MAX) like", value.toUpperCase(), "jsizeMax");
            return (Criteria) this;
        }

        public Criteria andWallThickCodeLikeInsensitive(String value) {
            addCriterion("upper(WALL_THICK_CODE) like", value.toUpperCase(), "wallThickCode");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeLikeInsensitive(String value) {
            addCriterion("upper(MATERIAL_TYPE) like", value.toUpperCase(), "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialCategoryLikeInsensitive(String value) {
            addCriterion("upper(MATERIAL_CATEGORY) like", value.toUpperCase(), "materialCategory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_grade_materail
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 23 12:39:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 等级材质对照表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-23
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}