/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * PpIinspectionTatioQueryHelper.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-18 Created
 */
package java;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PpIinspectionTatioQueryHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public PpIinspectionTatioQueryHelper() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 抽检比例设置表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-18
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNull() {
            addCriterion("COMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNotNull() {
            addCriterion("COMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompIdEqualTo(Long value) {
            addCriterion("COMP_ID =", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotEqualTo(Long value) {
            addCriterion("COMP_ID <>", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThan(Long value) {
            addCriterion("COMP_ID >", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COMP_ID >=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThan(Long value) {
            addCriterion("COMP_ID <", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThanOrEqualTo(Long value) {
            addCriterion("COMP_ID <=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdIn(List<Long> values) {
            addCriterion("COMP_ID in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotIn(List<Long> values) {
            addCriterion("COMP_ID not in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdBetween(Long value1, Long value2) {
            addCriterion("COMP_ID between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotBetween(Long value1, Long value2) {
            addCriterion("COMP_ID not between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("PROJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("PROJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Long value) {
            addCriterion("PROJ_ID =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Long value) {
            addCriterion("PROJ_ID <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Long value) {
            addCriterion("PROJ_ID >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Long value) {
            addCriterion("PROJ_ID <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Long> values) {
            addCriterion("PROJ_ID in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Long> values) {
            addCriterion("PROJ_ID not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeIsNull() {
            addCriterion("INSPECTION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeIsNotNull() {
            addCriterion("INSPECTION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeEqualTo(String value) {
            addCriterion("INSPECTION_CODE =", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeNotEqualTo(String value) {
            addCriterion("INSPECTION_CODE <>", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeGreaterThan(String value) {
            addCriterion("INSPECTION_CODE >", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("INSPECTION_CODE >=", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeLessThan(String value) {
            addCriterion("INSPECTION_CODE <", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeLessThanOrEqualTo(String value) {
            addCriterion("INSPECTION_CODE <=", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeLike(String value) {
            addCriterion("INSPECTION_CODE like", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeNotLike(String value) {
            addCriterion("INSPECTION_CODE not like", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeIn(List<String> values) {
            addCriterion("INSPECTION_CODE in", values, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeNotIn(List<String> values) {
            addCriterion("INSPECTION_CODE not in", values, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeBetween(String value1, String value2) {
            addCriterion("INSPECTION_CODE between", value1, value2, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeNotBetween(String value1, String value2) {
            addCriterion("INSPECTION_CODE not between", value1, value2, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andRtRateIsNull() {
            addCriterion("RT_RATE is null");
            return (Criteria) this;
        }

        public Criteria andRtRateIsNotNull() {
            addCriterion("RT_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andRtRateEqualTo(Long value) {
            addCriterion("RT_RATE =", value, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateNotEqualTo(Long value) {
            addCriterion("RT_RATE <>", value, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateGreaterThan(Long value) {
            addCriterion("RT_RATE >", value, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateGreaterThanOrEqualTo(Long value) {
            addCriterion("RT_RATE >=", value, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateLessThan(Long value) {
            addCriterion("RT_RATE <", value, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateLessThanOrEqualTo(Long value) {
            addCriterion("RT_RATE <=", value, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateIn(List<Long> values) {
            addCriterion("RT_RATE in", values, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateNotIn(List<Long> values) {
            addCriterion("RT_RATE not in", values, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateBetween(Long value1, Long value2) {
            addCriterion("RT_RATE between", value1, value2, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateNotBetween(Long value1, Long value2) {
            addCriterion("RT_RATE not between", value1, value2, "rtRate");
            return (Criteria) this;
        }

        public Criteria andRtRateGdIsNull() {
            addCriterion("RT_RATE_GD is null");
            return (Criteria) this;
        }

        public Criteria andRtRateGdIsNotNull() {
            addCriterion("RT_RATE_GD is not null");
            return (Criteria) this;
        }

        public Criteria andRtRateGdEqualTo(Long value) {
            addCriterion("RT_RATE_GD =", value, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdNotEqualTo(Long value) {
            addCriterion("RT_RATE_GD <>", value, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdGreaterThan(Long value) {
            addCriterion("RT_RATE_GD >", value, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdGreaterThanOrEqualTo(Long value) {
            addCriterion("RT_RATE_GD >=", value, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdLessThan(Long value) {
            addCriterion("RT_RATE_GD <", value, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdLessThanOrEqualTo(Long value) {
            addCriterion("RT_RATE_GD <=", value, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdIn(List<Long> values) {
            addCriterion("RT_RATE_GD in", values, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdNotIn(List<Long> values) {
            addCriterion("RT_RATE_GD not in", values, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdBetween(Long value1, Long value2) {
            addCriterion("RT_RATE_GD between", value1, value2, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtRateGdNotBetween(Long value1, Long value2) {
            addCriterion("RT_RATE_GD not between", value1, value2, "rtRateGd");
            return (Criteria) this;
        }

        public Criteria andRtStandardIsNull() {
            addCriterion("RT_STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andRtStandardIsNotNull() {
            addCriterion("RT_STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andRtStandardEqualTo(String value) {
            addCriterion("RT_STANDARD =", value, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardNotEqualTo(String value) {
            addCriterion("RT_STANDARD <>", value, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardGreaterThan(String value) {
            addCriterion("RT_STANDARD >", value, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardGreaterThanOrEqualTo(String value) {
            addCriterion("RT_STANDARD >=", value, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardLessThan(String value) {
            addCriterion("RT_STANDARD <", value, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardLessThanOrEqualTo(String value) {
            addCriterion("RT_STANDARD <=", value, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardLike(String value) {
            addCriterion("RT_STANDARD like", value, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardNotLike(String value) {
            addCriterion("RT_STANDARD not like", value, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardIn(List<String> values) {
            addCriterion("RT_STANDARD in", values, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardNotIn(List<String> values) {
            addCriterion("RT_STANDARD not in", values, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardBetween(String value1, String value2) {
            addCriterion("RT_STANDARD between", value1, value2, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtStandardNotBetween(String value1, String value2) {
            addCriterion("RT_STANDARD not between", value1, value2, "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtGradeIsNull() {
            addCriterion("RT_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andRtGradeIsNotNull() {
            addCriterion("RT_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andRtGradeEqualTo(String value) {
            addCriterion("RT_GRADE =", value, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeNotEqualTo(String value) {
            addCriterion("RT_GRADE <>", value, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeGreaterThan(String value) {
            addCriterion("RT_GRADE >", value, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeGreaterThanOrEqualTo(String value) {
            addCriterion("RT_GRADE >=", value, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeLessThan(String value) {
            addCriterion("RT_GRADE <", value, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeLessThanOrEqualTo(String value) {
            addCriterion("RT_GRADE <=", value, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeLike(String value) {
            addCriterion("RT_GRADE like", value, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeNotLike(String value) {
            addCriterion("RT_GRADE not like", value, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeIn(List<String> values) {
            addCriterion("RT_GRADE in", values, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeNotIn(List<String> values) {
            addCriterion("RT_GRADE not in", values, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeBetween(String value1, String value2) {
            addCriterion("RT_GRADE between", value1, value2, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andRtGradeNotBetween(String value1, String value2) {
            addCriterion("RT_GRADE not between", value1, value2, "rtGrade");
            return (Criteria) this;
        }

        public Criteria andPtRateIsNull() {
            addCriterion("PT_RATE is null");
            return (Criteria) this;
        }

        public Criteria andPtRateIsNotNull() {
            addCriterion("PT_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andPtRateEqualTo(Long value) {
            addCriterion("PT_RATE =", value, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateNotEqualTo(Long value) {
            addCriterion("PT_RATE <>", value, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateGreaterThan(Long value) {
            addCriterion("PT_RATE >", value, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateGreaterThanOrEqualTo(Long value) {
            addCriterion("PT_RATE >=", value, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateLessThan(Long value) {
            addCriterion("PT_RATE <", value, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateLessThanOrEqualTo(Long value) {
            addCriterion("PT_RATE <=", value, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateIn(List<Long> values) {
            addCriterion("PT_RATE in", values, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateNotIn(List<Long> values) {
            addCriterion("PT_RATE not in", values, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateBetween(Long value1, Long value2) {
            addCriterion("PT_RATE between", value1, value2, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtRateNotBetween(Long value1, Long value2) {
            addCriterion("PT_RATE not between", value1, value2, "ptRate");
            return (Criteria) this;
        }

        public Criteria andPtStandardIsNull() {
            addCriterion("PT_STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andPtStandardIsNotNull() {
            addCriterion("PT_STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andPtStandardEqualTo(String value) {
            addCriterion("PT_STANDARD =", value, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardNotEqualTo(String value) {
            addCriterion("PT_STANDARD <>", value, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardGreaterThan(String value) {
            addCriterion("PT_STANDARD >", value, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardGreaterThanOrEqualTo(String value) {
            addCriterion("PT_STANDARD >=", value, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardLessThan(String value) {
            addCriterion("PT_STANDARD <", value, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardLessThanOrEqualTo(String value) {
            addCriterion("PT_STANDARD <=", value, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardLike(String value) {
            addCriterion("PT_STANDARD like", value, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardNotLike(String value) {
            addCriterion("PT_STANDARD not like", value, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardIn(List<String> values) {
            addCriterion("PT_STANDARD in", values, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardNotIn(List<String> values) {
            addCriterion("PT_STANDARD not in", values, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardBetween(String value1, String value2) {
            addCriterion("PT_STANDARD between", value1, value2, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtStandardNotBetween(String value1, String value2) {
            addCriterion("PT_STANDARD not between", value1, value2, "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtGradeIsNull() {
            addCriterion("PT_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andPtGradeIsNotNull() {
            addCriterion("PT_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andPtGradeEqualTo(String value) {
            addCriterion("PT_GRADE =", value, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeNotEqualTo(String value) {
            addCriterion("PT_GRADE <>", value, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeGreaterThan(String value) {
            addCriterion("PT_GRADE >", value, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeGreaterThanOrEqualTo(String value) {
            addCriterion("PT_GRADE >=", value, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeLessThan(String value) {
            addCriterion("PT_GRADE <", value, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeLessThanOrEqualTo(String value) {
            addCriterion("PT_GRADE <=", value, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeLike(String value) {
            addCriterion("PT_GRADE like", value, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeNotLike(String value) {
            addCriterion("PT_GRADE not like", value, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeIn(List<String> values) {
            addCriterion("PT_GRADE in", values, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeNotIn(List<String> values) {
            addCriterion("PT_GRADE not in", values, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeBetween(String value1, String value2) {
            addCriterion("PT_GRADE between", value1, value2, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andPtGradeNotBetween(String value1, String value2) {
            addCriterion("PT_GRADE not between", value1, value2, "ptGrade");
            return (Criteria) this;
        }

        public Criteria andUtRateIsNull() {
            addCriterion("UT_RATE is null");
            return (Criteria) this;
        }

        public Criteria andUtRateIsNotNull() {
            addCriterion("UT_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andUtRateEqualTo(Long value) {
            addCriterion("UT_RATE =", value, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateNotEqualTo(Long value) {
            addCriterion("UT_RATE <>", value, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateGreaterThan(Long value) {
            addCriterion("UT_RATE >", value, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateGreaterThanOrEqualTo(Long value) {
            addCriterion("UT_RATE >=", value, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateLessThan(Long value) {
            addCriterion("UT_RATE <", value, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateLessThanOrEqualTo(Long value) {
            addCriterion("UT_RATE <=", value, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateIn(List<Long> values) {
            addCriterion("UT_RATE in", values, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateNotIn(List<Long> values) {
            addCriterion("UT_RATE not in", values, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateBetween(Long value1, Long value2) {
            addCriterion("UT_RATE between", value1, value2, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtRateNotBetween(Long value1, Long value2) {
            addCriterion("UT_RATE not between", value1, value2, "utRate");
            return (Criteria) this;
        }

        public Criteria andUtStandardIsNull() {
            addCriterion("UT_STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andUtStandardIsNotNull() {
            addCriterion("UT_STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andUtStandardEqualTo(String value) {
            addCriterion("UT_STANDARD =", value, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardNotEqualTo(String value) {
            addCriterion("UT_STANDARD <>", value, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardGreaterThan(String value) {
            addCriterion("UT_STANDARD >", value, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardGreaterThanOrEqualTo(String value) {
            addCriterion("UT_STANDARD >=", value, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardLessThan(String value) {
            addCriterion("UT_STANDARD <", value, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardLessThanOrEqualTo(String value) {
            addCriterion("UT_STANDARD <=", value, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardLike(String value) {
            addCriterion("UT_STANDARD like", value, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardNotLike(String value) {
            addCriterion("UT_STANDARD not like", value, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardIn(List<String> values) {
            addCriterion("UT_STANDARD in", values, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardNotIn(List<String> values) {
            addCriterion("UT_STANDARD not in", values, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardBetween(String value1, String value2) {
            addCriterion("UT_STANDARD between", value1, value2, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtStandardNotBetween(String value1, String value2) {
            addCriterion("UT_STANDARD not between", value1, value2, "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtGradeIsNull() {
            addCriterion("UT_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andUtGradeIsNotNull() {
            addCriterion("UT_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andUtGradeEqualTo(String value) {
            addCriterion("UT_GRADE =", value, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeNotEqualTo(String value) {
            addCriterion("UT_GRADE <>", value, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeGreaterThan(String value) {
            addCriterion("UT_GRADE >", value, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeGreaterThanOrEqualTo(String value) {
            addCriterion("UT_GRADE >=", value, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeLessThan(String value) {
            addCriterion("UT_GRADE <", value, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeLessThanOrEqualTo(String value) {
            addCriterion("UT_GRADE <=", value, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeLike(String value) {
            addCriterion("UT_GRADE like", value, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeNotLike(String value) {
            addCriterion("UT_GRADE not like", value, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeIn(List<String> values) {
            addCriterion("UT_GRADE in", values, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeNotIn(List<String> values) {
            addCriterion("UT_GRADE not in", values, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeBetween(String value1, String value2) {
            addCriterion("UT_GRADE between", value1, value2, "utGrade");
            return (Criteria) this;
        }

        public Criteria andUtGradeNotBetween(String value1, String value2) {
            addCriterion("UT_GRADE not between", value1, value2, "utGrade");
            return (Criteria) this;
        }

        public Criteria andMtRateIsNull() {
            addCriterion("MT_RATE is null");
            return (Criteria) this;
        }

        public Criteria andMtRateIsNotNull() {
            addCriterion("MT_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andMtRateEqualTo(Long value) {
            addCriterion("MT_RATE =", value, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateNotEqualTo(Long value) {
            addCriterion("MT_RATE <>", value, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateGreaterThan(Long value) {
            addCriterion("MT_RATE >", value, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateGreaterThanOrEqualTo(Long value) {
            addCriterion("MT_RATE >=", value, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateLessThan(Long value) {
            addCriterion("MT_RATE <", value, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateLessThanOrEqualTo(Long value) {
            addCriterion("MT_RATE <=", value, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateIn(List<Long> values) {
            addCriterion("MT_RATE in", values, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateNotIn(List<Long> values) {
            addCriterion("MT_RATE not in", values, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateBetween(Long value1, Long value2) {
            addCriterion("MT_RATE between", value1, value2, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtRateNotBetween(Long value1, Long value2) {
            addCriterion("MT_RATE not between", value1, value2, "mtRate");
            return (Criteria) this;
        }

        public Criteria andMtStandardIsNull() {
            addCriterion("MT_STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andMtStandardIsNotNull() {
            addCriterion("MT_STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andMtStandardEqualTo(String value) {
            addCriterion("MT_STANDARD =", value, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardNotEqualTo(String value) {
            addCriterion("MT_STANDARD <>", value, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardGreaterThan(String value) {
            addCriterion("MT_STANDARD >", value, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardGreaterThanOrEqualTo(String value) {
            addCriterion("MT_STANDARD >=", value, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardLessThan(String value) {
            addCriterion("MT_STANDARD <", value, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardLessThanOrEqualTo(String value) {
            addCriterion("MT_STANDARD <=", value, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardLike(String value) {
            addCriterion("MT_STANDARD like", value, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardNotLike(String value) {
            addCriterion("MT_STANDARD not like", value, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardIn(List<String> values) {
            addCriterion("MT_STANDARD in", values, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardNotIn(List<String> values) {
            addCriterion("MT_STANDARD not in", values, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardBetween(String value1, String value2) {
            addCriterion("MT_STANDARD between", value1, value2, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtStandardNotBetween(String value1, String value2) {
            addCriterion("MT_STANDARD not between", value1, value2, "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtGradeIsNull() {
            addCriterion("MT_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andMtGradeIsNotNull() {
            addCriterion("MT_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andMtGradeEqualTo(String value) {
            addCriterion("MT_GRADE =", value, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeNotEqualTo(String value) {
            addCriterion("MT_GRADE <>", value, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeGreaterThan(String value) {
            addCriterion("MT_GRADE >", value, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeGreaterThanOrEqualTo(String value) {
            addCriterion("MT_GRADE >=", value, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeLessThan(String value) {
            addCriterion("MT_GRADE <", value, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeLessThanOrEqualTo(String value) {
            addCriterion("MT_GRADE <=", value, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeLike(String value) {
            addCriterion("MT_GRADE like", value, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeNotLike(String value) {
            addCriterion("MT_GRADE not like", value, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeIn(List<String> values) {
            addCriterion("MT_GRADE in", values, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeNotIn(List<String> values) {
            addCriterion("MT_GRADE not in", values, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeBetween(String value1, String value2) {
            addCriterion("MT_GRADE between", value1, value2, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andMtGradeNotBetween(String value1, String value2) {
            addCriterion("MT_GRADE not between", value1, value2, "mtGrade");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeLikeInsensitive(String value) {
            addCriterion("upper(INSPECTION_CODE) like", value.toUpperCase(), "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andRtStandardLikeInsensitive(String value) {
            addCriterion("upper(RT_STANDARD) like", value.toUpperCase(), "rtStandard");
            return (Criteria) this;
        }

        public Criteria andRtGradeLikeInsensitive(String value) {
            addCriterion("upper(RT_GRADE) like", value.toUpperCase(), "rtGrade");
            return (Criteria) this;
        }

        public Criteria andPtStandardLikeInsensitive(String value) {
            addCriterion("upper(PT_STANDARD) like", value.toUpperCase(), "ptStandard");
            return (Criteria) this;
        }

        public Criteria andPtGradeLikeInsensitive(String value) {
            addCriterion("upper(PT_GRADE) like", value.toUpperCase(), "ptGrade");
            return (Criteria) this;
        }

        public Criteria andUtStandardLikeInsensitive(String value) {
            addCriterion("upper(UT_STANDARD) like", value.toUpperCase(), "utStandard");
            return (Criteria) this;
        }

        public Criteria andUtGradeLikeInsensitive(String value) {
            addCriterion("upper(UT_GRADE) like", value.toUpperCase(), "utGrade");
            return (Criteria) this;
        }

        public Criteria andMtStandardLikeInsensitive(String value) {
            addCriterion("upper(MT_STANDARD) like", value.toUpperCase(), "mtStandard");
            return (Criteria) this;
        }

        public Criteria andMtGradeLikeInsensitive(String value) {
            addCriterion("upper(MT_GRADE) like", value.toUpperCase(), "mtGrade");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_inspection_ratio
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 18 17:06:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 抽检比例设置表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-18
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}