/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * PpLineQueryHelper.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-18 Created
 */
package java;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PpLineQueryHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public PpLineQueryHelper() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 管道特性表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-18
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNull() {
            addCriterion("COMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNotNull() {
            addCriterion("COMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompIdEqualTo(Long value) {
            addCriterion("COMP_ID =", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotEqualTo(Long value) {
            addCriterion("COMP_ID <>", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThan(Long value) {
            addCriterion("COMP_ID >", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COMP_ID >=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThan(Long value) {
            addCriterion("COMP_ID <", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThanOrEqualTo(Long value) {
            addCriterion("COMP_ID <=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdIn(List<Long> values) {
            addCriterion("COMP_ID in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotIn(List<Long> values) {
            addCriterion("COMP_ID not in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdBetween(Long value1, Long value2) {
            addCriterion("COMP_ID between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotBetween(Long value1, Long value2) {
            addCriterion("COMP_ID not between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("PROJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("PROJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Long value) {
            addCriterion("PROJ_ID =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Long value) {
            addCriterion("PROJ_ID <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Long value) {
            addCriterion("PROJ_ID >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Long value) {
            addCriterion("PROJ_ID <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Long> values) {
            addCriterion("PROJ_ID in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Long> values) {
            addCriterion("PROJ_ID not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("AREA_ID is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("AREA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Long value) {
            addCriterion("AREA_ID =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Long value) {
            addCriterion("AREA_ID <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Long value) {
            addCriterion("AREA_ID >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AREA_ID >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Long value) {
            addCriterion("AREA_ID <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Long value) {
            addCriterion("AREA_ID <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Long> values) {
            addCriterion("AREA_ID in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Long> values) {
            addCriterion("AREA_ID not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Long value1, Long value2) {
            addCriterion("AREA_ID between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Long value1, Long value2) {
            addCriterion("AREA_ID not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andLineNumIsNull() {
            addCriterion("LINE_NUM is null");
            return (Criteria) this;
        }

        public Criteria andLineNumIsNotNull() {
            addCriterion("LINE_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andLineNumEqualTo(String value) {
            addCriterion("LINE_NUM =", value, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumNotEqualTo(String value) {
            addCriterion("LINE_NUM <>", value, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumGreaterThan(String value) {
            addCriterion("LINE_NUM >", value, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_NUM >=", value, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumLessThan(String value) {
            addCriterion("LINE_NUM <", value, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumLessThanOrEqualTo(String value) {
            addCriterion("LINE_NUM <=", value, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumLike(String value) {
            addCriterion("LINE_NUM like", value, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumNotLike(String value) {
            addCriterion("LINE_NUM not like", value, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumIn(List<String> values) {
            addCriterion("LINE_NUM in", values, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumNotIn(List<String> values) {
            addCriterion("LINE_NUM not in", values, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumBetween(String value1, String value2) {
            addCriterion("LINE_NUM between", value1, value2, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineNumNotBetween(String value1, String value2) {
            addCriterion("LINE_NUM not between", value1, value2, "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineVersionIsNull() {
            addCriterion("LINE_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andLineVersionIsNotNull() {
            addCriterion("LINE_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andLineVersionEqualTo(String value) {
            addCriterion("LINE_VERSION =", value, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionNotEqualTo(String value) {
            addCriterion("LINE_VERSION <>", value, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionGreaterThan(String value) {
            addCriterion("LINE_VERSION >", value, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_VERSION >=", value, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionLessThan(String value) {
            addCriterion("LINE_VERSION <", value, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionLessThanOrEqualTo(String value) {
            addCriterion("LINE_VERSION <=", value, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionLike(String value) {
            addCriterion("LINE_VERSION like", value, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionNotLike(String value) {
            addCriterion("LINE_VERSION not like", value, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionIn(List<String> values) {
            addCriterion("LINE_VERSION in", values, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionNotIn(List<String> values) {
            addCriterion("LINE_VERSION not in", values, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionBetween(String value1, String value2) {
            addCriterion("LINE_VERSION between", value1, value2, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andLineVersionNotBetween(String value1, String value2) {
            addCriterion("LINE_VERSION not between", value1, value2, "lineVersion");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("SIZE is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(String value) {
            addCriterion("SIZE =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(String value) {
            addCriterion("SIZE <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(String value) {
            addCriterion("SIZE >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(String value) {
            addCriterion("SIZE >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(String value) {
            addCriterion("SIZE <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(String value) {
            addCriterion("SIZE <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLike(String value) {
            addCriterion("SIZE like", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotLike(String value) {
            addCriterion("SIZE not like", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<String> values) {
            addCriterion("SIZE in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<String> values) {
            addCriterion("SIZE not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(String value1, String value2) {
            addCriterion("SIZE between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(String value1, String value2) {
            addCriterion("SIZE not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andServIsNull() {
            addCriterion("SERV is null");
            return (Criteria) this;
        }

        public Criteria andServIsNotNull() {
            addCriterion("SERV is not null");
            return (Criteria) this;
        }

        public Criteria andServEqualTo(String value) {
            addCriterion("SERV =", value, "serv");
            return (Criteria) this;
        }

        public Criteria andServNotEqualTo(String value) {
            addCriterion("SERV <>", value, "serv");
            return (Criteria) this;
        }

        public Criteria andServGreaterThan(String value) {
            addCriterion("SERV >", value, "serv");
            return (Criteria) this;
        }

        public Criteria andServGreaterThanOrEqualTo(String value) {
            addCriterion("SERV >=", value, "serv");
            return (Criteria) this;
        }

        public Criteria andServLessThan(String value) {
            addCriterion("SERV <", value, "serv");
            return (Criteria) this;
        }

        public Criteria andServLessThanOrEqualTo(String value) {
            addCriterion("SERV <=", value, "serv");
            return (Criteria) this;
        }

        public Criteria andServLike(String value) {
            addCriterion("SERV like", value, "serv");
            return (Criteria) this;
        }

        public Criteria andServNotLike(String value) {
            addCriterion("SERV not like", value, "serv");
            return (Criteria) this;
        }

        public Criteria andServIn(List<String> values) {
            addCriterion("SERV in", values, "serv");
            return (Criteria) this;
        }

        public Criteria andServNotIn(List<String> values) {
            addCriterion("SERV not in", values, "serv");
            return (Criteria) this;
        }

        public Criteria andServBetween(String value1, String value2) {
            addCriterion("SERV between", value1, value2, "serv");
            return (Criteria) this;
        }

        public Criteria andServNotBetween(String value1, String value2) {
            addCriterion("SERV not between", value1, value2, "serv");
            return (Criteria) this;
        }

        public Criteria andClassSpecIsNull() {
            addCriterion("CLASS_SPEC is null");
            return (Criteria) this;
        }

        public Criteria andClassSpecIsNotNull() {
            addCriterion("CLASS_SPEC is not null");
            return (Criteria) this;
        }

        public Criteria andClassSpecEqualTo(String value) {
            addCriterion("CLASS_SPEC =", value, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecNotEqualTo(String value) {
            addCriterion("CLASS_SPEC <>", value, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecGreaterThan(String value) {
            addCriterion("CLASS_SPEC >", value, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecGreaterThanOrEqualTo(String value) {
            addCriterion("CLASS_SPEC >=", value, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecLessThan(String value) {
            addCriterion("CLASS_SPEC <", value, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecLessThanOrEqualTo(String value) {
            addCriterion("CLASS_SPEC <=", value, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecLike(String value) {
            addCriterion("CLASS_SPEC like", value, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecNotLike(String value) {
            addCriterion("CLASS_SPEC not like", value, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecIn(List<String> values) {
            addCriterion("CLASS_SPEC in", values, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecNotIn(List<String> values) {
            addCriterion("CLASS_SPEC not in", values, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecBetween(String value1, String value2) {
            addCriterion("CLASS_SPEC between", value1, value2, "classSpec");
            return (Criteria) this;
        }

        public Criteria andClassSpecNotBetween(String value1, String value2) {
            addCriterion("CLASS_SPEC not between", value1, value2, "classSpec");
            return (Criteria) this;
        }

        public Criteria andLineFromIsNull() {
            addCriterion("LINE_FROM is null");
            return (Criteria) this;
        }

        public Criteria andLineFromIsNotNull() {
            addCriterion("LINE_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andLineFromEqualTo(String value) {
            addCriterion("LINE_FROM =", value, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromNotEqualTo(String value) {
            addCriterion("LINE_FROM <>", value, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromGreaterThan(String value) {
            addCriterion("LINE_FROM >", value, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_FROM >=", value, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromLessThan(String value) {
            addCriterion("LINE_FROM <", value, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromLessThanOrEqualTo(String value) {
            addCriterion("LINE_FROM <=", value, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromLike(String value) {
            addCriterion("LINE_FROM like", value, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromNotLike(String value) {
            addCriterion("LINE_FROM not like", value, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromIn(List<String> values) {
            addCriterion("LINE_FROM in", values, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromNotIn(List<String> values) {
            addCriterion("LINE_FROM not in", values, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromBetween(String value1, String value2) {
            addCriterion("LINE_FROM between", value1, value2, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineFromNotBetween(String value1, String value2) {
            addCriterion("LINE_FROM not between", value1, value2, "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineToIsNull() {
            addCriterion("LINE_TO is null");
            return (Criteria) this;
        }

        public Criteria andLineToIsNotNull() {
            addCriterion("LINE_TO is not null");
            return (Criteria) this;
        }

        public Criteria andLineToEqualTo(String value) {
            addCriterion("LINE_TO =", value, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToNotEqualTo(String value) {
            addCriterion("LINE_TO <>", value, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToGreaterThan(String value) {
            addCriterion("LINE_TO >", value, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_TO >=", value, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToLessThan(String value) {
            addCriterion("LINE_TO <", value, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToLessThanOrEqualTo(String value) {
            addCriterion("LINE_TO <=", value, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToLike(String value) {
            addCriterion("LINE_TO like", value, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToNotLike(String value) {
            addCriterion("LINE_TO not like", value, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToIn(List<String> values) {
            addCriterion("LINE_TO in", values, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToNotIn(List<String> values) {
            addCriterion("LINE_TO not in", values, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToBetween(String value1, String value2) {
            addCriterion("LINE_TO between", value1, value2, "lineTo");
            return (Criteria) this;
        }

        public Criteria andLineToNotBetween(String value1, String value2) {
            addCriterion("LINE_TO not between", value1, value2, "lineTo");
            return (Criteria) this;
        }

        public Criteria andOperatePressureIsNull() {
            addCriterion("OPERATE_PRESSURE is null");
            return (Criteria) this;
        }

        public Criteria andOperatePressureIsNotNull() {
            addCriterion("OPERATE_PRESSURE is not null");
            return (Criteria) this;
        }

        public Criteria andOperatePressureEqualTo(String value) {
            addCriterion("OPERATE_PRESSURE =", value, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureNotEqualTo(String value) {
            addCriterion("OPERATE_PRESSURE <>", value, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureGreaterThan(String value) {
            addCriterion("OPERATE_PRESSURE >", value, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATE_PRESSURE >=", value, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureLessThan(String value) {
            addCriterion("OPERATE_PRESSURE <", value, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureLessThanOrEqualTo(String value) {
            addCriterion("OPERATE_PRESSURE <=", value, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureLike(String value) {
            addCriterion("OPERATE_PRESSURE like", value, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureNotLike(String value) {
            addCriterion("OPERATE_PRESSURE not like", value, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureIn(List<String> values) {
            addCriterion("OPERATE_PRESSURE in", values, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureNotIn(List<String> values) {
            addCriterion("OPERATE_PRESSURE not in", values, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureBetween(String value1, String value2) {
            addCriterion("OPERATE_PRESSURE between", value1, value2, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperatePressureNotBetween(String value1, String value2) {
            addCriterion("OPERATE_PRESSURE not between", value1, value2, "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureIsNull() {
            addCriterion("OPERATE_TEMPERATURE is null");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureIsNotNull() {
            addCriterion("OPERATE_TEMPERATURE is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureEqualTo(String value) {
            addCriterion("OPERATE_TEMPERATURE =", value, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureNotEqualTo(String value) {
            addCriterion("OPERATE_TEMPERATURE <>", value, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureGreaterThan(String value) {
            addCriterion("OPERATE_TEMPERATURE >", value, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATE_TEMPERATURE >=", value, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureLessThan(String value) {
            addCriterion("OPERATE_TEMPERATURE <", value, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureLessThanOrEqualTo(String value) {
            addCriterion("OPERATE_TEMPERATURE <=", value, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureLike(String value) {
            addCriterion("OPERATE_TEMPERATURE like", value, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureNotLike(String value) {
            addCriterion("OPERATE_TEMPERATURE not like", value, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureIn(List<String> values) {
            addCriterion("OPERATE_TEMPERATURE in", values, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureNotIn(List<String> values) {
            addCriterion("OPERATE_TEMPERATURE not in", values, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureBetween(String value1, String value2) {
            addCriterion("OPERATE_TEMPERATURE between", value1, value2, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureNotBetween(String value1, String value2) {
            addCriterion("OPERATE_TEMPERATURE not between", value1, value2, "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andLineLevelIsNull() {
            addCriterion("LINE_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andLineLevelIsNotNull() {
            addCriterion("LINE_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andLineLevelEqualTo(String value) {
            addCriterion("LINE_LEVEL =", value, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelNotEqualTo(String value) {
            addCriterion("LINE_LEVEL <>", value, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelGreaterThan(String value) {
            addCriterion("LINE_LEVEL >", value, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_LEVEL >=", value, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelLessThan(String value) {
            addCriterion("LINE_LEVEL <", value, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelLessThanOrEqualTo(String value) {
            addCriterion("LINE_LEVEL <=", value, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelLike(String value) {
            addCriterion("LINE_LEVEL like", value, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelNotLike(String value) {
            addCriterion("LINE_LEVEL not like", value, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelIn(List<String> values) {
            addCriterion("LINE_LEVEL in", values, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelNotIn(List<String> values) {
            addCriterion("LINE_LEVEL not in", values, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelBetween(String value1, String value2) {
            addCriterion("LINE_LEVEL between", value1, value2, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineLevelNotBetween(String value1, String value2) {
            addCriterion("LINE_LEVEL not between", value1, value2, "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineCodeIsNull() {
            addCriterion("LINE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andLineCodeIsNotNull() {
            addCriterion("LINE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andLineCodeEqualTo(String value) {
            addCriterion("LINE_CODE =", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotEqualTo(String value) {
            addCriterion("LINE_CODE <>", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeGreaterThan(String value) {
            addCriterion("LINE_CODE >", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_CODE >=", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeLessThan(String value) {
            addCriterion("LINE_CODE <", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeLessThanOrEqualTo(String value) {
            addCriterion("LINE_CODE <=", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeLike(String value) {
            addCriterion("LINE_CODE like", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotLike(String value) {
            addCriterion("LINE_CODE not like", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeIn(List<String> values) {
            addCriterion("LINE_CODE in", values, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotIn(List<String> values) {
            addCriterion("LINE_CODE not in", values, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeBetween(String value1, String value2) {
            addCriterion("LINE_CODE between", value1, value2, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotBetween(String value1, String value2) {
            addCriterion("LINE_CODE not between", value1, value2, "lineCode");
            return (Criteria) this;
        }

        public Criteria andDesignPressureIsNull() {
            addCriterion("DESIGN_PRESSURE is null");
            return (Criteria) this;
        }

        public Criteria andDesignPressureIsNotNull() {
            addCriterion("DESIGN_PRESSURE is not null");
            return (Criteria) this;
        }

        public Criteria andDesignPressureEqualTo(String value) {
            addCriterion("DESIGN_PRESSURE =", value, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureNotEqualTo(String value) {
            addCriterion("DESIGN_PRESSURE <>", value, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureGreaterThan(String value) {
            addCriterion("DESIGN_PRESSURE >", value, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_PRESSURE >=", value, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureLessThan(String value) {
            addCriterion("DESIGN_PRESSURE <", value, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_PRESSURE <=", value, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureLike(String value) {
            addCriterion("DESIGN_PRESSURE like", value, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureNotLike(String value) {
            addCriterion("DESIGN_PRESSURE not like", value, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureIn(List<String> values) {
            addCriterion("DESIGN_PRESSURE in", values, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureNotIn(List<String> values) {
            addCriterion("DESIGN_PRESSURE not in", values, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureBetween(String value1, String value2) {
            addCriterion("DESIGN_PRESSURE between", value1, value2, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignPressureNotBetween(String value1, String value2) {
            addCriterion("DESIGN_PRESSURE not between", value1, value2, "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureIsNull() {
            addCriterion("DESIGN_TEMPERATURE is null");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureIsNotNull() {
            addCriterion("DESIGN_TEMPERATURE is not null");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureEqualTo(String value) {
            addCriterion("DESIGN_TEMPERATURE =", value, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureNotEqualTo(String value) {
            addCriterion("DESIGN_TEMPERATURE <>", value, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureGreaterThan(String value) {
            addCriterion("DESIGN_TEMPERATURE >", value, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_TEMPERATURE >=", value, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureLessThan(String value) {
            addCriterion("DESIGN_TEMPERATURE <", value, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_TEMPERATURE <=", value, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureLike(String value) {
            addCriterion("DESIGN_TEMPERATURE like", value, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureNotLike(String value) {
            addCriterion("DESIGN_TEMPERATURE not like", value, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureIn(List<String> values) {
            addCriterion("DESIGN_TEMPERATURE in", values, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureNotIn(List<String> values) {
            addCriterion("DESIGN_TEMPERATURE not in", values, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureBetween(String value1, String value2) {
            addCriterion("DESIGN_TEMPERATURE between", value1, value2, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureNotBetween(String value1, String value2) {
            addCriterion("DESIGN_TEMPERATURE not between", value1, value2, "designTemperature");
            return (Criteria) this;
        }

        public Criteria andKindLevelIsNull() {
            addCriterion("KIND_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andKindLevelIsNotNull() {
            addCriterion("KIND_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andKindLevelEqualTo(String value) {
            addCriterion("KIND_LEVEL =", value, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelNotEqualTo(String value) {
            addCriterion("KIND_LEVEL <>", value, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelGreaterThan(String value) {
            addCriterion("KIND_LEVEL >", value, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelGreaterThanOrEqualTo(String value) {
            addCriterion("KIND_LEVEL >=", value, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelLessThan(String value) {
            addCriterion("KIND_LEVEL <", value, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelLessThanOrEqualTo(String value) {
            addCriterion("KIND_LEVEL <=", value, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelLike(String value) {
            addCriterion("KIND_LEVEL like", value, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelNotLike(String value) {
            addCriterion("KIND_LEVEL not like", value, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelIn(List<String> values) {
            addCriterion("KIND_LEVEL in", values, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelNotIn(List<String> values) {
            addCriterion("KIND_LEVEL not in", values, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelBetween(String value1, String value2) {
            addCriterion("KIND_LEVEL between", value1, value2, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andKindLevelNotBetween(String value1, String value2) {
            addCriterion("KIND_LEVEL not between", value1, value2, "kindLevel");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeIsNull() {
            addCriterion("INSPECTION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeIsNotNull() {
            addCriterion("INSPECTION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeEqualTo(String value) {
            addCriterion("INSPECTION_CODE =", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeNotEqualTo(String value) {
            addCriterion("INSPECTION_CODE <>", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeGreaterThan(String value) {
            addCriterion("INSPECTION_CODE >", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("INSPECTION_CODE >=", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeLessThan(String value) {
            addCriterion("INSPECTION_CODE <", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeLessThanOrEqualTo(String value) {
            addCriterion("INSPECTION_CODE <=", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeLike(String value) {
            addCriterion("INSPECTION_CODE like", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeNotLike(String value) {
            addCriterion("INSPECTION_CODE not like", value, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeIn(List<String> values) {
            addCriterion("INSPECTION_CODE in", values, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeNotIn(List<String> values) {
            addCriterion("INSPECTION_CODE not in", values, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeBetween(String value1, String value2) {
            addCriterion("INSPECTION_CODE between", value1, value2, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeNotBetween(String value1, String value2) {
            addCriterion("INSPECTION_CODE not between", value1, value2, "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeIsNull() {
            addCriterion("INSULATION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeIsNotNull() {
            addCriterion("INSULATION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeEqualTo(String value) {
            addCriterion("INSULATION_CODE =", value, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeNotEqualTo(String value) {
            addCriterion("INSULATION_CODE <>", value, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeGreaterThan(String value) {
            addCriterion("INSULATION_CODE >", value, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("INSULATION_CODE >=", value, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeLessThan(String value) {
            addCriterion("INSULATION_CODE <", value, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeLessThanOrEqualTo(String value) {
            addCriterion("INSULATION_CODE <=", value, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeLike(String value) {
            addCriterion("INSULATION_CODE like", value, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeNotLike(String value) {
            addCriterion("INSULATION_CODE not like", value, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeIn(List<String> values) {
            addCriterion("INSULATION_CODE in", values, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeNotIn(List<String> values) {
            addCriterion("INSULATION_CODE not in", values, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeBetween(String value1, String value2) {
            addCriterion("INSULATION_CODE between", value1, value2, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeNotBetween(String value1, String value2) {
            addCriterion("INSULATION_CODE not between", value1, value2, "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationHighIsNull() {
            addCriterion("INSULATION_HIGH is null");
            return (Criteria) this;
        }

        public Criteria andInsulationHighIsNotNull() {
            addCriterion("INSULATION_HIGH is not null");
            return (Criteria) this;
        }

        public Criteria andInsulationHighEqualTo(String value) {
            addCriterion("INSULATION_HIGH =", value, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighNotEqualTo(String value) {
            addCriterion("INSULATION_HIGH <>", value, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighGreaterThan(String value) {
            addCriterion("INSULATION_HIGH >", value, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighGreaterThanOrEqualTo(String value) {
            addCriterion("INSULATION_HIGH >=", value, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighLessThan(String value) {
            addCriterion("INSULATION_HIGH <", value, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighLessThanOrEqualTo(String value) {
            addCriterion("INSULATION_HIGH <=", value, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighLike(String value) {
            addCriterion("INSULATION_HIGH like", value, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighNotLike(String value) {
            addCriterion("INSULATION_HIGH not like", value, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighIn(List<String> values) {
            addCriterion("INSULATION_HIGH in", values, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighNotIn(List<String> values) {
            addCriterion("INSULATION_HIGH not in", values, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighBetween(String value1, String value2) {
            addCriterion("INSULATION_HIGH between", value1, value2, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andInsulationHighNotBetween(String value1, String value2) {
            addCriterion("INSULATION_HIGH not between", value1, value2, "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andPaintCodeIsNull() {
            addCriterion("PAINT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPaintCodeIsNotNull() {
            addCriterion("PAINT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPaintCodeEqualTo(String value) {
            addCriterion("PAINT_CODE =", value, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeNotEqualTo(String value) {
            addCriterion("PAINT_CODE <>", value, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeGreaterThan(String value) {
            addCriterion("PAINT_CODE >", value, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAINT_CODE >=", value, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeLessThan(String value) {
            addCriterion("PAINT_CODE <", value, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeLessThanOrEqualTo(String value) {
            addCriterion("PAINT_CODE <=", value, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeLike(String value) {
            addCriterion("PAINT_CODE like", value, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeNotLike(String value) {
            addCriterion("PAINT_CODE not like", value, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeIn(List<String> values) {
            addCriterion("PAINT_CODE in", values, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeNotIn(List<String> values) {
            addCriterion("PAINT_CODE not in", values, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeBetween(String value1, String value2) {
            addCriterion("PAINT_CODE between", value1, value2, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPaintCodeNotBetween(String value1, String value2) {
            addCriterion("PAINT_CODE not between", value1, value2, "paintCode");
            return (Criteria) this;
        }

        public Criteria andPIDiagramIsNull() {
            addCriterion("P_I_DIAGRAM is null");
            return (Criteria) this;
        }

        public Criteria andPIDiagramIsNotNull() {
            addCriterion("P_I_DIAGRAM is not null");
            return (Criteria) this;
        }

        public Criteria andPIDiagramEqualTo(String value) {
            addCriterion("P_I_DIAGRAM =", value, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramNotEqualTo(String value) {
            addCriterion("P_I_DIAGRAM <>", value, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramGreaterThan(String value) {
            addCriterion("P_I_DIAGRAM >", value, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramGreaterThanOrEqualTo(String value) {
            addCriterion("P_I_DIAGRAM >=", value, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramLessThan(String value) {
            addCriterion("P_I_DIAGRAM <", value, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramLessThanOrEqualTo(String value) {
            addCriterion("P_I_DIAGRAM <=", value, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramLike(String value) {
            addCriterion("P_I_DIAGRAM like", value, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramNotLike(String value) {
            addCriterion("P_I_DIAGRAM not like", value, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramIn(List<String> values) {
            addCriterion("P_I_DIAGRAM in", values, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramNotIn(List<String> values) {
            addCriterion("P_I_DIAGRAM not in", values, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramBetween(String value1, String value2) {
            addCriterion("P_I_DIAGRAM between", value1, value2, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andPIDiagramNotBetween(String value1, String value2) {
            addCriterion("P_I_DIAGRAM not between", value1, value2, "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andTestPressureIsNull() {
            addCriterion("TEST_PRESSURE is null");
            return (Criteria) this;
        }

        public Criteria andTestPressureIsNotNull() {
            addCriterion("TEST_PRESSURE is not null");
            return (Criteria) this;
        }

        public Criteria andTestPressureEqualTo(String value) {
            addCriterion("TEST_PRESSURE =", value, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureNotEqualTo(String value) {
            addCriterion("TEST_PRESSURE <>", value, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureGreaterThan(String value) {
            addCriterion("TEST_PRESSURE >", value, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_PRESSURE >=", value, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureLessThan(String value) {
            addCriterion("TEST_PRESSURE <", value, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureLessThanOrEqualTo(String value) {
            addCriterion("TEST_PRESSURE <=", value, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureLike(String value) {
            addCriterion("TEST_PRESSURE like", value, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureNotLike(String value) {
            addCriterion("TEST_PRESSURE not like", value, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureIn(List<String> values) {
            addCriterion("TEST_PRESSURE in", values, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureNotIn(List<String> values) {
            addCriterion("TEST_PRESSURE not in", values, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureBetween(String value1, String value2) {
            addCriterion("TEST_PRESSURE between", value1, value2, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestPressureNotBetween(String value1, String value2) {
            addCriterion("TEST_PRESSURE not between", value1, value2, "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestMaterialIsNull() {
            addCriterion("TEST_MATERIAL is null");
            return (Criteria) this;
        }

        public Criteria andTestMaterialIsNotNull() {
            addCriterion("TEST_MATERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andTestMaterialEqualTo(String value) {
            addCriterion("TEST_MATERIAL =", value, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialNotEqualTo(String value) {
            addCriterion("TEST_MATERIAL <>", value, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialGreaterThan(String value) {
            addCriterion("TEST_MATERIAL >", value, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_MATERIAL >=", value, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialLessThan(String value) {
            addCriterion("TEST_MATERIAL <", value, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialLessThanOrEqualTo(String value) {
            addCriterion("TEST_MATERIAL <=", value, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialLike(String value) {
            addCriterion("TEST_MATERIAL like", value, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialNotLike(String value) {
            addCriterion("TEST_MATERIAL not like", value, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialIn(List<String> values) {
            addCriterion("TEST_MATERIAL in", values, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialNotIn(List<String> values) {
            addCriterion("TEST_MATERIAL not in", values, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialBetween(String value1, String value2) {
            addCriterion("TEST_MATERIAL between", value1, value2, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andTestMaterialNotBetween(String value1, String value2) {
            addCriterion("TEST_MATERIAL not between", value1, value2, "testMaterial");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeIsNull() {
            addCriterion("JACKETED_PIPE is null");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeIsNotNull() {
            addCriterion("JACKETED_PIPE is not null");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeEqualTo(String value) {
            addCriterion("JACKETED_PIPE =", value, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeNotEqualTo(String value) {
            addCriterion("JACKETED_PIPE <>", value, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeGreaterThan(String value) {
            addCriterion("JACKETED_PIPE >", value, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeGreaterThanOrEqualTo(String value) {
            addCriterion("JACKETED_PIPE >=", value, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeLessThan(String value) {
            addCriterion("JACKETED_PIPE <", value, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeLessThanOrEqualTo(String value) {
            addCriterion("JACKETED_PIPE <=", value, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeLike(String value) {
            addCriterion("JACKETED_PIPE like", value, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeNotLike(String value) {
            addCriterion("JACKETED_PIPE not like", value, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeIn(List<String> values) {
            addCriterion("JACKETED_PIPE in", values, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeNotIn(List<String> values) {
            addCriterion("JACKETED_PIPE not in", values, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeBetween(String value1, String value2) {
            addCriterion("JACKETED_PIPE between", value1, value2, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeNotBetween(String value1, String value2) {
            addCriterion("JACKETED_PIPE not between", value1, value2, "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andLineNumLikeInsensitive(String value) {
            addCriterion("upper(LINE_NUM) like", value.toUpperCase(), "lineNum");
            return (Criteria) this;
        }

        public Criteria andLineVersionLikeInsensitive(String value) {
            addCriterion("upper(LINE_VERSION) like", value.toUpperCase(), "lineVersion");
            return (Criteria) this;
        }

        public Criteria andSizeLikeInsensitive(String value) {
            addCriterion("upper(SIZE) like", value.toUpperCase(), "size");
            return (Criteria) this;
        }

        public Criteria andServLikeInsensitive(String value) {
            addCriterion("upper(SERV) like", value.toUpperCase(), "serv");
            return (Criteria) this;
        }

        public Criteria andClassSpecLikeInsensitive(String value) {
            addCriterion("upper(CLASS_SPEC) like", value.toUpperCase(), "classSpec");
            return (Criteria) this;
        }

        public Criteria andLineFromLikeInsensitive(String value) {
            addCriterion("upper(LINE_FROM) like", value.toUpperCase(), "lineFrom");
            return (Criteria) this;
        }

        public Criteria andLineToLikeInsensitive(String value) {
            addCriterion("upper(LINE_TO) like", value.toUpperCase(), "lineTo");
            return (Criteria) this;
        }

        public Criteria andOperatePressureLikeInsensitive(String value) {
            addCriterion("upper(OPERATE_PRESSURE) like", value.toUpperCase(), "operatePressure");
            return (Criteria) this;
        }

        public Criteria andOperateTemperatureLikeInsensitive(String value) {
            addCriterion("upper(OPERATE_TEMPERATURE) like", value.toUpperCase(), "operateTemperature");
            return (Criteria) this;
        }

        public Criteria andLineLevelLikeInsensitive(String value) {
            addCriterion("upper(LINE_LEVEL) like", value.toUpperCase(), "lineLevel");
            return (Criteria) this;
        }

        public Criteria andLineCodeLikeInsensitive(String value) {
            addCriterion("upper(LINE_CODE) like", value.toUpperCase(), "lineCode");
            return (Criteria) this;
        }

        public Criteria andDesignPressureLikeInsensitive(String value) {
            addCriterion("upper(DESIGN_PRESSURE) like", value.toUpperCase(), "designPressure");
            return (Criteria) this;
        }

        public Criteria andDesignTemperatureLikeInsensitive(String value) {
            addCriterion("upper(DESIGN_TEMPERATURE) like", value.toUpperCase(), "designTemperature");
            return (Criteria) this;
        }

        public Criteria andKindLevelLikeInsensitive(String value) {
            addCriterion("upper(KIND_LEVEL) like", value.toUpperCase(), "kindLevel");
            return (Criteria) this;
        }

        public Criteria andInspectionCodeLikeInsensitive(String value) {
            addCriterion("upper(INSPECTION_CODE) like", value.toUpperCase(), "inspectionCode");
            return (Criteria) this;
        }

        public Criteria andInsulationCodeLikeInsensitive(String value) {
            addCriterion("upper(INSULATION_CODE) like", value.toUpperCase(), "insulationCode");
            return (Criteria) this;
        }

        public Criteria andInsulationHighLikeInsensitive(String value) {
            addCriterion("upper(INSULATION_HIGH) like", value.toUpperCase(), "insulationHigh");
            return (Criteria) this;
        }

        public Criteria andPaintCodeLikeInsensitive(String value) {
            addCriterion("upper(PAINT_CODE) like", value.toUpperCase(), "paintCode");
            return (Criteria) this;
        }

        public Criteria andPIDiagramLikeInsensitive(String value) {
            addCriterion("upper(P_I_DIAGRAM) like", value.toUpperCase(), "pIDiagram");
            return (Criteria) this;
        }

        public Criteria andTestPressureLikeInsensitive(String value) {
            addCriterion("upper(TEST_PRESSURE) like", value.toUpperCase(), "testPressure");
            return (Criteria) this;
        }

        public Criteria andTestMaterialLikeInsensitive(String value) {
            addCriterion("upper(TEST_MATERIAL) like", value.toUpperCase(), "testMaterial");
            return (Criteria) this;
        }

        public Criteria andJacketedPipeLikeInsensitive(String value) {
            addCriterion("upper(JACKETED_PIPE) like", value.toUpperCase(), "jacketedPipe");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(REMARK) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_line
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 18 17:06:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 管道特性表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-18
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}