/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * PpLineWeldQueryHelper.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-23 Created
 */
package java;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PpLineWeldQueryHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public PpLineWeldQueryHelper() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 焊接记录表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-23
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPipeIdIsNull() {
            addCriterion("PIPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andPipeIdIsNotNull() {
            addCriterion("PIPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPipeIdEqualTo(Long value) {
            addCriterion("PIPE_ID =", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdNotEqualTo(Long value) {
            addCriterion("PIPE_ID <>", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdGreaterThan(Long value) {
            addCriterion("PIPE_ID >", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PIPE_ID >=", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdLessThan(Long value) {
            addCriterion("PIPE_ID <", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdLessThanOrEqualTo(Long value) {
            addCriterion("PIPE_ID <=", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdIn(List<Long> values) {
            addCriterion("PIPE_ID in", values, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdNotIn(List<Long> values) {
            addCriterion("PIPE_ID not in", values, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdBetween(Long value1, Long value2) {
            addCriterion("PIPE_ID between", value1, value2, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdNotBetween(Long value1, Long value2) {
            addCriterion("PIPE_ID not between", value1, value2, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPageCodeIsNull() {
            addCriterion("PAGE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPageCodeIsNotNull() {
            addCriterion("PAGE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPageCodeEqualTo(String value) {
            addCriterion("PAGE_CODE =", value, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeNotEqualTo(String value) {
            addCriterion("PAGE_CODE <>", value, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeGreaterThan(String value) {
            addCriterion("PAGE_CODE >", value, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAGE_CODE >=", value, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeLessThan(String value) {
            addCriterion("PAGE_CODE <", value, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeLessThanOrEqualTo(String value) {
            addCriterion("PAGE_CODE <=", value, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeLike(String value) {
            addCriterion("PAGE_CODE like", value, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeNotLike(String value) {
            addCriterion("PAGE_CODE not like", value, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeIn(List<String> values) {
            addCriterion("PAGE_CODE in", values, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeNotIn(List<String> values) {
            addCriterion("PAGE_CODE not in", values, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeBetween(String value1, String value2) {
            addCriterion("PAGE_CODE between", value1, value2, "pageCode");
            return (Criteria) this;
        }

        public Criteria andPageCodeNotBetween(String value1, String value2) {
            addCriterion("PAGE_CODE not between", value1, value2, "pageCode");
            return (Criteria) this;
        }

        public Criteria andJiontIsNull() {
            addCriterion("JIONT is null");
            return (Criteria) this;
        }

        public Criteria andJiontIsNotNull() {
            addCriterion("JIONT is not null");
            return (Criteria) this;
        }

        public Criteria andJiontEqualTo(String value) {
            addCriterion("JIONT =", value, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontNotEqualTo(String value) {
            addCriterion("JIONT <>", value, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontGreaterThan(String value) {
            addCriterion("JIONT >", value, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontGreaterThanOrEqualTo(String value) {
            addCriterion("JIONT >=", value, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontLessThan(String value) {
            addCriterion("JIONT <", value, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontLessThanOrEqualTo(String value) {
            addCriterion("JIONT <=", value, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontLike(String value) {
            addCriterion("JIONT like", value, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontNotLike(String value) {
            addCriterion("JIONT not like", value, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontIn(List<String> values) {
            addCriterion("JIONT in", values, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontNotIn(List<String> values) {
            addCriterion("JIONT not in", values, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontBetween(String value1, String value2) {
            addCriterion("JIONT between", value1, value2, "jiont");
            return (Criteria) this;
        }

        public Criteria andJiontNotBetween(String value1, String value2) {
            addCriterion("JIONT not between", value1, value2, "jiont");
            return (Criteria) this;
        }

        public Criteria andWpsnoIsNull() {
            addCriterion("WPSNO is null");
            return (Criteria) this;
        }

        public Criteria andWpsnoIsNotNull() {
            addCriterion("WPSNO is not null");
            return (Criteria) this;
        }

        public Criteria andWpsnoEqualTo(String value) {
            addCriterion("WPSNO =", value, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoNotEqualTo(String value) {
            addCriterion("WPSNO <>", value, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoGreaterThan(String value) {
            addCriterion("WPSNO >", value, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoGreaterThanOrEqualTo(String value) {
            addCriterion("WPSNO >=", value, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoLessThan(String value) {
            addCriterion("WPSNO <", value, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoLessThanOrEqualTo(String value) {
            addCriterion("WPSNO <=", value, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoLike(String value) {
            addCriterion("WPSNO like", value, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoNotLike(String value) {
            addCriterion("WPSNO not like", value, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoIn(List<String> values) {
            addCriterion("WPSNO in", values, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoNotIn(List<String> values) {
            addCriterion("WPSNO not in", values, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoBetween(String value1, String value2) {
            addCriterion("WPSNO between", value1, value2, "wpsno");
            return (Criteria) this;
        }

        public Criteria andWpsnoNotBetween(String value1, String value2) {
            addCriterion("WPSNO not between", value1, value2, "wpsno");
            return (Criteria) this;
        }

        public Criteria andJlocationIsNull() {
            addCriterion("JLOCATION is null");
            return (Criteria) this;
        }

        public Criteria andJlocationIsNotNull() {
            addCriterion("JLOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andJlocationEqualTo(String value) {
            addCriterion("JLOCATION =", value, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationNotEqualTo(String value) {
            addCriterion("JLOCATION <>", value, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationGreaterThan(String value) {
            addCriterion("JLOCATION >", value, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationGreaterThanOrEqualTo(String value) {
            addCriterion("JLOCATION >=", value, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationLessThan(String value) {
            addCriterion("JLOCATION <", value, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationLessThanOrEqualTo(String value) {
            addCriterion("JLOCATION <=", value, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationLike(String value) {
            addCriterion("JLOCATION like", value, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationNotLike(String value) {
            addCriterion("JLOCATION not like", value, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationIn(List<String> values) {
            addCriterion("JLOCATION in", values, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationNotIn(List<String> values) {
            addCriterion("JLOCATION not in", values, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationBetween(String value1, String value2) {
            addCriterion("JLOCATION between", value1, value2, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJlocationNotBetween(String value1, String value2) {
            addCriterion("JLOCATION not between", value1, value2, "jlocation");
            return (Criteria) this;
        }

        public Criteria andJclassIsNull() {
            addCriterion("JCLASS is null");
            return (Criteria) this;
        }

        public Criteria andJclassIsNotNull() {
            addCriterion("JCLASS is not null");
            return (Criteria) this;
        }

        public Criteria andJclassEqualTo(String value) {
            addCriterion("JCLASS =", value, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassNotEqualTo(String value) {
            addCriterion("JCLASS <>", value, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassGreaterThan(String value) {
            addCriterion("JCLASS >", value, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassGreaterThanOrEqualTo(String value) {
            addCriterion("JCLASS >=", value, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassLessThan(String value) {
            addCriterion("JCLASS <", value, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassLessThanOrEqualTo(String value) {
            addCriterion("JCLASS <=", value, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassLike(String value) {
            addCriterion("JCLASS like", value, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassNotLike(String value) {
            addCriterion("JCLASS not like", value, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassIn(List<String> values) {
            addCriterion("JCLASS in", values, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassNotIn(List<String> values) {
            addCriterion("JCLASS not in", values, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassBetween(String value1, String value2) {
            addCriterion("JCLASS between", value1, value2, "jclass");
            return (Criteria) this;
        }

        public Criteria andJclassNotBetween(String value1, String value2) {
            addCriterion("JCLASS not between", value1, value2, "jclass");
            return (Criteria) this;
        }

        public Criteria andFinishDateIsNull() {
            addCriterion("FINISH_DATE is null");
            return (Criteria) this;
        }

        public Criteria andFinishDateIsNotNull() {
            addCriterion("FINISH_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andFinishDateEqualTo(Date value) {
            addCriterionForJDBCDate("FINISH_DATE =", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("FINISH_DATE <>", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateGreaterThan(Date value) {
            addCriterionForJDBCDate("FINISH_DATE >", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FINISH_DATE >=", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateLessThan(Date value) {
            addCriterionForJDBCDate("FINISH_DATE <", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FINISH_DATE <=", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateIn(List<Date> values) {
            addCriterionForJDBCDate("FINISH_DATE in", values, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("FINISH_DATE not in", values, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FINISH_DATE between", value1, value2, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FINISH_DATE not between", value1, value2, "finishDate");
            return (Criteria) this;
        }

        public Criteria andJsizeIsNull() {
            addCriterion("JSIZE is null");
            return (Criteria) this;
        }

        public Criteria andJsizeIsNotNull() {
            addCriterion("JSIZE is not null");
            return (Criteria) this;
        }

        public Criteria andJsizeEqualTo(String value) {
            addCriterion("JSIZE =", value, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeNotEqualTo(String value) {
            addCriterion("JSIZE <>", value, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeGreaterThan(String value) {
            addCriterion("JSIZE >", value, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeGreaterThanOrEqualTo(String value) {
            addCriterion("JSIZE >=", value, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeLessThan(String value) {
            addCriterion("JSIZE <", value, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeLessThanOrEqualTo(String value) {
            addCriterion("JSIZE <=", value, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeLike(String value) {
            addCriterion("JSIZE like", value, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeNotLike(String value) {
            addCriterion("JSIZE not like", value, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeIn(List<String> values) {
            addCriterion("JSIZE in", values, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeNotIn(List<String> values) {
            addCriterion("JSIZE not in", values, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeBetween(String value1, String value2) {
            addCriterion("JSIZE between", value1, value2, "jsize");
            return (Criteria) this;
        }

        public Criteria andJsizeNotBetween(String value1, String value2) {
            addCriterion("JSIZE not between", value1, value2, "jsize");
            return (Criteria) this;
        }

        public Criteria andThicknessIsNull() {
            addCriterion("THICKNESS is null");
            return (Criteria) this;
        }

        public Criteria andThicknessIsNotNull() {
            addCriterion("THICKNESS is not null");
            return (Criteria) this;
        }

        public Criteria andThicknessEqualTo(String value) {
            addCriterion("THICKNESS =", value, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessNotEqualTo(String value) {
            addCriterion("THICKNESS <>", value, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessGreaterThan(String value) {
            addCriterion("THICKNESS >", value, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessGreaterThanOrEqualTo(String value) {
            addCriterion("THICKNESS >=", value, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessLessThan(String value) {
            addCriterion("THICKNESS <", value, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessLessThanOrEqualTo(String value) {
            addCriterion("THICKNESS <=", value, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessLike(String value) {
            addCriterion("THICKNESS like", value, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessNotLike(String value) {
            addCriterion("THICKNESS not like", value, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessIn(List<String> values) {
            addCriterion("THICKNESS in", values, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessNotIn(List<String> values) {
            addCriterion("THICKNESS not in", values, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessBetween(String value1, String value2) {
            addCriterion("THICKNESS between", value1, value2, "thickness");
            return (Criteria) this;
        }

        public Criteria andThicknessNotBetween(String value1, String value2) {
            addCriterion("THICKNESS not between", value1, value2, "thickness");
            return (Criteria) this;
        }

        public Criteria andJtypeIsNull() {
            addCriterion("JTYPE is null");
            return (Criteria) this;
        }

        public Criteria andJtypeIsNotNull() {
            addCriterion("JTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andJtypeEqualTo(String value) {
            addCriterion("JTYPE =", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeNotEqualTo(String value) {
            addCriterion("JTYPE <>", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeGreaterThan(String value) {
            addCriterion("JTYPE >", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeGreaterThanOrEqualTo(String value) {
            addCriterion("JTYPE >=", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeLessThan(String value) {
            addCriterion("JTYPE <", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeLessThanOrEqualTo(String value) {
            addCriterion("JTYPE <=", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeLike(String value) {
            addCriterion("JTYPE like", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeNotLike(String value) {
            addCriterion("JTYPE not like", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeIn(List<String> values) {
            addCriterion("JTYPE in", values, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeNotIn(List<String> values) {
            addCriterion("JTYPE not in", values, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeBetween(String value1, String value2) {
            addCriterion("JTYPE between", value1, value2, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeNotBetween(String value1, String value2) {
            addCriterion("JTYPE not between", value1, value2, "jtype");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessIsNull() {
            addCriterion("WELDING_PROCESS is null");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessIsNotNull() {
            addCriterion("WELDING_PROCESS is not null");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessEqualTo(String value) {
            addCriterion("WELDING_PROCESS =", value, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessNotEqualTo(String value) {
            addCriterion("WELDING_PROCESS <>", value, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessGreaterThan(String value) {
            addCriterion("WELDING_PROCESS >", value, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessGreaterThanOrEqualTo(String value) {
            addCriterion("WELDING_PROCESS >=", value, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessLessThan(String value) {
            addCriterion("WELDING_PROCESS <", value, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessLessThanOrEqualTo(String value) {
            addCriterion("WELDING_PROCESS <=", value, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessLike(String value) {
            addCriterion("WELDING_PROCESS like", value, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessNotLike(String value) {
            addCriterion("WELDING_PROCESS not like", value, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessIn(List<String> values) {
            addCriterion("WELDING_PROCESS in", values, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessNotIn(List<String> values) {
            addCriterion("WELDING_PROCESS not in", values, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessBetween(String value1, String value2) {
            addCriterion("WELDING_PROCESS between", value1, value2, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessNotBetween(String value1, String value2) {
            addCriterion("WELDING_PROCESS not between", value1, value2, "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andFixedRotatIsNull() {
            addCriterion("FIXED_ROTAT is null");
            return (Criteria) this;
        }

        public Criteria andFixedRotatIsNotNull() {
            addCriterion("FIXED_ROTAT is not null");
            return (Criteria) this;
        }

        public Criteria andFixedRotatEqualTo(String value) {
            addCriterion("FIXED_ROTAT =", value, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatNotEqualTo(String value) {
            addCriterion("FIXED_ROTAT <>", value, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatGreaterThan(String value) {
            addCriterion("FIXED_ROTAT >", value, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatGreaterThanOrEqualTo(String value) {
            addCriterion("FIXED_ROTAT >=", value, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatLessThan(String value) {
            addCriterion("FIXED_ROTAT <", value, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatLessThanOrEqualTo(String value) {
            addCriterion("FIXED_ROTAT <=", value, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatLike(String value) {
            addCriterion("FIXED_ROTAT like", value, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatNotLike(String value) {
            addCriterion("FIXED_ROTAT not like", value, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatIn(List<String> values) {
            addCriterion("FIXED_ROTAT in", values, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatNotIn(List<String> values) {
            addCriterion("FIXED_ROTAT not in", values, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatBetween(String value1, String value2) {
            addCriterion("FIXED_ROTAT between", value1, value2, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andFixedRotatNotBetween(String value1, String value2) {
            addCriterion("FIXED_ROTAT not between", value1, value2, "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andRootWelderIsNull() {
            addCriterion("ROOT_WELDER is null");
            return (Criteria) this;
        }

        public Criteria andRootWelderIsNotNull() {
            addCriterion("ROOT_WELDER is not null");
            return (Criteria) this;
        }

        public Criteria andRootWelderEqualTo(String value) {
            addCriterion("ROOT_WELDER =", value, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderNotEqualTo(String value) {
            addCriterion("ROOT_WELDER <>", value, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderGreaterThan(String value) {
            addCriterion("ROOT_WELDER >", value, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderGreaterThanOrEqualTo(String value) {
            addCriterion("ROOT_WELDER >=", value, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderLessThan(String value) {
            addCriterion("ROOT_WELDER <", value, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderLessThanOrEqualTo(String value) {
            addCriterion("ROOT_WELDER <=", value, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderLike(String value) {
            addCriterion("ROOT_WELDER like", value, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderNotLike(String value) {
            addCriterion("ROOT_WELDER not like", value, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderIn(List<String> values) {
            addCriterion("ROOT_WELDER in", values, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderNotIn(List<String> values) {
            addCriterion("ROOT_WELDER not in", values, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderBetween(String value1, String value2) {
            addCriterion("ROOT_WELDER between", value1, value2, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andRootWelderNotBetween(String value1, String value2) {
            addCriterion("ROOT_WELDER not between", value1, value2, "rootWelder");
            return (Criteria) this;
        }

        public Criteria andExamitemIsNull() {
            addCriterion("EXAMITEM is null");
            return (Criteria) this;
        }

        public Criteria andExamitemIsNotNull() {
            addCriterion("EXAMITEM is not null");
            return (Criteria) this;
        }

        public Criteria andExamitemEqualTo(String value) {
            addCriterion("EXAMITEM =", value, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemNotEqualTo(String value) {
            addCriterion("EXAMITEM <>", value, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemGreaterThan(String value) {
            addCriterion("EXAMITEM >", value, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemGreaterThanOrEqualTo(String value) {
            addCriterion("EXAMITEM >=", value, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemLessThan(String value) {
            addCriterion("EXAMITEM <", value, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemLessThanOrEqualTo(String value) {
            addCriterion("EXAMITEM <=", value, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemLike(String value) {
            addCriterion("EXAMITEM like", value, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemNotLike(String value) {
            addCriterion("EXAMITEM not like", value, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemIn(List<String> values) {
            addCriterion("EXAMITEM in", values, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemNotIn(List<String> values) {
            addCriterion("EXAMITEM not in", values, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemBetween(String value1, String value2) {
            addCriterion("EXAMITEM between", value1, value2, "examitem");
            return (Criteria) this;
        }

        public Criteria andExamitemNotBetween(String value1, String value2) {
            addCriterion("EXAMITEM not between", value1, value2, "examitem");
            return (Criteria) this;
        }

        public Criteria andCoverWelderIsNull() {
            addCriterion("COVER_WELDER is null");
            return (Criteria) this;
        }

        public Criteria andCoverWelderIsNotNull() {
            addCriterion("COVER_WELDER is not null");
            return (Criteria) this;
        }

        public Criteria andCoverWelderEqualTo(String value) {
            addCriterion("COVER_WELDER =", value, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderNotEqualTo(String value) {
            addCriterion("COVER_WELDER <>", value, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderGreaterThan(String value) {
            addCriterion("COVER_WELDER >", value, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderGreaterThanOrEqualTo(String value) {
            addCriterion("COVER_WELDER >=", value, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderLessThan(String value) {
            addCriterion("COVER_WELDER <", value, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderLessThanOrEqualTo(String value) {
            addCriterion("COVER_WELDER <=", value, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderLike(String value) {
            addCriterion("COVER_WELDER like", value, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderNotLike(String value) {
            addCriterion("COVER_WELDER not like", value, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderIn(List<String> values) {
            addCriterion("COVER_WELDER in", values, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderNotIn(List<String> values) {
            addCriterion("COVER_WELDER not in", values, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderBetween(String value1, String value2) {
            addCriterion("COVER_WELDER between", value1, value2, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andCoverWelderNotBetween(String value1, String value2) {
            addCriterion("COVER_WELDER not between", value1, value2, "coverWelder");
            return (Criteria) this;
        }

        public Criteria andVisualIsNull() {
            addCriterion("VISUAL is null");
            return (Criteria) this;
        }

        public Criteria andVisualIsNotNull() {
            addCriterion("VISUAL is not null");
            return (Criteria) this;
        }

        public Criteria andVisualEqualTo(Long value) {
            addCriterion("VISUAL =", value, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualNotEqualTo(Long value) {
            addCriterion("VISUAL <>", value, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualGreaterThan(Long value) {
            addCriterion("VISUAL >", value, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualGreaterThanOrEqualTo(Long value) {
            addCriterion("VISUAL >=", value, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualLessThan(Long value) {
            addCriterion("VISUAL <", value, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualLessThanOrEqualTo(Long value) {
            addCriterion("VISUAL <=", value, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualIn(List<Long> values) {
            addCriterion("VISUAL in", values, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualNotIn(List<Long> values) {
            addCriterion("VISUAL not in", values, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualBetween(Long value1, Long value2) {
            addCriterion("VISUAL between", value1, value2, "visual");
            return (Criteria) this;
        }

        public Criteria andVisualNotBetween(Long value1, Long value2) {
            addCriterion("VISUAL not between", value1, value2, "visual");
            return (Criteria) this;
        }

        public Criteria andPieceNo1IsNull() {
            addCriterion("PIECE_NO1 is null");
            return (Criteria) this;
        }

        public Criteria andPieceNo1IsNotNull() {
            addCriterion("PIECE_NO1 is not null");
            return (Criteria) this;
        }

        public Criteria andPieceNo1EqualTo(String value) {
            addCriterion("PIECE_NO1 =", value, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1NotEqualTo(String value) {
            addCriterion("PIECE_NO1 <>", value, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1GreaterThan(String value) {
            addCriterion("PIECE_NO1 >", value, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1GreaterThanOrEqualTo(String value) {
            addCriterion("PIECE_NO1 >=", value, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1LessThan(String value) {
            addCriterion("PIECE_NO1 <", value, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1LessThanOrEqualTo(String value) {
            addCriterion("PIECE_NO1 <=", value, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1Like(String value) {
            addCriterion("PIECE_NO1 like", value, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1NotLike(String value) {
            addCriterion("PIECE_NO1 not like", value, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1In(List<String> values) {
            addCriterion("PIECE_NO1 in", values, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1NotIn(List<String> values) {
            addCriterion("PIECE_NO1 not in", values, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1Between(String value1, String value2) {
            addCriterion("PIECE_NO1 between", value1, value2, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andPieceNo1NotBetween(String value1, String value2) {
            addCriterion("PIECE_NO1 not between", value1, value2, "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialIsNull() {
            addCriterion("WELDING_MATIAL is null");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialIsNotNull() {
            addCriterion("WELDING_MATIAL is not null");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialEqualTo(String value) {
            addCriterion("WELDING_MATIAL =", value, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialNotEqualTo(String value) {
            addCriterion("WELDING_MATIAL <>", value, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialGreaterThan(String value) {
            addCriterion("WELDING_MATIAL >", value, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialGreaterThanOrEqualTo(String value) {
            addCriterion("WELDING_MATIAL >=", value, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialLessThan(String value) {
            addCriterion("WELDING_MATIAL <", value, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialLessThanOrEqualTo(String value) {
            addCriterion("WELDING_MATIAL <=", value, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialLike(String value) {
            addCriterion("WELDING_MATIAL like", value, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialNotLike(String value) {
            addCriterion("WELDING_MATIAL not like", value, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialIn(List<String> values) {
            addCriterion("WELDING_MATIAL in", values, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialNotIn(List<String> values) {
            addCriterion("WELDING_MATIAL not in", values, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialBetween(String value1, String value2) {
            addCriterion("WELDING_MATIAL between", value1, value2, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialNotBetween(String value1, String value2) {
            addCriterion("WELDING_MATIAL not between", value1, value2, "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andPieceNo2IsNull() {
            addCriterion("PIECE_NO2 is null");
            return (Criteria) this;
        }

        public Criteria andPieceNo2IsNotNull() {
            addCriterion("PIECE_NO2 is not null");
            return (Criteria) this;
        }

        public Criteria andPieceNo2EqualTo(String value) {
            addCriterion("PIECE_NO2 =", value, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2NotEqualTo(String value) {
            addCriterion("PIECE_NO2 <>", value, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2GreaterThan(String value) {
            addCriterion("PIECE_NO2 >", value, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2GreaterThanOrEqualTo(String value) {
            addCriterion("PIECE_NO2 >=", value, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2LessThan(String value) {
            addCriterion("PIECE_NO2 <", value, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2LessThanOrEqualTo(String value) {
            addCriterion("PIECE_NO2 <=", value, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2Like(String value) {
            addCriterion("PIECE_NO2 like", value, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2NotLike(String value) {
            addCriterion("PIECE_NO2 not like", value, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2In(List<String> values) {
            addCriterion("PIECE_NO2 in", values, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2NotIn(List<String> values) {
            addCriterion("PIECE_NO2 not in", values, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2Between(String value1, String value2) {
            addCriterion("PIECE_NO2 between", value1, value2, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andPieceNo2NotBetween(String value1, String value2) {
            addCriterion("PIECE_NO2 not between", value1, value2, "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo1IsNull() {
            addCriterion("HEAT_NO1 is null");
            return (Criteria) this;
        }

        public Criteria andHeatNo1IsNotNull() {
            addCriterion("HEAT_NO1 is not null");
            return (Criteria) this;
        }

        public Criteria andHeatNo1EqualTo(String value) {
            addCriterion("HEAT_NO1 =", value, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1NotEqualTo(String value) {
            addCriterion("HEAT_NO1 <>", value, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1GreaterThan(String value) {
            addCriterion("HEAT_NO1 >", value, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1GreaterThanOrEqualTo(String value) {
            addCriterion("HEAT_NO1 >=", value, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1LessThan(String value) {
            addCriterion("HEAT_NO1 <", value, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1LessThanOrEqualTo(String value) {
            addCriterion("HEAT_NO1 <=", value, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1Like(String value) {
            addCriterion("HEAT_NO1 like", value, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1NotLike(String value) {
            addCriterion("HEAT_NO1 not like", value, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1In(List<String> values) {
            addCriterion("HEAT_NO1 in", values, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1NotIn(List<String> values) {
            addCriterion("HEAT_NO1 not in", values, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1Between(String value1, String value2) {
            addCriterion("HEAT_NO1 between", value1, value2, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo1NotBetween(String value1, String value2) {
            addCriterion("HEAT_NO1 not between", value1, value2, "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo2IsNull() {
            addCriterion("HEAT_NO2 is null");
            return (Criteria) this;
        }

        public Criteria andHeatNo2IsNotNull() {
            addCriterion("HEAT_NO2 is not null");
            return (Criteria) this;
        }

        public Criteria andHeatNo2EqualTo(String value) {
            addCriterion("HEAT_NO2 =", value, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2NotEqualTo(String value) {
            addCriterion("HEAT_NO2 <>", value, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2GreaterThan(String value) {
            addCriterion("HEAT_NO2 >", value, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2GreaterThanOrEqualTo(String value) {
            addCriterion("HEAT_NO2 >=", value, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2LessThan(String value) {
            addCriterion("HEAT_NO2 <", value, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2LessThanOrEqualTo(String value) {
            addCriterion("HEAT_NO2 <=", value, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2Like(String value) {
            addCriterion("HEAT_NO2 like", value, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2NotLike(String value) {
            addCriterion("HEAT_NO2 not like", value, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2In(List<String> values) {
            addCriterion("HEAT_NO2 in", values, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2NotIn(List<String> values) {
            addCriterion("HEAT_NO2 not in", values, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2Between(String value1, String value2) {
            addCriterion("HEAT_NO2 between", value1, value2, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo2NotBetween(String value1, String value2) {
            addCriterion("HEAT_NO2 not between", value1, value2, "heatNo2");
            return (Criteria) this;
        }

        public Criteria andAlterCodeIsNull() {
            addCriterion("ALTER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAlterCodeIsNotNull() {
            addCriterion("ALTER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAlterCodeEqualTo(String value) {
            addCriterion("ALTER_CODE =", value, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeNotEqualTo(String value) {
            addCriterion("ALTER_CODE <>", value, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeGreaterThan(String value) {
            addCriterion("ALTER_CODE >", value, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ALTER_CODE >=", value, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeLessThan(String value) {
            addCriterion("ALTER_CODE <", value, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeLessThanOrEqualTo(String value) {
            addCriterion("ALTER_CODE <=", value, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeLike(String value) {
            addCriterion("ALTER_CODE like", value, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeNotLike(String value) {
            addCriterion("ALTER_CODE not like", value, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeIn(List<String> values) {
            addCriterion("ALTER_CODE in", values, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeNotIn(List<String> values) {
            addCriterion("ALTER_CODE not in", values, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeBetween(String value1, String value2) {
            addCriterion("ALTER_CODE between", value1, value2, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterCodeNotBetween(String value1, String value2) {
            addCriterion("ALTER_CODE not between", value1, value2, "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterTypeIsNull() {
            addCriterion("ALTER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAlterTypeIsNotNull() {
            addCriterion("ALTER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAlterTypeEqualTo(String value) {
            addCriterion("ALTER_TYPE =", value, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeNotEqualTo(String value) {
            addCriterion("ALTER_TYPE <>", value, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeGreaterThan(String value) {
            addCriterion("ALTER_TYPE >", value, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ALTER_TYPE >=", value, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeLessThan(String value) {
            addCriterion("ALTER_TYPE <", value, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeLessThanOrEqualTo(String value) {
            addCriterion("ALTER_TYPE <=", value, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeLike(String value) {
            addCriterion("ALTER_TYPE like", value, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeNotLike(String value) {
            addCriterion("ALTER_TYPE not like", value, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeIn(List<String> values) {
            addCriterion("ALTER_TYPE in", values, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeNotIn(List<String> values) {
            addCriterion("ALTER_TYPE not in", values, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeBetween(String value1, String value2) {
            addCriterion("ALTER_TYPE between", value1, value2, "alterType");
            return (Criteria) this;
        }

        public Criteria andAlterTypeNotBetween(String value1, String value2) {
            addCriterion("ALTER_TYPE not between", value1, value2, "alterType");
            return (Criteria) this;
        }

        public Criteria andDailyNoIsNull() {
            addCriterion("DAILY_NO is null");
            return (Criteria) this;
        }

        public Criteria andDailyNoIsNotNull() {
            addCriterion("DAILY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andDailyNoEqualTo(String value) {
            addCriterion("DAILY_NO =", value, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoNotEqualTo(String value) {
            addCriterion("DAILY_NO <>", value, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoGreaterThan(String value) {
            addCriterion("DAILY_NO >", value, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoGreaterThanOrEqualTo(String value) {
            addCriterion("DAILY_NO >=", value, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoLessThan(String value) {
            addCriterion("DAILY_NO <", value, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoLessThanOrEqualTo(String value) {
            addCriterion("DAILY_NO <=", value, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoLike(String value) {
            addCriterion("DAILY_NO like", value, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoNotLike(String value) {
            addCriterion("DAILY_NO not like", value, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoIn(List<String> values) {
            addCriterion("DAILY_NO in", values, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoNotIn(List<String> values) {
            addCriterion("DAILY_NO not in", values, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoBetween(String value1, String value2) {
            addCriterion("DAILY_NO between", value1, value2, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andDailyNoNotBetween(String value1, String value2) {
            addCriterion("DAILY_NO not between", value1, value2, "dailyNo");
            return (Criteria) this;
        }

        public Criteria andHardessRecIsNull() {
            addCriterion("HARDESS_REC is null");
            return (Criteria) this;
        }

        public Criteria andHardessRecIsNotNull() {
            addCriterion("HARDESS_REC is not null");
            return (Criteria) this;
        }

        public Criteria andHardessRecEqualTo(String value) {
            addCriterion("HARDESS_REC =", value, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecNotEqualTo(String value) {
            addCriterion("HARDESS_REC <>", value, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecGreaterThan(String value) {
            addCriterion("HARDESS_REC >", value, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecGreaterThanOrEqualTo(String value) {
            addCriterion("HARDESS_REC >=", value, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecLessThan(String value) {
            addCriterion("HARDESS_REC <", value, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecLessThanOrEqualTo(String value) {
            addCriterion("HARDESS_REC <=", value, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecLike(String value) {
            addCriterion("HARDESS_REC like", value, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecNotLike(String value) {
            addCriterion("HARDESS_REC not like", value, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecIn(List<String> values) {
            addCriterion("HARDESS_REC in", values, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecNotIn(List<String> values) {
            addCriterion("HARDESS_REC not in", values, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecBetween(String value1, String value2) {
            addCriterion("HARDESS_REC between", value1, value2, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHardessRecNotBetween(String value1, String value2) {
            addCriterion("HARDESS_REC not between", value1, value2, "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecIsNull() {
            addCriterion("HEAT_REC is null");
            return (Criteria) this;
        }

        public Criteria andHeatRecIsNotNull() {
            addCriterion("HEAT_REC is not null");
            return (Criteria) this;
        }

        public Criteria andHeatRecEqualTo(String value) {
            addCriterion("HEAT_REC =", value, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecNotEqualTo(String value) {
            addCriterion("HEAT_REC <>", value, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecGreaterThan(String value) {
            addCriterion("HEAT_REC >", value, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecGreaterThanOrEqualTo(String value) {
            addCriterion("HEAT_REC >=", value, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecLessThan(String value) {
            addCriterion("HEAT_REC <", value, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecLessThanOrEqualTo(String value) {
            addCriterion("HEAT_REC <=", value, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecLike(String value) {
            addCriterion("HEAT_REC like", value, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecNotLike(String value) {
            addCriterion("HEAT_REC not like", value, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecIn(List<String> values) {
            addCriterion("HEAT_REC in", values, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecNotIn(List<String> values) {
            addCriterion("HEAT_REC not in", values, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecBetween(String value1, String value2) {
            addCriterion("HEAT_REC between", value1, value2, "heatRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecNotBetween(String value1, String value2) {
            addCriterion("HEAT_REC not between", value1, value2, "heatRec");
            return (Criteria) this;
        }

        public Criteria andRtLotIsNull() {
            addCriterion("RT_LOT is null");
            return (Criteria) this;
        }

        public Criteria andRtLotIsNotNull() {
            addCriterion("RT_LOT is not null");
            return (Criteria) this;
        }

        public Criteria andRtLotEqualTo(String value) {
            addCriterion("RT_LOT =", value, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotNotEqualTo(String value) {
            addCriterion("RT_LOT <>", value, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotGreaterThan(String value) {
            addCriterion("RT_LOT >", value, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotGreaterThanOrEqualTo(String value) {
            addCriterion("RT_LOT >=", value, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotLessThan(String value) {
            addCriterion("RT_LOT <", value, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotLessThanOrEqualTo(String value) {
            addCriterion("RT_LOT <=", value, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotLike(String value) {
            addCriterion("RT_LOT like", value, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotNotLike(String value) {
            addCriterion("RT_LOT not like", value, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotIn(List<String> values) {
            addCriterion("RT_LOT in", values, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotNotIn(List<String> values) {
            addCriterion("RT_LOT not in", values, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotBetween(String value1, String value2) {
            addCriterion("RT_LOT between", value1, value2, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtLotNotBetween(String value1, String value2) {
            addCriterion("RT_LOT not between", value1, value2, "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtSampleIsNull() {
            addCriterion("RT_SAMPLE is null");
            return (Criteria) this;
        }

        public Criteria andRtSampleIsNotNull() {
            addCriterion("RT_SAMPLE is not null");
            return (Criteria) this;
        }

        public Criteria andRtSampleEqualTo(String value) {
            addCriterion("RT_SAMPLE =", value, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleNotEqualTo(String value) {
            addCriterion("RT_SAMPLE <>", value, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleGreaterThan(String value) {
            addCriterion("RT_SAMPLE >", value, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleGreaterThanOrEqualTo(String value) {
            addCriterion("RT_SAMPLE >=", value, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleLessThan(String value) {
            addCriterion("RT_SAMPLE <", value, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleLessThanOrEqualTo(String value) {
            addCriterion("RT_SAMPLE <=", value, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleLike(String value) {
            addCriterion("RT_SAMPLE like", value, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleNotLike(String value) {
            addCriterion("RT_SAMPLE not like", value, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleIn(List<String> values) {
            addCriterion("RT_SAMPLE in", values, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleNotIn(List<String> values) {
            addCriterion("RT_SAMPLE not in", values, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleBetween(String value1, String value2) {
            addCriterion("RT_SAMPLE between", value1, value2, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRtSampleNotBetween(String value1, String value2) {
            addCriterion("RT_SAMPLE not between", value1, value2, "rtSample");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andPageCodeLikeInsensitive(String value) {
            addCriterion("upper(PAGE_CODE) like", value.toUpperCase(), "pageCode");
            return (Criteria) this;
        }

        public Criteria andJiontLikeInsensitive(String value) {
            addCriterion("upper(JIONT) like", value.toUpperCase(), "jiont");
            return (Criteria) this;
        }

        public Criteria andWpsnoLikeInsensitive(String value) {
            addCriterion("upper(WPSNO) like", value.toUpperCase(), "wpsno");
            return (Criteria) this;
        }

        public Criteria andJlocationLikeInsensitive(String value) {
            addCriterion("upper(JLOCATION) like", value.toUpperCase(), "jlocation");
            return (Criteria) this;
        }

        public Criteria andJclassLikeInsensitive(String value) {
            addCriterion("upper(JCLASS) like", value.toUpperCase(), "jclass");
            return (Criteria) this;
        }

        public Criteria andJsizeLikeInsensitive(String value) {
            addCriterion("upper(JSIZE) like", value.toUpperCase(), "jsize");
            return (Criteria) this;
        }

        public Criteria andThicknessLikeInsensitive(String value) {
            addCriterion("upper(THICKNESS) like", value.toUpperCase(), "thickness");
            return (Criteria) this;
        }

        public Criteria andJtypeLikeInsensitive(String value) {
            addCriterion("upper(JTYPE) like", value.toUpperCase(), "jtype");
            return (Criteria) this;
        }

        public Criteria andWeldingProcessLikeInsensitive(String value) {
            addCriterion("upper(WELDING_PROCESS) like", value.toUpperCase(), "weldingProcess");
            return (Criteria) this;
        }

        public Criteria andFixedRotatLikeInsensitive(String value) {
            addCriterion("upper(FIXED_ROTAT) like", value.toUpperCase(), "fixedRotat");
            return (Criteria) this;
        }

        public Criteria andRootWelderLikeInsensitive(String value) {
            addCriterion("upper(ROOT_WELDER) like", value.toUpperCase(), "rootWelder");
            return (Criteria) this;
        }

        public Criteria andExamitemLikeInsensitive(String value) {
            addCriterion("upper(EXAMITEM) like", value.toUpperCase(), "examitem");
            return (Criteria) this;
        }

        public Criteria andCoverWelderLikeInsensitive(String value) {
            addCriterion("upper(COVER_WELDER) like", value.toUpperCase(), "coverWelder");
            return (Criteria) this;
        }

        public Criteria andPieceNo1LikeInsensitive(String value) {
            addCriterion("upper(PIECE_NO1) like", value.toUpperCase(), "pieceNo1");
            return (Criteria) this;
        }

        public Criteria andWeldingMatialLikeInsensitive(String value) {
            addCriterion("upper(WELDING_MATIAL) like", value.toUpperCase(), "weldingMatial");
            return (Criteria) this;
        }

        public Criteria andPieceNo2LikeInsensitive(String value) {
            addCriterion("upper(PIECE_NO2) like", value.toUpperCase(), "pieceNo2");
            return (Criteria) this;
        }

        public Criteria andHeatNo1LikeInsensitive(String value) {
            addCriterion("upper(HEAT_NO1) like", value.toUpperCase(), "heatNo1");
            return (Criteria) this;
        }

        public Criteria andHeatNo2LikeInsensitive(String value) {
            addCriterion("upper(HEAT_NO2) like", value.toUpperCase(), "heatNo2");
            return (Criteria) this;
        }

        public Criteria andAlterCodeLikeInsensitive(String value) {
            addCriterion("upper(ALTER_CODE) like", value.toUpperCase(), "alterCode");
            return (Criteria) this;
        }

        public Criteria andAlterTypeLikeInsensitive(String value) {
            addCriterion("upper(ALTER_TYPE) like", value.toUpperCase(), "alterType");
            return (Criteria) this;
        }

        public Criteria andDailyNoLikeInsensitive(String value) {
            addCriterion("upper(DAILY_NO) like", value.toUpperCase(), "dailyNo");
            return (Criteria) this;
        }

        public Criteria andHardessRecLikeInsensitive(String value) {
            addCriterion("upper(HARDESS_REC) like", value.toUpperCase(), "hardessRec");
            return (Criteria) this;
        }

        public Criteria andHeatRecLikeInsensitive(String value) {
            addCriterion("upper(HEAT_REC) like", value.toUpperCase(), "heatRec");
            return (Criteria) this;
        }

        public Criteria andRtLotLikeInsensitive(String value) {
            addCriterion("upper(RT_LOT) like", value.toUpperCase(), "rtLot");
            return (Criteria) this;
        }

        public Criteria andRtSampleLikeInsensitive(String value) {
            addCriterion("upper(RT_SAMPLE) like", value.toUpperCase(), "rtSample");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(REMARK) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_line_weld
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 23 12:39:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 焊接记录表
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-23
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}