/**
 *  introspectedTable.getFullyQualifiedTable().getComment()
 * PpLineWeldCheckQueryHelper.java
 * Copyright(C) 2015-2015 xxxxxx公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-07-23 Created
 */
package java;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PpLineWeldCheckQueryHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public PpLineWeldCheckQueryHelper() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 焊接记录质量检查记录
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-23
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("PROJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("PROJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Long value) {
            addCriterion("PROJ_ID =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Long value) {
            addCriterion("PROJ_ID <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Long value) {
            addCriterion("PROJ_ID >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Long value) {
            addCriterion("PROJ_ID <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Long> values) {
            addCriterion("PROJ_ID in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Long> values) {
            addCriterion("PROJ_ID not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andPipeIdIsNull() {
            addCriterion("PIPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andPipeIdIsNotNull() {
            addCriterion("PIPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPipeIdEqualTo(Long value) {
            addCriterion("PIPE_ID =", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdNotEqualTo(Long value) {
            addCriterion("PIPE_ID <>", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdGreaterThan(Long value) {
            addCriterion("PIPE_ID >", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PIPE_ID >=", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdLessThan(Long value) {
            addCriterion("PIPE_ID <", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdLessThanOrEqualTo(Long value) {
            addCriterion("PIPE_ID <=", value, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdIn(List<Long> values) {
            addCriterion("PIPE_ID in", values, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdNotIn(List<Long> values) {
            addCriterion("PIPE_ID not in", values, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdBetween(Long value1, Long value2) {
            addCriterion("PIPE_ID between", value1, value2, "pipeId");
            return (Criteria) this;
        }

        public Criteria andPipeIdNotBetween(Long value1, Long value2) {
            addCriterion("PIPE_ID not between", value1, value2, "pipeId");
            return (Criteria) this;
        }

        public Criteria andJointIdIsNull() {
            addCriterion("JOINT_ID is null");
            return (Criteria) this;
        }

        public Criteria andJointIdIsNotNull() {
            addCriterion("JOINT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJointIdEqualTo(Long value) {
            addCriterion("JOINT_ID =", value, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdNotEqualTo(Long value) {
            addCriterion("JOINT_ID <>", value, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdGreaterThan(Long value) {
            addCriterion("JOINT_ID >", value, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdGreaterThanOrEqualTo(Long value) {
            addCriterion("JOINT_ID >=", value, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdLessThan(Long value) {
            addCriterion("JOINT_ID <", value, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdLessThanOrEqualTo(Long value) {
            addCriterion("JOINT_ID <=", value, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdIn(List<Long> values) {
            addCriterion("JOINT_ID in", values, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdNotIn(List<Long> values) {
            addCriterion("JOINT_ID not in", values, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdBetween(Long value1, Long value2) {
            addCriterion("JOINT_ID between", value1, value2, "jointId");
            return (Criteria) this;
        }

        public Criteria andJointIdNotBetween(Long value1, Long value2) {
            addCriterion("JOINT_ID not between", value1, value2, "jointId");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalIsNull() {
            addCriterion("RTFILM_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalIsNotNull() {
            addCriterion("RTFILM_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalEqualTo(Integer value) {
            addCriterion("RTFILM_TOTAL =", value, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalNotEqualTo(Integer value) {
            addCriterion("RTFILM_TOTAL <>", value, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalGreaterThan(Integer value) {
            addCriterion("RTFILM_TOTAL >", value, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("RTFILM_TOTAL >=", value, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalLessThan(Integer value) {
            addCriterion("RTFILM_TOTAL <", value, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalLessThanOrEqualTo(Integer value) {
            addCriterion("RTFILM_TOTAL <=", value, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalIn(List<Integer> values) {
            addCriterion("RTFILM_TOTAL in", values, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalNotIn(List<Integer> values) {
            addCriterion("RTFILM_TOTAL not in", values, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalBetween(Integer value1, Integer value2) {
            addCriterion("RTFILM_TOTAL between", value1, value2, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("RTFILM_TOTAL not between", value1, value2, "rtfilmTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalIsNull() {
            addCriterion("RTFILM_PASS_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalIsNotNull() {
            addCriterion("RTFILM_PASS_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalEqualTo(Integer value) {
            addCriterion("RTFILM_PASS_TOTAL =", value, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalNotEqualTo(Integer value) {
            addCriterion("RTFILM_PASS_TOTAL <>", value, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalGreaterThan(Integer value) {
            addCriterion("RTFILM_PASS_TOTAL >", value, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("RTFILM_PASS_TOTAL >=", value, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalLessThan(Integer value) {
            addCriterion("RTFILM_PASS_TOTAL <", value, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalLessThanOrEqualTo(Integer value) {
            addCriterion("RTFILM_PASS_TOTAL <=", value, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalIn(List<Integer> values) {
            addCriterion("RTFILM_PASS_TOTAL in", values, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalNotIn(List<Integer> values) {
            addCriterion("RTFILM_PASS_TOTAL not in", values, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalBetween(Integer value1, Integer value2) {
            addCriterion("RTFILM_PASS_TOTAL between", value1, value2, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andRtfilmPassTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("RTFILM_PASS_TOTAL not between", value1, value2, "rtfilmPassTotal");
            return (Criteria) this;
        }

        public Criteria andReportCodeIsNull() {
            addCriterion("REPORT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andReportCodeIsNotNull() {
            addCriterion("REPORT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andReportCodeEqualTo(String value) {
            addCriterion("REPORT_CODE =", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotEqualTo(String value) {
            addCriterion("REPORT_CODE <>", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeGreaterThan(String value) {
            addCriterion("REPORT_CODE >", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeGreaterThanOrEqualTo(String value) {
            addCriterion("REPORT_CODE >=", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLessThan(String value) {
            addCriterion("REPORT_CODE <", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLessThanOrEqualTo(String value) {
            addCriterion("REPORT_CODE <=", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLike(String value) {
            addCriterion("REPORT_CODE like", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotLike(String value) {
            addCriterion("REPORT_CODE not like", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeIn(List<String> values) {
            addCriterion("REPORT_CODE in", values, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotIn(List<String> values) {
            addCriterion("REPORT_CODE not in", values, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeBetween(String value1, String value2) {
            addCriterion("REPORT_CODE between", value1, value2, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotBetween(String value1, String value2) {
            addCriterion("REPORT_CODE not between", value1, value2, "reportCode");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNull() {
            addCriterion("CHECK_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNotNull() {
            addCriterion("CHECK_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCheckDateEqualTo(String value) {
            addCriterion("CHECK_DATE =", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotEqualTo(String value) {
            addCriterion("CHECK_DATE <>", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThan(String value) {
            addCriterion("CHECK_DATE >", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_DATE >=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThan(String value) {
            addCriterion("CHECK_DATE <", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThanOrEqualTo(String value) {
            addCriterion("CHECK_DATE <=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLike(String value) {
            addCriterion("CHECK_DATE like", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotLike(String value) {
            addCriterion("CHECK_DATE not like", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateIn(List<String> values) {
            addCriterion("CHECK_DATE in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotIn(List<String> values) {
            addCriterion("CHECK_DATE not in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateBetween(String value1, String value2) {
            addCriterion("CHECK_DATE between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotBetween(String value1, String value2) {
            addCriterion("CHECK_DATE not between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckResultIsNull() {
            addCriterion("CHECK_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andCheckResultIsNotNull() {
            addCriterion("CHECK_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andCheckResultEqualTo(String value) {
            addCriterion("CHECK_RESULT =", value, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultNotEqualTo(String value) {
            addCriterion("CHECK_RESULT <>", value, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultGreaterThan(String value) {
            addCriterion("CHECK_RESULT >", value, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_RESULT >=", value, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultLessThan(String value) {
            addCriterion("CHECK_RESULT <", value, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultLessThanOrEqualTo(String value) {
            addCriterion("CHECK_RESULT <=", value, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultLike(String value) {
            addCriterion("CHECK_RESULT like", value, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultNotLike(String value) {
            addCriterion("CHECK_RESULT not like", value, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultIn(List<String> values) {
            addCriterion("CHECK_RESULT in", values, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultNotIn(List<String> values) {
            addCriterion("CHECK_RESULT not in", values, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultBetween(String value1, String value2) {
            addCriterion("CHECK_RESULT between", value1, value2, "checkResult");
            return (Criteria) this;
        }

        public Criteria andCheckResultNotBetween(String value1, String value2) {
            addCriterion("CHECK_RESULT not between", value1, value2, "checkResult");
            return (Criteria) this;
        }

        public Criteria andReworkCodeIsNull() {
            addCriterion("REWORK_CODE is null");
            return (Criteria) this;
        }

        public Criteria andReworkCodeIsNotNull() {
            addCriterion("REWORK_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andReworkCodeEqualTo(String value) {
            addCriterion("REWORK_CODE =", value, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeNotEqualTo(String value) {
            addCriterion("REWORK_CODE <>", value, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeGreaterThan(String value) {
            addCriterion("REWORK_CODE >", value, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeGreaterThanOrEqualTo(String value) {
            addCriterion("REWORK_CODE >=", value, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeLessThan(String value) {
            addCriterion("REWORK_CODE <", value, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeLessThanOrEqualTo(String value) {
            addCriterion("REWORK_CODE <=", value, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeLike(String value) {
            addCriterion("REWORK_CODE like", value, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeNotLike(String value) {
            addCriterion("REWORK_CODE not like", value, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeIn(List<String> values) {
            addCriterion("REWORK_CODE in", values, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeNotIn(List<String> values) {
            addCriterion("REWORK_CODE not in", values, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeBetween(String value1, String value2) {
            addCriterion("REWORK_CODE between", value1, value2, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkCodeNotBetween(String value1, String value2) {
            addCriterion("REWORK_CODE not between", value1, value2, "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkWelderIsNull() {
            addCriterion("REWORK_WELDER is null");
            return (Criteria) this;
        }

        public Criteria andReworkWelderIsNotNull() {
            addCriterion("REWORK_WELDER is not null");
            return (Criteria) this;
        }

        public Criteria andReworkWelderEqualTo(String value) {
            addCriterion("REWORK_WELDER =", value, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderNotEqualTo(String value) {
            addCriterion("REWORK_WELDER <>", value, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderGreaterThan(String value) {
            addCriterion("REWORK_WELDER >", value, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderGreaterThanOrEqualTo(String value) {
            addCriterion("REWORK_WELDER >=", value, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderLessThan(String value) {
            addCriterion("REWORK_WELDER <", value, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderLessThanOrEqualTo(String value) {
            addCriterion("REWORK_WELDER <=", value, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderLike(String value) {
            addCriterion("REWORK_WELDER like", value, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderNotLike(String value) {
            addCriterion("REWORK_WELDER not like", value, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderIn(List<String> values) {
            addCriterion("REWORK_WELDER in", values, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderNotIn(List<String> values) {
            addCriterion("REWORK_WELDER not in", values, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderBetween(String value1, String value2) {
            addCriterion("REWORK_WELDER between", value1, value2, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkWelderNotBetween(String value1, String value2) {
            addCriterion("REWORK_WELDER not between", value1, value2, "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkDateIsNull() {
            addCriterion("REWORK_DATE is null");
            return (Criteria) this;
        }

        public Criteria andReworkDateIsNotNull() {
            addCriterion("REWORK_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andReworkDateEqualTo(Date value) {
            addCriterionForJDBCDate("REWORK_DATE =", value, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("REWORK_DATE <>", value, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateGreaterThan(Date value) {
            addCriterionForJDBCDate("REWORK_DATE >", value, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("REWORK_DATE >=", value, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateLessThan(Date value) {
            addCriterionForJDBCDate("REWORK_DATE <", value, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("REWORK_DATE <=", value, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateIn(List<Date> values) {
            addCriterionForJDBCDate("REWORK_DATE in", values, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("REWORK_DATE not in", values, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("REWORK_DATE between", value1, value2, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("REWORK_DATE not between", value1, value2, "reworkDate");
            return (Criteria) this;
        }

        public Criteria andReworkResultIsNull() {
            addCriterion("REWORK_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andReworkResultIsNotNull() {
            addCriterion("REWORK_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andReworkResultEqualTo(String value) {
            addCriterion("REWORK_RESULT =", value, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultNotEqualTo(String value) {
            addCriterion("REWORK_RESULT <>", value, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultGreaterThan(String value) {
            addCriterion("REWORK_RESULT >", value, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultGreaterThanOrEqualTo(String value) {
            addCriterion("REWORK_RESULT >=", value, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultLessThan(String value) {
            addCriterion("REWORK_RESULT <", value, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultLessThanOrEqualTo(String value) {
            addCriterion("REWORK_RESULT <=", value, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultLike(String value) {
            addCriterion("REWORK_RESULT like", value, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultNotLike(String value) {
            addCriterion("REWORK_RESULT not like", value, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultIn(List<String> values) {
            addCriterion("REWORK_RESULT in", values, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultNotIn(List<String> values) {
            addCriterion("REWORK_RESULT not in", values, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultBetween(String value1, String value2) {
            addCriterion("REWORK_RESULT between", value1, value2, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andReworkResultNotBetween(String value1, String value2) {
            addCriterion("REWORK_RESULT not between", value1, value2, "reworkResult");
            return (Criteria) this;
        }

        public Criteria andRepairReportIsNull() {
            addCriterion("REPAIR_REPORT is null");
            return (Criteria) this;
        }

        public Criteria andRepairReportIsNotNull() {
            addCriterion("REPAIR_REPORT is not null");
            return (Criteria) this;
        }

        public Criteria andRepairReportEqualTo(String value) {
            addCriterion("REPAIR_REPORT =", value, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportNotEqualTo(String value) {
            addCriterion("REPAIR_REPORT <>", value, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportGreaterThan(String value) {
            addCriterion("REPAIR_REPORT >", value, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportGreaterThanOrEqualTo(String value) {
            addCriterion("REPAIR_REPORT >=", value, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportLessThan(String value) {
            addCriterion("REPAIR_REPORT <", value, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportLessThanOrEqualTo(String value) {
            addCriterion("REPAIR_REPORT <=", value, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportLike(String value) {
            addCriterion("REPAIR_REPORT like", value, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportNotLike(String value) {
            addCriterion("REPAIR_REPORT not like", value, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportIn(List<String> values) {
            addCriterion("REPAIR_REPORT in", values, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportNotIn(List<String> values) {
            addCriterion("REPAIR_REPORT not in", values, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportBetween(String value1, String value2) {
            addCriterion("REPAIR_REPORT between", value1, value2, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRepairReportNotBetween(String value1, String value2) {
            addCriterion("REPAIR_REPORT not between", value1, value2, "repairReport");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andReportCodeLikeInsensitive(String value) {
            addCriterion("upper(REPORT_CODE) like", value.toUpperCase(), "reportCode");
            return (Criteria) this;
        }

        public Criteria andCheckDateLikeInsensitive(String value) {
            addCriterion("upper(CHECK_DATE) like", value.toUpperCase(), "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckResultLikeInsensitive(String value) {
            addCriterion("upper(CHECK_RESULT) like", value.toUpperCase(), "checkResult");
            return (Criteria) this;
        }

        public Criteria andReworkCodeLikeInsensitive(String value) {
            addCriterion("upper(REWORK_CODE) like", value.toUpperCase(), "reworkCode");
            return (Criteria) this;
        }

        public Criteria andReworkWelderLikeInsensitive(String value) {
            addCriterion("upper(REWORK_WELDER) like", value.toUpperCase(), "reworkWelder");
            return (Criteria) this;
        }

        public Criteria andReworkResultLikeInsensitive(String value) {
            addCriterion("upper(REWORK_RESULT) like", value.toUpperCase(), "reworkResult");
            return (Criteria) this;
        }

        public Criteria andRepairReportLikeInsensitive(String value) {
            addCriterion("upper(REPAIR_REPORT) like", value.toUpperCase(), "repairReport");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(REMARK) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 23 12:39:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 焊接记录质量检查记录
     * 
     * @author 菠萝大象
     * @version 1.0 2017-07-23
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}