package java;

import java.io.Serializable;
import java.util.Date;

/**
 * 焊接记录质量检查记录
 * 
 * @author 菠萝大象
 * @version 1.0 2017-07-23
 */
public class PpLineWeldCheck implements Serializable {
    private Long id;

    private Long projId;

    private Long pipeId;

    private Long jointId;

    /**
     * @rt
     */
    private Integer rtfilmTotal;

    /**
     * @rt
     */
    private Integer rtfilmPassTotal;

    /**
     * @rt
     */
    private String reportCode;

    /**
     * @rt
     */
    private String checkDate;

    private String checkResult;

    private String reworkCode;

    private String reworkWelder;

    private Date reworkDate;

    private String reworkResult;

    private String repairReport;

    private String remark;

    private Date createTime;

    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.ID
     *
     * @return the value of pp_line_weld_check.ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.ID
     *
     * @param id the value for pp_line_weld_check.ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.PROJ_ID
     *
     * @return the value of pp_line_weld_check.PROJ_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Long getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.PROJ_ID
     *
     * @param projId the value for pp_line_weld_check.PROJ_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setProjId(Long projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.PIPE_ID
     *
     * @return the value of pp_line_weld_check.PIPE_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Long getPipeId() {
        return pipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.PIPE_ID
     *
     * @param pipeId the value for pp_line_weld_check.PIPE_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setPipeId(Long pipeId) {
        this.pipeId = pipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.JOINT_ID
     *
     * @return the value of pp_line_weld_check.JOINT_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Long getJointId() {
        return jointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.JOINT_ID
     *
     * @param jointId the value for pp_line_weld_check.JOINT_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setJointId(Long jointId) {
        this.jointId = jointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.RTFILM_TOTAL
     *
     * @return the value of pp_line_weld_check.RTFILM_TOTAL
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Integer getRtfilmTotal() {
        return rtfilmTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.RTFILM_TOTAL
     *
     * @param rtfilmTotal the value for pp_line_weld_check.RTFILM_TOTAL
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setRtfilmTotal(Integer rtfilmTotal) {
        this.rtfilmTotal = rtfilmTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.RTFILM_PASS_TOTAL
     *
     * @return the value of pp_line_weld_check.RTFILM_PASS_TOTAL
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Integer getRtfilmPassTotal() {
        return rtfilmPassTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.RTFILM_PASS_TOTAL
     *
     * @param rtfilmPassTotal the value for pp_line_weld_check.RTFILM_PASS_TOTAL
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setRtfilmPassTotal(Integer rtfilmPassTotal) {
        this.rtfilmPassTotal = rtfilmPassTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.REPORT_CODE
     *
     * @return the value of pp_line_weld_check.REPORT_CODE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getReportCode() {
        return reportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.REPORT_CODE
     *
     * @param reportCode the value for pp_line_weld_check.REPORT_CODE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setReportCode(String reportCode) {
        this.reportCode = reportCode == null ? null : reportCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.CHECK_DATE
     *
     * @return the value of pp_line_weld_check.CHECK_DATE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.CHECK_DATE
     *
     * @param checkDate the value for pp_line_weld_check.CHECK_DATE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate == null ? null : checkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.CHECK_RESULT
     *
     * @return the value of pp_line_weld_check.CHECK_RESULT
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.CHECK_RESULT
     *
     * @param checkResult the value for pp_line_weld_check.CHECK_RESULT
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult == null ? null : checkResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.REWORK_CODE
     *
     * @return the value of pp_line_weld_check.REWORK_CODE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getReworkCode() {
        return reworkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.REWORK_CODE
     *
     * @param reworkCode the value for pp_line_weld_check.REWORK_CODE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setReworkCode(String reworkCode) {
        this.reworkCode = reworkCode == null ? null : reworkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.REWORK_WELDER
     *
     * @return the value of pp_line_weld_check.REWORK_WELDER
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getReworkWelder() {
        return reworkWelder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.REWORK_WELDER
     *
     * @param reworkWelder the value for pp_line_weld_check.REWORK_WELDER
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setReworkWelder(String reworkWelder) {
        this.reworkWelder = reworkWelder == null ? null : reworkWelder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.REWORK_DATE
     *
     * @return the value of pp_line_weld_check.REWORK_DATE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Date getReworkDate() {
        return reworkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.REWORK_DATE
     *
     * @param reworkDate the value for pp_line_weld_check.REWORK_DATE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setReworkDate(Date reworkDate) {
        this.reworkDate = reworkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.REWORK_RESULT
     *
     * @return the value of pp_line_weld_check.REWORK_RESULT
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getReworkResult() {
        return reworkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.REWORK_RESULT
     *
     * @param reworkResult the value for pp_line_weld_check.REWORK_RESULT
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setReworkResult(String reworkResult) {
        this.reworkResult = reworkResult == null ? null : reworkResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.REPAIR_REPORT
     *
     * @return the value of pp_line_weld_check.REPAIR_REPORT
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getRepairReport() {
        return repairReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.REPAIR_REPORT
     *
     * @param repairReport the value for pp_line_weld_check.REPAIR_REPORT
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setRepairReport(String repairReport) {
        this.repairReport = repairReport == null ? null : repairReport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.REMARK
     *
     * @return the value of pp_line_weld_check.REMARK
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.REMARK
     *
     * @param remark the value for pp_line_weld_check.REMARK
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.CREATE_TIME
     *
     * @return the value of pp_line_weld_check.CREATE_TIME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.CREATE_TIME
     *
     * @param createTime the value for pp_line_weld_check.CREATE_TIME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_check.DEL_FLAG
     *
     * @return the value of pp_line_weld_check.DEL_FLAG
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_check.DEL_FLAG
     *
     * @param delFlag the value for pp_line_weld_check.DEL_FLAG
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PpLineWeldCheck other = (PpLineWeldCheck) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProjId() == null ? other.getProjId() == null : this.getProjId().equals(other.getProjId()))
            && (this.getPipeId() == null ? other.getPipeId() == null : this.getPipeId().equals(other.getPipeId()))
            && (this.getJointId() == null ? other.getJointId() == null : this.getJointId().equals(other.getJointId()))
            && (this.getRtfilmTotal() == null ? other.getRtfilmTotal() == null : this.getRtfilmTotal().equals(other.getRtfilmTotal()))
            && (this.getRtfilmPassTotal() == null ? other.getRtfilmPassTotal() == null : this.getRtfilmPassTotal().equals(other.getRtfilmPassTotal()))
            && (this.getReportCode() == null ? other.getReportCode() == null : this.getReportCode().equals(other.getReportCode()))
            && (this.getCheckDate() == null ? other.getCheckDate() == null : this.getCheckDate().equals(other.getCheckDate()))
            && (this.getCheckResult() == null ? other.getCheckResult() == null : this.getCheckResult().equals(other.getCheckResult()))
            && (this.getReworkCode() == null ? other.getReworkCode() == null : this.getReworkCode().equals(other.getReworkCode()))
            && (this.getReworkWelder() == null ? other.getReworkWelder() == null : this.getReworkWelder().equals(other.getReworkWelder()))
            && (this.getReworkDate() == null ? other.getReworkDate() == null : this.getReworkDate().equals(other.getReworkDate()))
            && (this.getReworkResult() == null ? other.getReworkResult() == null : this.getReworkResult().equals(other.getReworkResult()))
            && (this.getRepairReport() == null ? other.getRepairReport() == null : this.getRepairReport().equals(other.getRepairReport()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_check
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjId() == null) ? 0 : getProjId().hashCode());
        result = prime * result + ((getPipeId() == null) ? 0 : getPipeId().hashCode());
        result = prime * result + ((getJointId() == null) ? 0 : getJointId().hashCode());
        result = prime * result + ((getRtfilmTotal() == null) ? 0 : getRtfilmTotal().hashCode());
        result = prime * result + ((getRtfilmPassTotal() == null) ? 0 : getRtfilmPassTotal().hashCode());
        result = prime * result + ((getReportCode() == null) ? 0 : getReportCode().hashCode());
        result = prime * result + ((getCheckDate() == null) ? 0 : getCheckDate().hashCode());
        result = prime * result + ((getCheckResult() == null) ? 0 : getCheckResult().hashCode());
        result = prime * result + ((getReworkCode() == null) ? 0 : getReworkCode().hashCode());
        result = prime * result + ((getReworkWelder() == null) ? 0 : getReworkWelder().hashCode());
        result = prime * result + ((getReworkDate() == null) ? 0 : getReworkDate().hashCode());
        result = prime * result + ((getReworkResult() == null) ? 0 : getReworkResult().hashCode());
        result = prime * result + ((getRepairReport() == null) ? 0 : getRepairReport().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }
}