package java;

import java.io.Serializable;
import java.util.Date;

/**
 * 管线-焊接材料记录表
 * 
 * @author 菠萝大象
 * @version 1.0 2017-07-18
 */
public class PpLineWeldMaterial implements Serializable {
    private Long id;

    private Long pipelineId;

    private Integer pageCode;

    private Integer sequenceNumber;

    private String materialCode;

    private String name;

    private String materialDesc;

    private String spec;

    private String unit;

    private String material;

    private String designQty;

    private String remark;

    private Date createTime;

    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_line_weld_material
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.ID
     *
     * @return the value of pp_line_weld_material.ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.ID
     *
     * @param id the value for pp_line_weld_material.ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.PIPELINE_ID
     *
     * @return the value of pp_line_weld_material.PIPELINE_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Long getPipelineId() {
        return pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.PIPELINE_ID
     *
     * @param pipelineId the value for pp_line_weld_material.PIPELINE_ID
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setPipelineId(Long pipelineId) {
        this.pipelineId = pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.PAGE_CODE
     *
     * @return the value of pp_line_weld_material.PAGE_CODE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Integer getPageCode() {
        return pageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.PAGE_CODE
     *
     * @param pageCode the value for pp_line_weld_material.PAGE_CODE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setPageCode(Integer pageCode) {
        this.pageCode = pageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.SEQUENCE_NUMBER
     *
     * @return the value of pp_line_weld_material.SEQUENCE_NUMBER
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.SEQUENCE_NUMBER
     *
     * @param sequenceNumber the value for pp_line_weld_material.SEQUENCE_NUMBER
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.MATERIAL_CODE
     *
     * @return the value of pp_line_weld_material.MATERIAL_CODE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.MATERIAL_CODE
     *
     * @param materialCode the value for pp_line_weld_material.MATERIAL_CODE
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode == null ? null : materialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.NAME
     *
     * @return the value of pp_line_weld_material.NAME
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.NAME
     *
     * @param name the value for pp_line_weld_material.NAME
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.MATERIAL_DESC
     *
     * @return the value of pp_line_weld_material.MATERIAL_DESC
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getMaterialDesc() {
        return materialDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.MATERIAL_DESC
     *
     * @param materialDesc the value for pp_line_weld_material.MATERIAL_DESC
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setMaterialDesc(String materialDesc) {
        this.materialDesc = materialDesc == null ? null : materialDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.SPEC
     *
     * @return the value of pp_line_weld_material.SPEC
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.SPEC
     *
     * @param spec the value for pp_line_weld_material.SPEC
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.UNIT
     *
     * @return the value of pp_line_weld_material.UNIT
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.UNIT
     *
     * @param unit the value for pp_line_weld_material.UNIT
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.MATERIAL
     *
     * @return the value of pp_line_weld_material.MATERIAL
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.MATERIAL
     *
     * @param material the value for pp_line_weld_material.MATERIAL
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.DESIGN_QTY
     *
     * @return the value of pp_line_weld_material.DESIGN_QTY
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getDesignQty() {
        return designQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.DESIGN_QTY
     *
     * @param designQty the value for pp_line_weld_material.DESIGN_QTY
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setDesignQty(String designQty) {
        this.designQty = designQty == null ? null : designQty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.REMARK
     *
     * @return the value of pp_line_weld_material.REMARK
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.REMARK
     *
     * @param remark the value for pp_line_weld_material.REMARK
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.CREATE_TIME
     *
     * @return the value of pp_line_weld_material.CREATE_TIME
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.CREATE_TIME
     *
     * @param createTime the value for pp_line_weld_material.CREATE_TIME
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_line_weld_material.DEL_FLAG
     *
     * @return the value of pp_line_weld_material.DEL_FLAG
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_line_weld_material.DEL_FLAG
     *
     * @param delFlag the value for pp_line_weld_material.DEL_FLAG
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_material
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PpLineWeldMaterial other = (PpLineWeldMaterial) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPipelineId() == null ? other.getPipelineId() == null : this.getPipelineId().equals(other.getPipelineId()))
            && (this.getPageCode() == null ? other.getPageCode() == null : this.getPageCode().equals(other.getPageCode()))
            && (this.getSequenceNumber() == null ? other.getSequenceNumber() == null : this.getSequenceNumber().equals(other.getSequenceNumber()))
            && (this.getMaterialCode() == null ? other.getMaterialCode() == null : this.getMaterialCode().equals(other.getMaterialCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMaterialDesc() == null ? other.getMaterialDesc() == null : this.getMaterialDesc().equals(other.getMaterialDesc()))
            && (this.getSpec() == null ? other.getSpec() == null : this.getSpec().equals(other.getSpec()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getMaterial() == null ? other.getMaterial() == null : this.getMaterial().equals(other.getMaterial()))
            && (this.getDesignQty() == null ? other.getDesignQty() == null : this.getDesignQty().equals(other.getDesignQty()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_line_weld_material
     *
     * @mbggenerated Tue Jul 18 17:06:29 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPipelineId() == null) ? 0 : getPipelineId().hashCode());
        result = prime * result + ((getPageCode() == null) ? 0 : getPageCode().hashCode());
        result = prime * result + ((getSequenceNumber() == null) ? 0 : getSequenceNumber().hashCode());
        result = prime * result + ((getMaterialCode() == null) ? 0 : getMaterialCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMaterialDesc() == null) ? 0 : getMaterialDesc().hashCode());
        result = prime * result + ((getSpec() == null) ? 0 : getSpec().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getMaterial() == null) ? 0 : getMaterial().hashCode());
        result = prime * result + ((getDesignQty() == null) ? 0 : getDesignQty().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }
}