package java;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 聚诚通会员等级表
 * 
 * @author 菠萝大象
 * @version 1.0 2017-08-28
 */
public class UserLevel implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 会员等级代码
     */
    private Short userLevelCode;

    /**
     * 会员等级名称
     */
    private String userLevelName;

    /**
     * 每日接收采购、商讯数量
     */
    private Short receiveNicheCount;

    /**
     * 每日商品接收数量
     */
    private Short receiveGoodsCount;

    /**
     * 每周商品推送商品次数
     */
    private Short pushGoodsCount;

    /**
     * 价格
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_user_level
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_level.id
     *
     * @return the value of trade_user_level.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_level.id
     *
     * @param id the value for trade_user_level.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_level.user_level_code
     *
     * @return the value of trade_user_level.user_level_code
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getUserLevelCode() {
        return userLevelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_level.user_level_code
     *
     * @param userLevelCode the value for trade_user_level.user_level_code
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUserLevelCode(Short userLevelCode) {
        this.userLevelCode = userLevelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_level.user_level_name
     *
     * @return the value of trade_user_level.user_level_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getUserLevelName() {
        return userLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_level.user_level_name
     *
     * @param userLevelName the value for trade_user_level.user_level_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUserLevelName(String userLevelName) {
        this.userLevelName = userLevelName == null ? null : userLevelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_level.receive_niche_count
     *
     * @return the value of trade_user_level.receive_niche_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getReceiveNicheCount() {
        return receiveNicheCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_level.receive_niche_count
     *
     * @param receiveNicheCount the value for trade_user_level.receive_niche_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setReceiveNicheCount(Short receiveNicheCount) {
        this.receiveNicheCount = receiveNicheCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_level.receive_goods_count
     *
     * @return the value of trade_user_level.receive_goods_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getReceiveGoodsCount() {
        return receiveGoodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_level.receive_goods_count
     *
     * @param receiveGoodsCount the value for trade_user_level.receive_goods_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setReceiveGoodsCount(Short receiveGoodsCount) {
        this.receiveGoodsCount = receiveGoodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_level.push_goods_count
     *
     * @return the value of trade_user_level.push_goods_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getPushGoodsCount() {
        return pushGoodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_level.push_goods_count
     *
     * @param pushGoodsCount the value for trade_user_level.push_goods_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPushGoodsCount(Short pushGoodsCount) {
        this.pushGoodsCount = pushGoodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_user_level.price
     *
     * @return the value of trade_user_level.price
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_user_level.price
     *
     * @param price the value for trade_user_level.price
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_level
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserLevel other = (UserLevel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserLevelCode() == null ? other.getUserLevelCode() == null : this.getUserLevelCode().equals(other.getUserLevelCode()))
            && (this.getUserLevelName() == null ? other.getUserLevelName() == null : this.getUserLevelName().equals(other.getUserLevelName()))
            && (this.getReceiveNicheCount() == null ? other.getReceiveNicheCount() == null : this.getReceiveNicheCount().equals(other.getReceiveNicheCount()))
            && (this.getReceiveGoodsCount() == null ? other.getReceiveGoodsCount() == null : this.getReceiveGoodsCount().equals(other.getReceiveGoodsCount()))
            && (this.getPushGoodsCount() == null ? other.getPushGoodsCount() == null : this.getPushGoodsCount().equals(other.getPushGoodsCount()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_level
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserLevelCode() == null) ? 0 : getUserLevelCode().hashCode());
        result = prime * result + ((getUserLevelName() == null) ? 0 : getUserLevelName().hashCode());
        result = prime * result + ((getReceiveNicheCount() == null) ? 0 : getReceiveNicheCount().hashCode());
        result = prime * result + ((getReceiveGoodsCount() == null) ? 0 : getReceiveGoodsCount().hashCode());
        result = prime * result + ((getPushGoodsCount() == null) ? 0 : getPushGoodsCount().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        return result;
    }
}