package java;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 支付码批次表
 * 
 * @author 菠萝大象
 * @version 1.0 2017-08-28
 */
public class VipCoupon implements Serializable {
    private Long id;

    /**
     * 优惠码名称
     */
    private String couponName;

    /**
     * 优惠码数量
     */
    private Integer couponCount;

    /**
     * 有效期起
     */
    private Date expiryDateFrom;

    /**
     * 有效期止
     */
    private Date expiryDateTo;

    /**
     * 优惠码适用于等级 0:通用 2:黄金会员 3:铂金会员
     */
    private Short applyUserLevel;

    /**
     * 优化类型,0折扣，1金额
     */
    private Short couponType;

    /**
     * 折扣，保留两位小数
     */
    private BigDecimal discount;

    /**
     * 折扣金额
     */
    private BigDecimal discountAmount;

    /**
     * 状态，0进行中，1已结束
     */
    private Short status;

    /**
     * 是否删除
     */
    private Short deleteFlag;

    /**
     * 创建人
     */
    private Long createId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改人
     */
    private Long updateId;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 批次号
     */
    private Short seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_vip_coupon
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.id
     *
     * @return the value of trade_vip_coupon.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.id
     *
     * @param id the value for trade_vip_coupon.id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.coupon_name
     *
     * @return the value of trade_vip_coupon.coupon_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.coupon_name
     *
     * @param couponName the value for trade_vip_coupon.coupon_name
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.coupon_count
     *
     * @return the value of trade_vip_coupon.coupon_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Integer getCouponCount() {
        return couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.coupon_count
     *
     * @param couponCount the value for trade_vip_coupon.coupon_count
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCouponCount(Integer couponCount) {
        this.couponCount = couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.expiry_date_from
     *
     * @return the value of trade_vip_coupon.expiry_date_from
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getExpiryDateFrom() {
        return expiryDateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.expiry_date_from
     *
     * @param expiryDateFrom the value for trade_vip_coupon.expiry_date_from
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setExpiryDateFrom(Date expiryDateFrom) {
        this.expiryDateFrom = expiryDateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.expiry_date_to
     *
     * @return the value of trade_vip_coupon.expiry_date_to
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getExpiryDateTo() {
        return expiryDateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.expiry_date_to
     *
     * @param expiryDateTo the value for trade_vip_coupon.expiry_date_to
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setExpiryDateTo(Date expiryDateTo) {
        this.expiryDateTo = expiryDateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.apply_user_level
     *
     * @return the value of trade_vip_coupon.apply_user_level
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getApplyUserLevel() {
        return applyUserLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.apply_user_level
     *
     * @param applyUserLevel the value for trade_vip_coupon.apply_user_level
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setApplyUserLevel(Short applyUserLevel) {
        this.applyUserLevel = applyUserLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.coupon_type
     *
     * @return the value of trade_vip_coupon.coupon_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.coupon_type
     *
     * @param couponType the value for trade_vip_coupon.coupon_type
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCouponType(Short couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.discount
     *
     * @return the value of trade_vip_coupon.discount
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.discount
     *
     * @param discount the value for trade_vip_coupon.discount
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.discount_amount
     *
     * @return the value of trade_vip_coupon.discount_amount
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.discount_amount
     *
     * @param discountAmount the value for trade_vip_coupon.discount_amount
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.status
     *
     * @return the value of trade_vip_coupon.status
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.status
     *
     * @param status the value for trade_vip_coupon.status
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.delete_flag
     *
     * @return the value of trade_vip_coupon.delete_flag
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.delete_flag
     *
     * @param deleteFlag the value for trade_vip_coupon.delete_flag
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.create_id
     *
     * @return the value of trade_vip_coupon.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.create_id
     *
     * @param createId the value for trade_vip_coupon.create_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.create_time
     *
     * @return the value of trade_vip_coupon.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.create_time
     *
     * @param createTime the value for trade_vip_coupon.create_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.update_id
     *
     * @return the value of trade_vip_coupon.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.update_id
     *
     * @param updateId the value for trade_vip_coupon.update_id
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.update_time
     *
     * @return the value of trade_vip_coupon.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.update_time
     *
     * @param updateTime the value for trade_vip_coupon.update_time
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_vip_coupon.seq
     *
     * @return the value of trade_vip_coupon.seq
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public Short getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_vip_coupon.seq
     *
     * @param seq the value for trade_vip_coupon.seq
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    public void setSeq(Short seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_vip_coupon
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VipCoupon other = (VipCoupon) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCouponName() == null ? other.getCouponName() == null : this.getCouponName().equals(other.getCouponName()))
            && (this.getCouponCount() == null ? other.getCouponCount() == null : this.getCouponCount().equals(other.getCouponCount()))
            && (this.getExpiryDateFrom() == null ? other.getExpiryDateFrom() == null : this.getExpiryDateFrom().equals(other.getExpiryDateFrom()))
            && (this.getExpiryDateTo() == null ? other.getExpiryDateTo() == null : this.getExpiryDateTo().equals(other.getExpiryDateTo()))
            && (this.getApplyUserLevel() == null ? other.getApplyUserLevel() == null : this.getApplyUserLevel().equals(other.getApplyUserLevel()))
            && (this.getCouponType() == null ? other.getCouponType() == null : this.getCouponType().equals(other.getCouponType()))
            && (this.getDiscount() == null ? other.getDiscount() == null : this.getDiscount().equals(other.getDiscount()))
            && (this.getDiscountAmount() == null ? other.getDiscountAmount() == null : this.getDiscountAmount().equals(other.getDiscountAmount()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getSeq() == null ? other.getSeq() == null : this.getSeq().equals(other.getSeq()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_vip_coupon
     *
     * @mbggenerated Mon Aug 28 11:46:45 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCouponName() == null) ? 0 : getCouponName().hashCode());
        result = prime * result + ((getCouponCount() == null) ? 0 : getCouponCount().hashCode());
        result = prime * result + ((getExpiryDateFrom() == null) ? 0 : getExpiryDateFrom().hashCode());
        result = prime * result + ((getExpiryDateTo() == null) ? 0 : getExpiryDateTo().hashCode());
        result = prime * result + ((getApplyUserLevel() == null) ? 0 : getApplyUserLevel().hashCode());
        result = prime * result + ((getCouponType() == null) ? 0 : getCouponType().hashCode());
        result = prime * result + ((getDiscount() == null) ? 0 : getDiscount().hashCode());
        result = prime * result + ((getDiscountAmount() == null) ? 0 : getDiscountAmount().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
        return result;
    }
}