package java;

import java.io.Serializable;
import java.util.Date;

/**
 * 焊工技能表
 * 
 * @author 菠萝大象
 * @version 1.0 2017-07-23
 */
public class WelderSkill implements Serializable {
    private Long id;

    private Long welderId;

    private String name;

    private Date assessmentDate;

    private Date effectiveDate;

    private Date createTime;

    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table welder_skill
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder_skill.ID
     *
     * @return the value of welder_skill.ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder_skill.ID
     *
     * @param id the value for welder_skill.ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder_skill.WELDER_ID
     *
     * @return the value of welder_skill.WELDER_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Long getWelderId() {
        return welderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder_skill.WELDER_ID
     *
     * @param welderId the value for welder_skill.WELDER_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setWelderId(Long welderId) {
        this.welderId = welderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder_skill.NAME
     *
     * @return the value of welder_skill.NAME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder_skill.NAME
     *
     * @param name the value for welder_skill.NAME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder_skill.ASSESSMENT_DATE
     *
     * @return the value of welder_skill.ASSESSMENT_DATE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Date getAssessmentDate() {
        return assessmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder_skill.ASSESSMENT_DATE
     *
     * @param assessmentDate the value for welder_skill.ASSESSMENT_DATE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setAssessmentDate(Date assessmentDate) {
        this.assessmentDate = assessmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder_skill.EFFECTIVE_DATE
     *
     * @return the value of welder_skill.EFFECTIVE_DATE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder_skill.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for welder_skill.EFFECTIVE_DATE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder_skill.CREATE_TIME
     *
     * @return the value of welder_skill.CREATE_TIME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder_skill.CREATE_TIME
     *
     * @param createTime the value for welder_skill.CREATE_TIME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder_skill.DEL_FLAG
     *
     * @return the value of welder_skill.DEL_FLAG
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder_skill.DEL_FLAG
     *
     * @param delFlag the value for welder_skill.DEL_FLAG
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welder_skill
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WelderSkill other = (WelderSkill) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWelderId() == null ? other.getWelderId() == null : this.getWelderId().equals(other.getWelderId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAssessmentDate() == null ? other.getAssessmentDate() == null : this.getAssessmentDate().equals(other.getAssessmentDate()))
            && (this.getEffectiveDate() == null ? other.getEffectiveDate() == null : this.getEffectiveDate().equals(other.getEffectiveDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welder_skill
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWelderId() == null) ? 0 : getWelderId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAssessmentDate() == null) ? 0 : getAssessmentDate().hashCode());
        result = prime * result + ((getEffectiveDate() == null) ? 0 : getEffectiveDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }
}