package java;

import java.io.Serializable;
import java.util.Date;

/**
 * 焊工工人表-包括：焊工姓名、手机号码、所在班组等
 * 
 * @author 菠萝大象
 * @version 1.0 2017-07-23
 */
public class Welder implements Serializable {
    private Long id;

    private Long compId;

    private String code;

    private String name;

    private String mobille;

    private String identityCard;

    private String workTerm;

    private String unitName;

    private Date createTime;

    private Integer delFlag;

    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table welder
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.ID
     *
     * @return the value of welder.ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.ID
     *
     * @param id the value for welder.ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.COMP_ID
     *
     * @return the value of welder.COMP_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.COMP_ID
     *
     * @param compId the value for welder.COMP_ID
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.CODE
     *
     * @return the value of welder.CODE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.CODE
     *
     * @param code the value for welder.CODE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.NAME
     *
     * @return the value of welder.NAME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.NAME
     *
     * @param name the value for welder.NAME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.MOBILLE
     *
     * @return the value of welder.MOBILLE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getMobille() {
        return mobille;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.MOBILLE
     *
     * @param mobille the value for welder.MOBILLE
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setMobille(String mobille) {
        this.mobille = mobille == null ? null : mobille.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.IDENTITY_CARD
     *
     * @return the value of welder.IDENTITY_CARD
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.IDENTITY_CARD
     *
     * @param identityCard the value for welder.IDENTITY_CARD
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.WORK_TERM
     *
     * @return the value of welder.WORK_TERM
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getWorkTerm() {
        return workTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.WORK_TERM
     *
     * @param workTerm the value for welder.WORK_TERM
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setWorkTerm(String workTerm) {
        this.workTerm = workTerm == null ? null : workTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.UNIT_NAME
     *
     * @return the value of welder.UNIT_NAME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.UNIT_NAME
     *
     * @param unitName the value for welder.UNIT_NAME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.CREATE_TIME
     *
     * @return the value of welder.CREATE_TIME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.CREATE_TIME
     *
     * @param createTime the value for welder.CREATE_TIME
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.DEL_FLAG
     *
     * @return the value of welder.DEL_FLAG
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.DEL_FLAG
     *
     * @param delFlag the value for welder.DEL_FLAG
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welder.REMARK
     *
     * @return the value of welder.REMARK
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welder.REMARK
     *
     * @param remark the value for welder.REMARK
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welder
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Welder other = (Welder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompId() == null ? other.getCompId() == null : this.getCompId().equals(other.getCompId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMobille() == null ? other.getMobille() == null : this.getMobille().equals(other.getMobille()))
            && (this.getIdentityCard() == null ? other.getIdentityCard() == null : this.getIdentityCard().equals(other.getIdentityCard()))
            && (this.getWorkTerm() == null ? other.getWorkTerm() == null : this.getWorkTerm().equals(other.getWorkTerm()))
            && (this.getUnitName() == null ? other.getUnitName() == null : this.getUnitName().equals(other.getUnitName()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welder
     *
     * @mbggenerated Sun Jul 23 12:39:36 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompId() == null) ? 0 : getCompId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMobille() == null) ? 0 : getMobille().hashCode());
        result = prime * result + ((getIdentityCard() == null) ? 0 : getIdentityCard().hashCode());
        result = prime * result + ((getWorkTerm() == null) ? 0 : getWorkTerm().hashCode());
        result = prime * result + ((getUnitName() == null) ? 0 : getUnitName().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}